Repository webpack/webpack-cli, pull requests merged in 2018-11, with the labels that each got.

#670 cli(color): document --no-color option
  bin/cli.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#678 cli(loaders): support for babel 7, babel-loader 8
  MIGRATE.md
  packages/generators/init-generator.ts
  packages/generators/utils/module.ts
  packages/migrate/loaders/__snapshots__/loaders.test.js.snap
  packages/migrate/loaders/__testfixtures__/loaders-7.input.js
Labels: PR: CI-ok, PR: reviewed-approved

#630 feat: install init as global dep
  bin/prompt-command.js
  package-lock.json
  package.json
Labels: PR: reviewed-approved, PR: reviewed-changes-requested, PR: small

#686 tests(webpack-scaffold): move to typescript
  packages/webpack-scaffold/__tests__/__snapshots__/index.test.ts.snap
  packages/webpack-scaffold/__tests__/index.test.ts
  packages/webpack-scaffold/index.ts
Labels: PR: reviewed-approved

#687 [Docs]: Fix typos and improve intro wording
  README.md
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#682 docs: correct use of individual package in node env
  packages/add/README.md
  packages/generate-loader/README.md
  packages/generate-plugin/README.md
  packages/info/README.md
  packages/init/README.md
  packages/migrate/README.md
  packages/remove/README.md
  packages/serve/README.md
  packages/update/README.md
Labels: PR: CI-ok, PR: reviewed-approved

#683 feat(tests): add extractHash support in test-infra
  test/test-utils.test.js
  test/testUtils.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: reviewed-changes-requested

#692 chore(ci): increase travis wait timer
  .travis.yml
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#680 cli: Fix file lookup on generators & missing module
  packages/generators/add-generator.ts
  packages/remove/index.ts
  packages/update/index.ts
  packages/utils/modify-config-helper.ts
Labels: PR: CI-not-ok, PR: reviewed-approved

#691 chore(deps): fix vulnerable packages, upgrades
  package-lock.json
  package.json
  packages/add/package-lock.json
  packages/add/package.json
  packages/generate-loader/package-lock.json
  packages/generate-loader/package.json
  packages/generate-plugin/package-lock.json
  packages/generate-plugin/package.json
  packages/generators/package-lock.json
  packages/generators/package.json
  packages/info/package-lock.json
  packages/info/package.json
  packages/init/package-lock.json
  packages/init/package.json
  packages/make/package-lock.json
  packages/make/package.json
  packages/migrate/package-lock.json
  packages/migrate/package.json
  packages/remove/package-lock.json
  packages/remove/package.json
  packages/serve/package-lock.json
  packages/serve/package.json
  packages/update/package-lock.json
  packages/update/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
  packages/webpack-scaffold/package-lock.json
  packages/webpack-scaffold/package.json
Labels: PR: reviewed-approved

#695 Adding tasks for publishing results
  azure-pipelines.yml
  package-lock.json
  package.json
Labels: PR: review-outdated

#696 chore(travis): add wait timer for installation, remove redundant script
  .travis.yml
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
