Repository webpack/webpack-cli, pull requests merged in 2018-05, with the labels that each got.

#432 chore(templates): Update issue templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: PR: CI-ok, PR: unreviewed

#441 cli(init): revise installation steps
  lib/generators/init-generator.js
  lib/utils/package-manager.js
  lib/utils/package-manager.test.js
  package-lock.json
Labels: PR: CI-not-ok, PR: unreviewed

#444 chore(travis): run lockfile cmds on tests
  .travis.yml
Labels: PR: small, PR: unreviewed

#425 chore(travis): add Node.js 10
  .travis.yml
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#424 chore(travis): move npm ci to install task
  .appveyor.yml
  .travis.yml
Labels: PR: reviewed-approved, PR: small

#452 cli(color): don't use supports-color on non-tty
  bin/cli.js
  bin/process-options.js
Labels: PR: reviewed-approved, Semver: patch 🔧

#455 Added yarn lock file to gitignore
  .gitignore
Labels: PR: reviewed-approved, PR: small

#453 cli(symlinks): Fix paths
  bin/cli.js
  bin/config-yargs.js
  bin/convert-argv.js
  bin/optionsSchema.json
  package-lock.json
  package.json
  packages/generators/add-generator.js
  packages/generators/utils/optionsSchema.json
  packages/migrate/__testfixtures__/failing.js
  packages/migrate/index.js
  packages/utils/__testfixtures__/fixture-0.input.js
  test/binCases/configFile/plugins-precedence/webpack.config.js
Labels: PR: unreviewed, Semver: patch 🔧

#451 cli(init): Better defaults
  INIT.md
  packages/generators/init-generator.js
  packages/generators/utils/entry.js
  packages/generators/utils/module.js
  packages/utils/ast-utils.js
  packages/utils/prop-types.js
  packages/utils/recursive-parser.js
  packages/utils/scaffold.js
Labels: PR: review-outdated, PR: small, Semver: minor ⚙️

#460 Fix vulnerabilities: v3
  package-lock.json
  package.json
  packages/generate-loader/package-lock.json
  packages/generate-loader/package.json
  packages/generate-plugin/package-lock.json
  packages/generate-plugin/package.json
  packages/generators/package-lock.json
  packages/info/package.json
  packages/init/package-lock.json
  packages/migrate/package-lock.json
  packages/serve/package-lock.json
  packages/utils/package-lock.json
  packages/utils/package.json
  packages/webpack-scaffold/package-lock.json
Labels: PR: reviewed-approved

#467 chore(package): update jest-cli to version 23.0.1
  package-lock.json
  package.json
Labels: PR: small, PR: unreviewed

#470 tests(parser): fix recursive-tests signature
  packages/utils/__snapshots__/recursive-parser.test.js.snap
  packages/utils/recursive-parser.test.js
Labels: PR: reviewed-approved, PR: small

#464 fix(entry): fix a bug when `--display-entrypoints=false` does not hide entries
  bin/webpack.js
  test/binCases/entry/display-entrypoints/a.js
  test/binCases/entry/display-entrypoints/index.js
  test/binCases/entry/display-entrypoints/stdin.js
  test/binCases/entry/display-entrypoints/test.opts
  test/binCases/entry/display-entrypoints/webpack.config.js
Labels: PR: reviewed-approved, PR: small

#472 fix(binTestCases): refactor to make tests pass
  .eslintignore
  test/BinTestCases.test.js
  test/binCases/config-name/found-many/stdin.js
  test/binCases/config-name/found-one/stdin.js
  test/binCases/config-type/array/stdin.js
  test/binCases/configFile/plugins-precedence/stdin.js
  test/binCases/configFile/profile/stdin.js
  test/binCases/entry/cli-override/stdin.js
  test/binCases/entry/multi-file/stdin.js
  test/binCases/entry/named-entry/stdin.js
  test/binCases/entry/non-hyphenated-args/stdin.js
  test/binCases/env/complex/stdin.js
  test/binCases/env/string/stdin.js
  test/binCases/errors/issue-5576/stdin.js
  test/binCases/errors/parse/stdin.js
  test/binCases/mode/none/stdin.js
  test/binCases/output/output-argument/stdin.js
  test/binCases/stats/single-config/stdin.js
Labels: PR: unreviewed
