Repository webpack/webpack-cli, pull requests merged in 2018-06, with the labels that each got.

#473 tests(coverage): fix coverage
  .appveyor.yml
  .gitignore
  .travis.yml
  package.json
  packages/utils/npm-exists.test.js
  packages/utils/package.json
  packages/webpack-scaffold/package.json
  test/BinTestCases.test.js
Labels: Chill ❄️, PR: unreviewed, Tests

#475 chore(semantic): Semantic release plugins
  .travis.yml
  commitlint.config.js
  package-lock.json
  package.json
Labels: PR: unreviewed

#456 ast(parser): add
  packages/utils/__snapshots__/ast-utils.test.js.snap
  packages/utils/__snapshots__/recursive-parser.test.js.snap
  packages/utils/__testfixtures__/fixture-2.input.js
  packages/utils/ast-utils.js
  packages/utils/ast-utils.test.js
  packages/utils/recursive-parser.js
  packages/utils/recursive-parser.test.js
Labels: PR: reviewed-approved, PR: reviewed-changes-requested, Semver: minor ⚙️

#478 require validateSchema and optionsValidationError from webpack
  bin/convert-argv.js
Labels: PR: small, PR: unreviewed

#481 fix: Remove workspaces key, as yarn workspaces is not in use
  package.json
Labels: PR: reviewed-approved, PR: small

#490 cli(init): don't use uglify on prod config
  packages/generators/init-generator.js
  packages/generators/utils/module.js
Labels: PR: reviewed-approved, PR: small

#494 fix: use async / await for info command
  packages/info/index.js
Labels: PR: reviewed-approved, PR: small

#496 chore(deps): update major versions
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#502 cli(prompts): Add autocomplete support for config props
  package-lock.json
  packages/generate-loader/package-lock.json
  packages/generate-plugin/package-lock.json
  packages/generators/add-generator.js
  packages/generators/package-lock.json
  packages/generators/package.json
  packages/init/package-lock.json
  packages/migrate/package-lock.json
  packages/serve/package-lock.json
  packages/utils/package-lock.json
  packages/webpack-scaffold/index.js
Labels: PR: reviewed-approved

#508 tests: Fix mixed spaces/tabs in stdin.js
  test/binCases/watch/info-verbosity-verbose/stdin.js
Labels: PR: reviewed-approved, PR: small

#510 chore(greenkeeper): support for lockfiles
  .travis.yml
Labels: PR: reviewed-approved, PR: small

#513 misc: remove chore from pkg.json
  package.json
Labels: PR: small, PR: unreviewed

#512 chore: add changelog for v3
  CHANGELOG.md
Labels: PR: unreviewed

#516 chore(ci): remove semantic release
  .travis.yml
  git_deploy_key.enc
  package-lock.json
  package.json
Labels: PR: unreviewed

#525 chore: remove semantic-release
  package.json
Labels: PR: reviewed-approved, PR: small

#511 feat(typescript): setup base infra
  .gitignore
  package-lock.json
  package.json
  packages/generators/package-lock.json
  packages/migrate/package-lock.json
  packages/utils/package-lock.json
  tsconfig.json
  tslint.json
Labels: PR: reviewed-approved

#522 chore(info): add typescript support
  package.json
  packages/info/.gitignore
  packages/info/.npmignore
  packages/info/index.ts
  packages/info/package-lock.json
  packages/info/package.json
  packages/info/tsconfig.json
  tslint.json
Labels: PR: reviewed-approved

#529 chore(build): fix eslint pattern
  .eslintignore
  package-lock.json
  package.json
  packages/generate-loader/package-lock.json
  packages/generate-plugin/package-lock.json
  packages/generators/package-lock.json
  packages/info/index.js
  packages/init/package-lock.json
  packages/migrate/package-lock.json
  packages/utils/package-lock.json
  packages/webpack-scaffold/package-lock.json
  test/BinTestCases.test.js
  test/binCases/config-type/array/webpack.config.js
  test/binCases/config-type/function-promise/dist/entry.bundle.js
  test/binCases/config-type/function-promise/webpack.config.js
  test/binCases/config-type/invalid-array/webpack.config.js
  test/binCases/config-type/promise/dist/entry.bundle.js
  test/binCases/configFile/plugins-precedence/index.js
  test/binCases/configFile/plugins-precedence/webpack.config.js
  test/binCases/configFile/profile/index.js
  test/binCases/entry/display-entrypoints/stdin.js
  test/binCases/errors/info-verbosity/webpack.config.js
  test/binCases/errors/parse/index.js
  test/binCases/module/module-bind/index.js
Labels: PR: reviewed-approved

#531 chore(template): tiny fix for bug template
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: PR: reviewed-approved, PR: small

#497 docs(pkg): readme info
  packages/info/README.md
Labels: Documentation, PR: CI-not-ok, PR: reviewed-approved

#534 chore(ci): fix build
  package-lock.json
  package.json
  packages/generate-loader/package-lock.json
  packages/generate-plugin/package-lock.json
  packages/generators/package-lock.json
  packages/info/package-lock.json
  packages/info/package.json
  packages/init/package-lock.json
  packages/migrate/package-lock.json
  packages/utils/package-lock.json
  packages/webpack-scaffold/package-lock.json
  packages/webpack-scaffold/package.json
  tslint.json
Labels: PR: CI-ok, PR: reviewed-approved

#461 ast(parser): command remove
  bin/cli.js
  package-lock.json
  packages/generators/remove-generator.js
  packages/info/index.ts
  packages/utils/__snapshots__/recursive-parser.test.js.snap
  packages/utils/__testfixtures__/fixture-3.input.js
  packages/utils/ast-utils.js
  packages/utils/modify-config-helper.js
  packages/utils/recursive-parser.js
  packages/utils/recursive-parser.test.js
Labels: PR: CI-ok, PR: reviewed-approved, Semver: minor ⚙️
