Repository webpack/webpack-cli, pull requests merged in 2018-03, with the labels that each got.

#297 misc(dep): add webpack 4 as peer dependency
  package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#285 tests(no-options): add no options test
  test/binCases/config-name/found-many/test.opts
  test/binCases/config-type/function-promise/test.opts
  test/binCases/config-type/function/test.opts
  test/binCases/config-type/invalid-array/test.opts
  test/binCases/config-type/invalid-type/test.opts
  test/binCases/config-type/object/test.opts
  test/binCases/config-type/promise/test.opts
  test/binCases/no-options/development/stdin.js
  test/binCases/no-options/development/tests.opts
  test/binCases/no-options/development/webpack.config.js
  test/binCases/no-options/none/stdin.js
  test/binCases/no-options/none/test.opts
  test/binCases/no-options/production/stdin.js
  test/binCases/no-options/production/tests.opts
  test/binCases/no-options/production/webpack.config.js
Labels: PR: CI-ok, PR: reviewed-approved

#298 [feature] strict Promise configuration validation
  schemas/webpackConfigurationSchema.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#294 fix: yeoman-generator fork issue
  bin/webpack.js
  lib/commands/serve.js
  lib/generators/add-generator.js
  lib/generators/init-generator.js
  lib/generators/remove-generator.js
  lib/generators/update-generator.js
  lib/generators/webpack-generator.js
  lib/init/index.js
  package.json
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved

#300 Commitlint
  .cz-config.js
  build/changelog-generator/index.js
Labels: PR: CI-ok, PR: reviewed-approved

#302 chore(packager): remove yarn
  .appveyor.yml
  .codecov.yml
  .flowconfig
  .travis.yml
  bin/webpack.js
  lib/migrate/__snapshots__/index.test.js.snap
  package-lock.json
  package.json
  yarn.lock
Labels: PR: CI-ok, PR: unreviewed

#303 misc(readme): add npm badge
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#305 cli(taptable): Remove Tapable#apply calls
  bin/process-options.js
  bin/webpack.js
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#308 fix(migrate): move options to use
  lib/migrate/loaders/__snapshots__/loaders.test.js.snap
  lib/migrate/loaders/__testfixtures__/loaders-9.input.js
  lib/migrate/loaders/loaders.js
Labels: PR: CI-ok, PR: reviewed-approved

#317 fix: adding 'fix' to whitelist
  .cz-config.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#309 Clean up dependencies
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#265 misc(generator): Allow local paths to generators
  SCAFFOLDING.md
  lib/utils/is-local-path.js
  lib/utils/is-local-path.spec.js
  lib/utils/npm-packages-exists.js
  lib/utils/npm-packages-exists.spec.js
  lib/utils/package-manager.js
  lib/utils/package-manager.spec.js
  lib/utils/resolve-packages.js
Labels: PR: CI-ok, PR: reviewed-changes-requested

#323 cli(init): Refactor Yeoman
  .appveyor.yml
  lib/generators/init-generator.js
  lib/init/index.js
  lib/init/index.test.js
  lib/init/transformations/index.js
  lib/utils/modify-config-helper.js
  lib/utils/resolve-packages.js
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: review-outdated

#319 Upgrade jscodeshift to 0.5.0 and all other deps
  lib/init/transformations/top-scope/__snapshots__/top-scope.test.js.snap
  package-lock.json
  package.json
Labels: PR: CI-not-ok, PR: review-outdated

#324 chore(test): updated tests file names
  lib/utils/is-local-path.test.js
  lib/utils/npm-exists.test.js
  lib/utils/npm-packages-exists.test.js
  lib/utils/package-manager.test.js
  lib/utils/resolve-packages.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: reviewed-changes-requested

#325 chore(ES6): changed 'var' into 'const' where convenient
  lib/generate-loader/index.js
  lib/generate-plugin/index.js
  lib/generators/loader-generator.js
  lib/generators/loader-generator.test.js
  lib/generators/plugin-generator.js
  lib/generators/webpack-generator.js
  lib/init/transformations/top-scope/__snapshots__/top-scope.test.js.snap
  lib/init/transformations/top-scope/top-scope.test.js
  lib/migrate/__testfixtures__/failing.js
  lib/utils/ast-utils.js
  lib/utils/ast-utils.test.js
  lib/utils/copy-utils.js
  lib/utils/hashtable.js
Labels: PR: CI-not-ok, PR: review-outdated

#328 Update README to remove inconsistent CLI messaging
  README.md
Labels: PR: CI-ok, PR: review-outdated, PR: small

#333 misc(init-generator): cleanup
  lib/generators/init-generator.js
Labels: PR: CI-ok, PR: reviewed-approved

#332 Fix global path require & add vim swap files to gitignore
  .gitignore
  lib/utils/package-manager.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#336 chore(scaffolding): update docs
  SCAFFOLDING.md
Labels: PR: CI-ok, PR: reviewed-approved

#339 misc(cz): fix type description
  .cz-config.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#342 fix: removes debug in migrate
  lib/migrate/__snapshots__/index.test.js.snap
  lib/migrate/loaderOptionsPlugin/__snapshots__/loaderOptionsPlugin.test.js.snap
  lib/migrate/loaderOptionsPlugin/loaderOptionsPlugin.js
Labels: PR: CI-ok, PR: reviewed-approved

#340 Support --build-delimiter for opt-in output delimiter
  bin/process-options.js
  bin/webpack.js
  test/binCases/stats/build-delimiter/index.js
  test/binCases/stats/build-delimiter/stdin.js
  test/binCases/stats/build-delimiter/test.opts
Labels: PR: CI-ok, PR: reviewed-approved

#344 cli(init): fix init regexp
  lib/generators/init-generator.js
  lib/generators/utils/module.js
Labels: PR: CI-ok, PR: review-outdated, PR: small

#347 cli(init): fix webpack-cli dep
  lib/generators/init-generator.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#349 chore(pkg): explicitly include files for release
  .npmignore
  package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#362 chore(upgrade): webpack 4.2 and other dependencies
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#366 chore(coverage): added reporters inside package.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#365 feat: add envinfo as `webpack-cli info` command
  .github/ISSUE_TEMPLATE.md
  bin/webpack.js
  lib/commands/info.js
  lib/index.js
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#368 feat: use npm ci for tests (#367)
  .appveyor.yml
  .travis.yml
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
