Repository webpack/webpack-cli, pull requests merged in 2018-09, with the labels that each got.

#583 fix(package): Bump lerna version
  package-lock.json
  package.json
  packages/add/package-lock.json
  packages/generate-loader/package-lock.json
  packages/generate-plugin/package-lock.json
  packages/generators/package-lock.json
  packages/info/package-lock.json
  packages/init/package-lock.json
  packages/make/package-lock.json
  packages/migrate/package-lock.json
  packages/remove/package-lock.json
  packages/serve/package-lock.json
  packages/update/package-lock.json
  packages/utils/package-lock.json
  packages/webpack-scaffold/package-lock.json
Labels: PR: CI-ok, PR: reviewed-approved

#595 Remove appveyor
  .appveyor.yml
  .npmignore
  README.md
  package.json
Labels: PR: CI-not-ok, PR: reviewed-approved

#597 docs: fix the setup workflow #591
  CONTRIBUTING.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: reviewed-changes-requested, PR: small

#599 chore(deps): resync package-lock, upgrade major version
  lerna.json
  package-lock.json
  package.json
  packages/add/package-lock.json
  packages/add/package.json
  packages/generate-loader/package-lock.json
  packages/generate-loader/package.json
  packages/generate-plugin/package-lock.json
  packages/generate-plugin/package.json
  packages/generators/package-lock.json
  packages/generators/package.json
  packages/info/package-lock.json
  packages/init/package-lock.json
  packages/init/package.json
  packages/migrate/package-lock.json
  packages/migrate/package.json
  packages/serve/package-lock.json
  packages/serve/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
  packages/webpack-scaffold/package-lock.json
  packages/webpack-scaffold/package.json
Labels: PR: CI-ok, PR: reviewed-approved

#601 Add a status badge for the azure pipelines CI build
  README.md
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#578 Types for packages
  packages/add/tsconfig.json
  packages/generate-loader/tsconfig.json
  packages/generate-plugin/tsconfig.json
  packages/generators/tsconfig.json
  packages/info/tsconfig.json
  packages/init/tsconfig.json
  packages/make/package.json
  packages/make/tsconfig.json
  packages/migrate/package.json
  packages/migrate/tsconfig.json
  packages/remove/package.json
  packages/remove/tsconfig.json
  packages/serve/package.json
  packages/serve/tsconfig.json
  packages/update/package.json
  packages/update/tsconfig.json
  packages/utils/package.json
  packages/utils/tsconfig.json
  packages/webpack-scaffold/package.json
  packages/webpack-scaffold/tsconfig.json
  tsconfig.base.json
  tsconfig.json
  tsconfig.packages.json
Labels: PR: CI-not-ok, PR: reviewed-approved

#592 Feature/fix commitlint
  .cz-config.js
  commitlint.config.js
  package-lock.json
  package.json
Labels: PR: CI-not-ok, PR: unreviewed

#604 fix tslint warnings
  packages/generators/add-generator.ts
  packages/generators/remove-generator.ts
  packages/make/index.ts
  packages/migrate/index.ts
  packages/migrate/removeDeprecatedPlugins/removeDeprecatedPlugins.ts
  packages/serve/index.ts
  packages/utils/recursive-parser.ts
  packages/utils/resolve-packages.ts
  tslint.json
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#584 Feature/package test ts
  package-lock.json
  package.json
  packages/add/package-lock.json
  packages/generate-loader/package-lock.json
  packages/generate-plugin/package-lock.json
  packages/generators/package-lock.json
  packages/info/__tests__/index.test.ts
  packages/info/index.ts
  packages/info/package-lock.json
  packages/init/package-lock.json
  packages/migrate/package-lock.json
  packages/serve/package-lock.json
  packages/utils/package-lock.json
  tsconfig.base.json
  tsconfig.json
Labels: PR: CI-ok, PR: reviewed-approved

#603 chore(fix): fix clean all script
  package.json
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#605 fix: resolve references in schema
  bin/config-yargs.js
Labels: PR: CI-not-ok, PR: reviewed-approved

#611 chore(deps): upgrade husky
  package-lock.json
  package.json
  packages/add/package-lock.json
  packages/generate-loader/package-lock.json
  packages/generate-plugin/package-lock.json
  packages/generators/package-lock.json
  packages/info/package-lock.json
  packages/init/package-lock.json
  packages/make/package-lock.json
  packages/migrate/package-lock.json
  packages/remove/package-lock.json
  packages/serve/package-lock.json
  packages/update/package-lock.json
  packages/utils/package-lock.json
  packages/webpack-scaffold/package-lock.json
Labels: PR: CI-ok, PR: reviewed-approved

#612 chore(scripts): add commit script, cz-customizable
  .cz-config.js
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#600 chore(docs): update readme
  README.md
Labels: PR: CI-not-ok, PR: reviewed-approved

#614 [docs] Update README.md
  README.md
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#615 docs(init): update init documentation
  packages/init/README.md
Labels: PR: CI-ok, PR: reviewed-approved

#616 docs(readme): update links
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#618 fix(tapable): fix hook options
  bin/cli.js
  bin/config-yargs.js
  packages/utils/npm-packages-exists.test.js
  packages/utils/recursive-parser.test.js
  test/binCases/watch/info-verbosity-verbose/stdin.js
Labels: PR: CI-ok, PR: reviewed-approved

#562 Output lib array opt
  CONTRIBUTING.md
  bin/config-yargs.js
  bin/convert-argv.js
  test/BinTestCases.test.js
  test/binCases/output/output-library-many/index.js
  test/binCases/output/output-library-many/stdin.js
  test/binCases/output/output-library-many/test.opts
  test/binCases/output/output-library-single/index.js
  test/binCases/output/output-library-single/stdin.js
  test/binCases/output/output-library-single/test.opts
Labels: PR: CI-ok, PR: reviewed-approved, PR: reviewed-changes-requested
