Repository webpack/webpack-cli, pull requests merged in 2018-10, with the labels that each got.

#628 chore(travis): remove node 7
  .travis.yml
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#631 fix critical error
  packages/init/README.md
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#658 chore(dependencies): pin to webpack 4.x.x
  package-lock.json
  package.json
  packages/generators/package-lock.json
  packages/generators/package.json
  packages/migrate/package-lock.json
  packages/migrate/package.json
  packages/utils/package-lock.json
Labels: PR: review-outdated

#665 chore(dependencies): pin versions to support node 6
  package.json
  packages/utils/package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#622 Refactor npmPackagesExists() function
  packages/utils/npm-packages-exists.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#666 chore(greenkeeper): remove greenkeeper scripts, configs
  .travis.yml
  README.md
  greenkeeper.json
Labels: PR: reviewed-approved

#663 cli(color): fix color option
  bin/cli.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
