Repository webpack/webpack-cli, pull requests merged in 2018-12, with the labels that each got.

#527 [WIP] Refactor bin folder
  .cz-config.js
  bin/cli.js
  bin/config-yargs.js
  bin/convert-argv.js
  bin/errorHelpers.js
  bin/optionsSchema.json
  bin/prepareOptions.js
  bin/prompt-command.js
  bin/webpackConfigurationSchema.json
  cli.js
  dist/a.js
  dist/b.js
  dist/main.js
  lib/bootstrap.js
  lib/commands/external.js
  lib/commands/internal.js
  lib/groups/advanced.js
  lib/groups/basic.js
  lib/groups/config.js
  lib/groups/help.js
  lib/groups/output.js
  lib/groups/stats.js
  lib/utils/cli-flags.js
  lib/utils/compiler.js
  lib/utils/dev-config.js
  lib/utils/group-helper.js
  lib/utils/prod-config.js
  lib/webpack-cli.js
  package-lock.json
  package.json
  packages/add/.gitignore
  packages/generate-loader/package-lock.json
  packages/generate-loader/types/Yeoman.js
  packages/generate-plugin/package-lock.json
  packages/generate-plugin/types/Yeoman.js
  packages/generators/add-generator.ts
  packages/generators/init-generator.ts
  packages/generators/package-lock.json
  packages/generators/types/index.js
  packages/init/index.ts
  packages/init/package-lock.json
  packages/init/types/Transform.js
  packages/init/types/index.js
  packages/migrate/.gitignore
  packages/migrate/commonsChunkPlugin/commonsChunkPlugin.js
  packages/migrate/package-lock.json
  packages/migrate/types/NodePath.js
  packages/migrate/types/index.js
  packages/serve/package-lock.json
  packages/update/.gitignore
  packages/utils/modify-config-helper.js
  packages/utils/npm-packages-exists.test.js
  packages/utils/package-lock.json
  packages/utils/types/NodePath.js
  packages/utils/types/Yeoman.js
  packages/utils/types/index.js
  packages/webpack-scaffold/package-lock.json
  src/index.js
  test/testUtils.js
  tsconfig.json
Labels: Chill ❄️, PR: CI-not-ok, PR: review-outdated

#714 docs: add Index and minor changes
  packages/webpack-scaffold/README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#671 Webpack GUI: Preact setup
  package-lock.json
  package.json
  packages/ui-gui/.gitignore
  packages/ui-gui/README.md
  packages/ui-gui/dist/bundle.css
  packages/ui-gui/dist/main.js
  packages/ui-gui/index.html
  packages/ui-gui/package-lock.json
  packages/ui-gui/package.json
  packages/ui-gui/src/assets/favicon.ico
  packages/ui-gui/src/assets/icons/android-chrome-192x192.png
  packages/ui-gui/src/assets/icons/android-chrome-512x512.png
  packages/ui-gui/src/assets/icons/apple-touch-icon.png
  packages/ui-gui/src/assets/icons/favicon-16x16.png
  packages/ui-gui/src/assets/icons/favicon-32x32.png
  packages/ui-gui/src/assets/icons/mstile-150x150.png
  packages/ui-gui/src/components/app.js
  packages/ui-gui/src/components/header/index.js
  packages/ui-gui/src/components/header/style.css
  packages/ui-gui/src/index.js
  packages/ui-gui/src/manifest.json
  packages/ui-gui/src/routes/404/index.js
  packages/ui-gui/src/routes/404/style.css
  packages/ui-gui/src/routes/home/index.js
  packages/ui-gui/src/routes/home/style.css
  packages/ui-gui/src/routes/profile/index.js
  packages/ui-gui/src/routes/profile/style.css
  packages/ui-gui/src/style/index.css
  packages/ui-gui/src/styles/app.scss
  packages/ui-gui/webpack.prod.js
  packages/ui-server/package.json
  packages/ui/bin/www.js
  packages/ui/package-lock.json
  packages/ui/package.json
Labels: PR: CI-not-ok, PR: reviewed-approved, UI 🕶

#719 docs: add packages README
  packages/README.md
Labels: PR: CI-ok, PR: reviewed-approved

#718 misc: reduce hop for creating an issue
  packages/utils/modify-config-helper.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
