Repository webpack/webpack-cli, pull requests merged in 2018-08, with the labels that each got.

#559 allow array value for --ouput-library
  bin/config-yargs.js
  bin/convert-argv.js
  test/binCases/output/output-library-many/index.js
  test/binCases/output/output-library-many/stdin.js
  test/binCases/output/output-library-many/test.opts
  test/binCases/output/output-library-single/index.js
  test/binCases/output/output-library-single/stdin.js
  test/binCases/output/output-library-single/test.opts
Labels: PR: CI-not-ok, PR: reviewed-approved

#561 Revert "allow array value for --ouput-library"
  bin/config-yargs.js
  bin/convert-argv.js
  test/binCases/output/output-library-many/index.js
  test/binCases/output/output-library-many/stdin.js
  test/binCases/output/output-library-many/test.opts
  test/binCases/output/output-library-single/index.js
  test/binCases/output/output-library-single/stdin.js
  test/binCases/output/output-library-single/test.opts
Labels: PR: unreviewed

#558 feat(migrate): CommonChunksPlugin to SplitChunksPlugin
  packages/migrate/commonsChunkPlugin/__snapshots__/commonsChunkPlugin.test.js.snap
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-0.input.js
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-1.input.js
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-2.input.js
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-3.input.js
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-4.input.js
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-5.input.js
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-6a.input.js
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-6b.input.js
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-6c.input.js
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-6d.input.js
  packages/migrate/commonsChunkPlugin/__testfixtures__/commonsChunkPlugin-7.input.js
  packages/migrate/commonsChunkPlugin/commonsChunkPlugin.test.js
  packages/migrate/commonsChunkPlugin/commonsChunkPlugin.ts
  packages/migrate/migrate.ts
  packages/migrate/types/NodePath.ts
Labels: PR: CI-ok, PR: reviewed-approved
