Repository webpack/webpack-cli, pull requests merged in 2018-07, with the labels that each got.

#521 chore(add-cmd): add typescript support
  package-lock.json
  packages/add/.gitignore
  packages/add/.npmignore
  packages/add/index.js
  packages/add/index.ts
  packages/add/package-lock.json
  packages/add/package.json
  packages/add/tsconfig.json
  packages/generators/package-lock.json
  packages/utils/package-lock.json
Labels: Chill ❄️, PR: CI-ok, PR: reviewed-approved

#535 chore(build): fix ci
  .eslintignore
  package-lock.json
  packages/generate-loader/package-lock.json
  packages/generate-plugin/package-lock.json
  packages/generators/package-lock.json
  packages/migrate/package-lock.json
  packages/utils/package-lock.json
  test/binCases/config-name/found-many/stdin.js
  test/binCases/config-name/found-one/stdin.js
  test/binCases/config-type/array/stdin.js
  test/binCases/configFile/plugins-precedence/stdin.js
  test/binCases/configFile/profile/stdin.js
  test/binCases/entry/cli-override/stdin.js
  test/binCases/entry/multi-file/stdin.js
  test/binCases/entry/named-entry/stdin.js
  test/binCases/entry/non-hyphenated-args/stdin.js
  test/binCases/env/complex/stdin.js
  test/binCases/errors/issue-5576/stdin.js
  test/binCases/errors/parse/index.js
  test/binCases/errors/parse/stdin.js
  test/binCases/mode/none/stdin.js
  test/binCases/output/output-argument/stdin.js
  test/binCases/stats/single-config/stdin.js
Labels: PR: CI-ok, PR: reviewed-approved

#537 feat(remove): add typescript support
  packages/remove/.gitignore
  packages/remove/.npmignore
  packages/remove/index.ts
  packages/remove/package-lock.json
  packages/remove/package.json
  packages/remove/tsconfig.json
Labels: PR: CI-ok, PR: reviewed-approved

#538 feat(update): add typescript support
  packages/update/.gitignore
  packages/update/.npmignore
  packages/update/index.ts
  packages/update/package-lock.json
  packages/update/package.json
  packages/update/tsconfig.json
Labels: PR: CI-ok, PR: reviewed-approved

#539 feat(make): add typescript support
  packages/make/.gitignore
  packages/make/.npmignore
  packages/make/index.ts
  packages/make/package-lock.json
  packages/make/package.json
  packages/make/tsconfig.json
Labels: PR: CI-ok, PR: reviewed-approved

#518 feat(init): add typescript support
  .gitignore
  package-lock.json
  packages/init/.gitignore
  packages/init/.npmignore
  packages/init/index.ts
  packages/init/init.js
  packages/init/init.ts
  packages/init/package-lock.json
  packages/init/package.json
  packages/init/tsconfig.json
  packages/init/types/Transform.ts
  packages/init/types/index.ts
Labels: PR: CI-ok, PR: reviewed-approved

#543 Updated working link for webpack addon.
  SCAFFOLDING.md
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#498 [WIP] docs(pkg): readme file for add package
  packages/add/README.md
Labels: Documentation, PR: reviewed-approved, PR: reviewed-changes-requested

#528 feat(utils): add typescript support
  package-lock.json
  package.json
  packages/generators/add-generator.ts
  packages/generators/remove-generator.js
  packages/generators/remove-generator.ts
  packages/init/index.ts
  packages/init/init.ts
  packages/migrate/bannerPlugin/bannerPlugin.test.js
  packages/migrate/extractTextPlugin/extractTextPlugin.test.js
  packages/migrate/index.ts
  packages/migrate/loaderOptionsPlugin/loaderOptionsPlugin.test.js
  packages/migrate/loaderOptionsPlugin/loaderOptionsPlugin.ts
  packages/migrate/loaders/loaders.test.js
  packages/migrate/loaders/loaders.ts
  packages/migrate/moduleConcatenationPlugin/moduleConcatenationPlugin.test.js
  packages/migrate/namedModulesPlugin/namedModulesPlugin.test.js
  packages/migrate/noEmitOnErrorsPlugin/noEmitOnErrorsPlugin.test.js
  packages/migrate/outputPath/outputPath.test.js
  packages/migrate/outputPath/outputPath.ts
  packages/migrate/removeDeprecatedPlugins/removeDeprecatedPlugins.test.js
  packages/migrate/removeJsonLoader/removeJsonLoader.test.js
  packages/migrate/resolve/resolve.test.js
  packages/migrate/resolve/resolve.ts
  packages/migrate/uglifyJsPlugin/uglifyJsPlugin.test.js
  packages/utils/.gitignore
  packages/utils/.npmignore
  packages/utils/ast-utils.ts
  packages/utils/copy-utils.ts
  packages/utils/defineTest.ts
  packages/utils/index.js
  packages/utils/index.ts
  packages/utils/is-local-path.test.js
  packages/utils/is-local-path.ts
  packages/utils/modify-config-helper.js
  packages/utils/modify-config-helper.ts
  packages/utils/npm-exists.js
  packages/utils/npm-exists.test.js
  packages/utils/npm-exists.ts
  packages/utils/npm-packages-exists.test.js
  packages/utils/npm-packages-exists.ts
  packages/utils/package-lock.json
  packages/utils/package-manager.ts
  packages/utils/package.json
  packages/utils/prop-types.ts
  packages/utils/recursive-parser.js
  packages/utils/recursive-parser.test.js
  packages/utils/recursive-parser.ts
  packages/utils/resolve-packages.ts
  packages/utils/run-prettier.ts
  packages/utils/scaffold.js
  packages/utils/scaffold.ts
  packages/utils/tsconfig.json
  packages/utils/types/NodePath.js
  packages/utils/types/NodePath.ts
  packages/utils/types/Yeoman.js
  packages/utils/types/Yeoman.ts
  packages/utils/types/index.js
  packages/utils/types/index.ts
  packages/utils/validate-identifier.js
  packages/utils/validate-identifier.ts
Labels: PR: CI-ok, PR: review-outdated

#545 docs(packages): add missing READMES to packages
  packages/add/README.md
  packages/generate-loader/README.md
  packages/generate-plugin/README.md
  packages/generators/README.md
  packages/info/README.md
  packages/init/README.md
  packages/make/README.md
  packages/migrate/README.md
  packages/remove/README.md
  packages/serve/README.md
  packages/update/README.md
  packages/utils/README.md
Labels: PR: CI-not-ok, PR: unreviewed

#552 tests(fix): bin test outputs
  test/binCases/configFile/plugins-precedence/stdin.js
  test/binCases/entry/multi-file/stdin.js
  test/binCases/entry/named-entry/stdin.js
Labels: PR: CI-ok, PR: reviewed-approved

#547 docs: init documentaion
  INIT.md
Labels: PR: CI-ok, PR: reviewed-approved

#553 fix(prettier): add parser, filePath
  packages/utils/run-prettier.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#554 docs: migrate documentaion
  MIGRATE.md
Labels: PR: CI-ok, PR: reviewed-approved

#555 chore(deps): removing inquirer as default package
  package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small, Semver: minor ⚙️
