Repository webpack/webpack-cli, pull requests merged in 2018-04, with the labels that each got.

#371 cli(refactor): improve folder structure
  bin/process-options.js
  bin/webpack.js
  lib/commands/generate-loader.js
  lib/commands/generate-plugin.js
  lib/commands/info.js
  lib/commands/init.js
  lib/commands/migrate.js
  lib/generate-loader/examples/simple/src/index.js.tpl
  lib/generate-loader/examples/simple/src/lazy-module.js.tpl
  lib/generate-loader/examples/simple/src/static-esm-module.js.tpl
  lib/generate-loader/examples/simple/webpack.config.js.tpl
  lib/generate-loader/src/_index.js.tpl
  lib/generate-loader/src/cjs.js.tpl
  lib/generate-loader/test/fixtures/simple-file.js.tpl
  lib/generate-loader/test/functional.test.js.tpl
  lib/generate-loader/test/test-utils.js.tpl
  lib/generate-loader/test/unit.test.js.tpl
  lib/generate-plugin/examples/simple/_webpack.config.js.tpl
  lib/generate-plugin/examples/simple/src/index.js.tpl
  lib/generate-plugin/examples/simple/src/lazy-module.js.tpl
  lib/generate-plugin/examples/simple/src/static-esm-module.js.tpl
  lib/generate-plugin/src/_index.js.tpl
  lib/generate-plugin/src/cjs.js.tpl
  lib/generate-plugin/test/fixtures/simple-file.js.tpl
  lib/generate-plugin/test/functional.test.js.tpl
  lib/generate-plugin/test/test-utils.js.tpl
  lib/generators/init-generator.js
  lib/generators/loader-generator.js
  lib/generators/loader-generator.test.js
  lib/generators/plugin-generator.js
  lib/generators/webpack-generator.js
  lib/index.js
  lib/init/transformations/top-scope/top-scope.test.js
  lib/migrate/loaderOptionsPlugin/loaderOptionsPlugin.js
  package-lock.json
  package.json
Labels: CLI, PR: CI-ok, PR: reviewed-approved, enhancement

#379 Add break as commit type and listed the type of commit in the documentation
  .cz-config.js
  CONTRIBUTING.md
Labels: PR: CI-ok, PR: unreviewed

#364 cli(init): mode support to config
  lib/generators/init-generator.js
  lib/init/transformations/mode/__snapshots__/mode.test.js.snap
  lib/init/transformations/mode/mode.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small, Semver: patch 🔧

#381 cli(bugfix): Allow mode "none" in CLI
  bin/config-yargs.js
  test/binCases/mode/none/index.js
  test/binCases/mode/none/stdin.js
  test/binCases/mode/none/test.opts
Labels: PR: CI-ok, PR: unreviewed, Semver: patch 🔧

#363 cli(init): use extractMiniCSSPlugin
  lib/generators/init-generator.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small, Semver: patch 🔧

#392 Retrieve information for CLI option from webpack schema options file
  bin/config-yargs.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small, Semver: minor ⚙️

#348 cli(add): write configuration to yeoman file
  lib/generators/add-generator.js
Labels: Chill ❄️, PR: CI-ok, PR: reviewed-approved, Semver: patch 🔧

#403 fix: output bundle file name for single entry
  lib/generators/init-generator.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#402 Update versions on message prompted to user during migration
  lib/commands/migrate.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small, Semver: patch 🔧

#399 Add NoEmitOnErrorsPlugin transformation
  lib/migrate/index.js
  lib/migrate/moduleConcatenationPlugin/__snapshots__/moduleConcatenationPlugin.test.js.snap
  lib/migrate/moduleConcatenationPlugin/__testfixtures__/.editorconfig
  lib/migrate/moduleConcatenationPlugin/__testfixtures__/moduleConcatenationPlugin-0.input.js
  lib/migrate/moduleConcatenationPlugin/__testfixtures__/moduleConcatenationPlugin-1.input.js
  lib/migrate/moduleConcatenationPlugin/__testfixtures__/moduleConcatenationPlugin-2.input.js
  lib/migrate/moduleConcatenationPlugin/moduleConcatenationPlugin.js
  lib/migrate/moduleConcatenationPlugin/moduleConcatenationPlugin.test.js
  lib/migrate/namedModulesPlugin/__snapshots__/namedModulesPlugin.test.js.snap
  lib/migrate/namedModulesPlugin/__testfixtures__/.editorconfig
  lib/migrate/namedModulesPlugin/__testfixtures__/namedModulesPlugin-0.input.js
  lib/migrate/namedModulesPlugin/__testfixtures__/namedModulesPlugin-1.input.js
  lib/migrate/namedModulesPlugin/__testfixtures__/namedModulesPlugin-2.input.js
  lib/migrate/namedModulesPlugin/namedModulesPlugin.js
  lib/migrate/namedModulesPlugin/namedModulesPlugin.test.js
  lib/migrate/noEmitOnErrorsPlugin/__snapshots__/noEmitOnErrorsPlugin.test.js.snap
  lib/migrate/noEmitOnErrorsPlugin/__testfixtures__/.editorconfig
  lib/migrate/noEmitOnErrorsPlugin/__testfixtures__/noEmitOnErrorsPlugin-0.input.js
  lib/migrate/noEmitOnErrorsPlugin/__testfixtures__/noEmitOnErrorsPlugin-1.input.js
  lib/migrate/noEmitOnErrorsPlugin/__testfixtures__/noEmitOnErrorsPlugin-2.input.js
  lib/migrate/noEmitOnErrorsPlugin/noEmitOnErrorsPlugin.js
  lib/migrate/noEmitOnErrorsPlugin/noEmitOnErrorsPlugin.test.js
  lib/utils/ast-utils.js
  package-lock.json
  package.json
  test/binCases/no-options/none/stdin.js
Labels: PR: CI-ok, PR: reviewed-approved, Semver: major 💣

#360 fix: checks validity of an identifier
  lib/utils/ast-utils.js
  lib/utils/validate-identifier.js
  lib/utils/validate-identifier.test.js
Labels: PR: CI-ok, PR: reviewed-approved, Semver: patch 🔧

#337 cli(entry): quotes sanitization
  lib/commands/init.js
  lib/generators/utils/entry.js
  lib/init/index.js
  lib/init/transformations/entry/__snapshots__/entry.test.js.snap
  lib/init/transformations/entry/entry.js
  lib/init/transformations/entry/entry.test.js
  lib/utils/prop-types.js
Labels: PR: CI-ok, PR: reviewed-approved

#409 fix(init): support non-string options for single entry
  lib/generators/utils/entry.js
Labels: PR: CI-ok, PR: reviewed-approved

#390 Update extractTextPlugin transformation
  lib/migrate/extractTextPlugin/__snapshots__/extractTextPlugin.test.js.snap
  lib/migrate/extractTextPlugin/__testfixtures__/extractTextPlugin-0.input.js
  lib/migrate/extractTextPlugin/__testfixtures__/extractTextPlugin-1.input.js
  lib/migrate/extractTextPlugin/__testfixtures__/extractTextPlugin-2.input.js
  lib/migrate/extractTextPlugin/__testfixtures__/extractTextPlugin.input.js
  lib/migrate/extractTextPlugin/extractTextPlugin.js
  lib/migrate/extractTextPlugin/extractTextPlugin.test.js
  lib/utils/ast-utils.js
  package.json
Labels: PR: CI-ok, PR: review-outdated, Semver: minor ⚙️

#405 Remove v1 -> v2-specific transformations
  lib/migrate/__snapshots__/index.test.js.snap
  lib/migrate/index.js
  lib/migrate/index.test.js
  lib/migrate/loaderOptionsPlugin/__snapshots__/loaderOptionsPlugin.test.js.snap
  lib/migrate/loaderOptionsPlugin/__testfixtures__/.editorconfig
  lib/migrate/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-0.input.js
  lib/migrate/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-1.input.js
  lib/migrate/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-2.input.js
  lib/migrate/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-3.input.js
  lib/migrate/loaderOptionsPlugin/loaderOptionsPlugin.js
  lib/migrate/loaderOptionsPlugin/loaderOptionsPlugin.test.js
  lib/migrate/loaders/__snapshots__/loaders.test.js.snap
  lib/migrate/loaders/__testfixtures__/.editorconfig
  lib/migrate/loaders/__testfixtures__/loaders-0.input.js
  lib/migrate/loaders/__testfixtures__/loaders-1.input.js
  lib/migrate/loaders/__testfixtures__/loaders-2.input.js
  lib/migrate/loaders/__testfixtures__/loaders-3.input.js
  lib/migrate/loaders/__testfixtures__/loaders-4.input.js
  lib/migrate/loaders/__testfixtures__/loaders-5.input.js
  lib/migrate/loaders/__testfixtures__/loaders-6.input.js
  lib/migrate/loaders/__testfixtures__/loaders-7.input.js
  lib/migrate/loaders/__testfixtures__/loaders-8.input.js
  lib/migrate/loaders/__testfixtures__/loaders-9.input.js
  lib/migrate/loaders/loaders.js
  lib/migrate/loaders/loaders.test.js
  lib/migrate/resolve/__snapshots__/resolve.test.js.snap
  lib/migrate/resolve/__testfixtures__/.editorconfig
  lib/migrate/resolve/__testfixtures__/resolve.input.js
  lib/migrate/resolve/resolve.js
  lib/migrate/resolve/resolve.test.js
Labels: PR: CI-ok, PR: review-outdated, Semver: major 💣

#410 fix: remove reference to specific version during migration
  lib/commands/migrate.js
Labels: PR: CI-ok, PR: review-outdated, PR: small

#412 chore(docs): updated old references to the extract text plugin
  INIT.md
  lib/generators/utils/tooltip.js
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#416 Update UglifyJS transformation
  lib/migrate/__snapshots__/index.test.js.snap
  lib/migrate/uglifyJsPlugin/__snapshots__/uglifyJsPlugin.test.js.snap
  lib/migrate/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-0.input.js
  lib/migrate/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-1.input.js
  lib/migrate/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-2.input.js
  lib/migrate/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-3.input.js
  lib/migrate/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-4.input.js
  lib/migrate/uglifyJsPlugin/uglifyJsPlugin.js
  lib/migrate/uglifyJsPlugin/uglifyJsPlugin.test.js
  lib/utils/__snapshots__/ast-utils.test.js.snap
  lib/utils/ast-utils.js
  lib/utils/ast-utils.test.js
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#415 chore(publishing): add semantic-release
  .travis.yml
  package-lock.json
  package.json
Labels: PR: CI-not-ok, PR: review-outdated

#377 cli(node): Add node flags to CLI
  bin/process-node-flags.js
  bin/webpack.js
  test/binCases/node-flags/advanced/index.js
  test/binCases/node-flags/advanced/stdin.js
  test/binCases/node-flags/advanced/test.opts
  test/binCases/node-flags/only-node-flags/index.js
  test/binCases/node-flags/only-node-flags/stdin.js
  test/binCases/node-flags/only-node-flags/test.opts
  test/binCases/node-flags/output/index.js
  test/binCases/node-flags/output/stdin.js
  test/binCases/node-flags/output/test.opts
Labels: PR: CI-ok, PR: review-outdated, Semver: minor ⚙️

#414 cli(yargs): use yargs.command for sub-commands
  bin/config-yargs.js
  bin/process-node-flags.js
  bin/webpack.js
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: reviewed-changes-requested
