Repository webpack/webpack-cli, pull requests merged in 2019-09, with the labels that each got.

#1065 fix: support both webpack versions
  bin/utils/convert-argv.js
  bin/utils/validate-options.js
  package-lock.json
  package.json
  packages/generate-loader/package-lock.json
  packages/generate-plugin/package-lock.json
  packages/generators/package-lock.json
  packages/init/package-lock.json
  packages/migrate/package-lock.json
  packages/serve/package-lock.json
  test/binCases/errors/v5-schema-validation/options.js
  test/binCases/errors/v5-schema-validation/validation.test.js
Labels: PR: CI-ok, PR: review-outdated

#1072 chore: minor code refactor
  lib/commands/external.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1062 chore: changed the outDir to entry test
  test/entry/entry-single-arg.test.js
  test/utils/test-utils.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1071 Tests: added tests with different config type
  test/config/.gitignore
  test/config/config-type/array/a.js
  test/config/config-type/array/configArray.test.js
  test/config/config-type/array/webpack.config.js
  test/config/config-type/function/a.js
  test/config/config-type/function/configFunction.test.js
  test/config/config-type/function/webpack.config.js
  test/config/config-type/promise/a.js
  test/config/config-type/promise/configPromise.test.js
  test/config/config-type/promise/webpack.config.js
Labels: PR: CI-ok, PR: reviewed-approved

#1078 fix: fix webpack hanging under certain circumstance
  bin/cli.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1073 Tests: added test for --json with simple usecases
  test/json/.gitignore
  test/json/basic/index.js
  test/json/basic/jsonBasic.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1079 test: add test for color in help
  package.json
  test/help/help-single-arg.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1050 tests: add tests for entry defaults, try to set better defaults
  .gitignore
  build/changelog-generator/index.js
  lib/bootstrap.js
  lib/utils/dev-config.js
  lib/webpack-cli.js
  packages/webpack-scaffold/index.ts
  test/config/basic/basic-config.test.js
  test/entry/defaults-empty/entry-single-arg.test.js
  test/entry/defaults-index/entry-multi-args.test.js
  test/entry/defaults-index/index.js
  test/utils/test-utils.js
Labels: PR: review-outdated

#1081 chore: minor typographical fixes
  commitlint.config.js
  lib/groups/config.js
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#1011 [NEXT]: webpack-cli serve refactor draft
  lib/bootstrap.js
  lib/commands/external.js
  lib/utils/cli-flags.js
  lib/utils/compiler.js
  lib/utils/dev-server-flags.js
  lib/webpack-cli.js
  packages/generators/types/json-loader.d.ts
  packages/serve/.gitignore
  packages/serve/args-to-camel-case.ts
  packages/serve/index.ts
  packages/serve/package-lock.json
  packages/serve/package.json
  packages/serve/startDevServer.ts
  packages/serve/tsconfig.json
  test/help/__snapshots__/help-single-arg.test.js.snap
Labels: PR: CI-not-ok, PR: reviewed-approved

#1086 chore: minor stylistic refactor
  lib/groups/config.js
  lib/utils/compiler.js
  lib/utils/zero-config.js
  test/env/array/array-env.test.js
  test/env/object/object-env.test.js
Labels: PR: CI-ok, PR: reviewed-approved
