Repository webpack/webpack-cli, pull requests merged in 2019-07, with the labels that each got.

#979 docs: remove removed packages description
  packages/README.md
Labels: PR: CI-ok, PR: reviewed-approved

#973 chore: prevent weird behaviour of pre-commit hook
  packages/generate-loader/.eslintrc
  packages/generate-loader/package-lock.json
  packages/generate-plugin/.eslintrc
  packages/generate-plugin/package-lock.json
  packages/generators/.eslintrc
  packages/generators/package-lock.json
  packages/info/.eslintrc
  packages/init/.eslintrc
  packages/init/package-lock.json
  packages/migrate/.eslintrc
  packages/migrate/package-lock.json
  packages/serve/.eslintrc
  packages/serve/package-lock.json
  packages/utils/.eslintrc
  packages/webpack-scaffold/.eslintrc
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#975 chore(utils): Fix path in scaffold util
  packages/utils/scaffold.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#974 chore(serve): refactor code to be more concise
  packages/serve/index.ts
Labels: PR: CI-ok, PR: reviewed-approved

#1006 fix: make init resolve linked packges
  packages/utils/npm-packages-exists.ts
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#971 fix: improve local configRegister file resolution
  lib/groups/config.js
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#1008 Docs readme
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
