Repository webpack/webpack-cli, pull requests merged in 2019-01, with the labels that each got.

#723 fixx: security vulnerability npm release 0.1.2
  packages/generators/package.json
Labels: PR: reviewed-approved, PR: reviewed-changes-requested, PR: small

#720 docs: update generators README
  packages/generators/README.md
Labels: PR: CI-ok, PR: reviewed-approved

#693 Feature/find config recursively
  bin/convert-argv.js
  package-lock.json
  package.json
  test/binCases/config-location/find-recursively/index2.js
  test/binCases/config-location/find-recursively/packages/foo/find-recursively.test.js
  test/binCases/config-location/find-recursively/webpack.config.js
  test/binCases/config-location/not-found/not-found.test.js
  test/binCases/config-location/not-found/src/index.js
  test/binCases/config-location/set-explicitly/index.js
  test/binCases/config-location/set-explicitly/set-explicitly.test.js
  test/binCases/config-location/set-explicitly/webpack.dev.js
  test/binCases/config-location/set-implicitly/index2.js
  test/binCases/config-location/set-implicitly/set-implicitly.test.js
  test/binCases/config-location/set-implicitly/webpack.config.js
  test/binCases/config-location/webpackfile-config/index2.js
  test/binCases/config-location/webpackfile-config/packages/foo/index1.js
  test/binCases/config-location/webpackfile-config/packages/foo/webpackfile-config.test.js
  test/binCases/config-location/webpackfile-config/packages/foo/webpackfile.js
  test/binCases/config-location/webpackfile-config/webpack.config.js
Labels: PR: reviewed-approved

#716 misc: not scaffold 'dist' if the user chooses default
  packages/generators/init-generator.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#727 Add installation guide for packages/webpack-scaffold
  packages/webpack-scaffold/README.md
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#728 fix(bin): extension detection (#724)
  bin/convert-argv.js
  package-lock.json
  package.json
  test/binCases/config-location/webpack-babel-config/.babelrc
  test/binCases/config-location/webpack-babel-config/index2.js
  test/binCases/config-location/webpack-babel-config/webpack-babel-config.test.js
  test/binCases/config-location/webpack-babel-config/webpack.config.babel.js
  test/binCases/config-location/webpack-ts-config/index2.js
  test/binCases/config-location/webpack-ts-config/tsconfig.json
  test/binCases/config-location/webpack-ts-config/webpack-ts-config.test.js
  test/binCases/config-location/webpack-ts-config/webpack.config.ts
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#736 tests(fix): fix failing tests
  .travis.yml
  commitlint.config.js
  package.json
  test/binCases/config-location/webpack-ts-config/webpack-ts-config.test.js
  test/binCases/help/help-output/__snapshots__/help-output.test.js.snap
  test/binCases/help/help-output/help-output.test.js
  test/binCases/plugins/uglifyjsplugin-empty-args/uglifyjsplugin-empty-args.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#735 fix(test): fix travis TS build
  .travis.yml
  package.json
Labels: PR: CI-ok, PR: review-outdated, PR: small

#700 feat(ui): init interface for UI
  packages/init/config.ts
  packages/init/index.ts
  packages/init/package-lock.json
  packages/ui-server/README.md
  packages/ui-server/package.json
  packages/ui-server/routes/api/index.js
  packages/ui-server/routes/api/init.js
  packages/ui-server/routes/index.js
  packages/ui-server/utils/questioner.ts
  packages/ui-server/utils/user.ts
  packages/webpack-scaffold/index.ts
  tsconfig.packages.json
Labels: PR: CI-not-ok, PR: reviewed-approved

#732 feat(log): add task based custom logger
  packages/log/.gitignore
  packages/log/index.ts
  packages/log/package.json
  packages/log/tsconfig.json
Labels: PR: CI-ok, PR: reviewed-approved
