Repository webpack/webpack-cli, pull requests merged in 2019-05, with the labels that each got.

#871 chore(travis): temporary remove node stable
  .travis.yml
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#873 docs: code of conduct
  CODE_OF_CONDUCT.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#874 chore(docs): minor fixes in the docs
  .github/CONTRIBUTING.md
  README.md
  packages/README.md
  packages/generate-loader/README.md
  packages/generate-plugin/README.md
  packages/generators/README.md
  packages/info/README.md
  packages/init/README.md
  packages/migrate/README.md
  packages/remove/README.md
  packages/serve/README.md
  packages/update/README.md
  packages/utils/README.md
Labels: PR: CI-ok, PR: review-outdated

#869 chore(types): move to @types/yeoman-generator
  packages/generate-loader/types/Yeoman.ts
  packages/generate-plugin/types/Yeoman.ts
  packages/generators/add-generator.ts
  packages/generators/addon-generator.ts
  packages/generators/init-generator.ts
  packages/generators/package-lock.json
  packages/generators/package.json
  packages/generators/remove-generator.ts
  packages/generators/types/yeoman-generator.d.ts
  packages/generators/update-generator.ts
  packages/generators/utils/entry.ts
  packages/utils/copy-utils.ts
  packages/utils/modify-config-helper.ts
  packages/utils/package-lock.json
  packages/utils/package.json
  packages/utils/types/Yeoman.ts
  packages/webpack-scaffold/index.ts
  packages/webpack-scaffold/package-lock.json
  packages/webpack-scaffold/package.json
Labels: PR: CI-ok, PR: reviewed-approved

#857 chore(deps): fix security vulnerabilities
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#859 chore(docs): Refactors links for badges
  README.md
  packages/add/README.md
  packages/generate-loader/README.md
  packages/generate-plugin/README.md
  packages/generators/README.md
  packages/info/README.md
  packages/init/README.md
  packages/migrate/README.md
  packages/remove/README.md
  packages/serve/README.md
  packages/update/README.md
  packages/utils/README.md
  packages/webpack-scaffold/README.md
Labels: PR: CI-ok, PR: reviewed-approved

#876 fix(opencollective-prompt): fix EPERM error
  bin/cli.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#863 feat(opencollective prompt): add disable option
  README.md
  bin/opencollective.js
Labels: PR: CI-ok, PR: reviewed-approved

#872 chore(ci): add node 12
  .travis.yml
  azure-pipelines-template.yml
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: review-outdated, PR: small

#851 feat(md): formats md before committing
  .github/CONTRIBUTING.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  package.json
  packages/generators/README.md
  packages/utils/README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#883 fix(generator): using configFile in configPath to get the config file name
  packages/generators/init-generator.ts
  packages/generators/remove-generator.ts
  packages/utils/modify-config-helper.ts
Labels: PR: CI-ok, PR: review-outdated, PR: small

#895 chore(github): add sponsor button
  .github/FUNDING.yml
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#892 cli: fix watch options for array config
  bin/cli.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#896 [sec]: Initial security policy
  SECURITY.md
Labels: PR: CI-ok, PR: reviewed-approved

#893 chore(add-generator): changed the naming of the plugin in config file
  packages/generators/__tests__/add-generator.test.ts
  packages/generators/add-generator.ts
  packages/generators/utils/plugins.ts
  tsconfig.base.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#817 misc(init-generator) cli improvements & refactor
  INIT.md
  SECURITY.md
  package-lock.json
  packages/generators/.gitignore
  packages/generators/add-generator.ts
  packages/generators/init-generator.ts
  packages/generators/templates/README.md
  packages/generators/templates/index.js
  packages/generators/templates/package.json.js
  packages/generators/templates/tsconfig.json.js
  packages/generators/types/index.ts
  packages/generators/utils/entry.ts
  packages/generators/utils/languageSupport.ts
  packages/generators/utils/module.ts
  packages/generators/utils/styleSupport.ts
  packages/generators/utils/tooltip.ts
  packages/generators/utils/webpackConfig.ts
  packages/utils/package-lock.json
  packages/utils/package.json
  packages/utils/run-prettier.ts
  packages/utils/scaffold.ts
  packages/webpack-scaffold/README.md
  packages/webpack-scaffold/__tests__/__snapshots__/index.test.ts.snap
  packages/webpack-scaffold/__tests__/index.test.ts
  packages/webpack-scaffold/index.ts
Labels: PR: CI-ok, PR: reviewed-approved, Up for Manual Verification

#806 chore(cli): remove findup-sync from root move to utils package && format ts files
  .eslintignore
  INIT.md
  bin/cli.js
  bin/opencollective.js
  package-lock.json
  package.json
  packages/generators/__tests__/add-generator.test.ts
  packages/generators/add-generator.ts
  packages/generators/addon-generator.ts
  packages/generators/index.ts
  packages/generators/init-generator.ts
  packages/generators/loader-generator.ts
  packages/generators/plugin-generator.ts
  packages/generators/templates/README.md
  packages/generators/templates/package.json.js
  packages/generators/utils/entry.ts
  packages/generators/utils/languageSupport.ts
  packages/generators/utils/plugins.ts
  packages/generators/utils/styleSupport.ts
  packages/generators/utils/webpackConfig.ts
  packages/init/init.ts
  packages/migrate/__tests__/migrate.test.ts
  packages/migrate/commonsChunkPlugin/__tests__/commonsChunkPlugin.test.ts
  packages/migrate/extractTextPlugin/extractTextPlugin.ts
  packages/migrate/loaderOptionsPlugin/__tests__/loaderOptionsPlugin.test.ts
  packages/migrate/loaders/loaders.ts
  packages/migrate/moduleConcatenationPlugin/__tests__/moduleConcatenationPlugin.test.ts
  packages/migrate/noEmitOnErrorsPlugin/__tests__/noEmitOnErrorsPlugin.test.ts
  packages/migrate/outputPath/outputPath.ts
  packages/migrate/removeDeprecatedPlugins/__tests__/removeDeprecatedPlugins.test.ts
  packages/migrate/removeJsonLoader/__tests__/removeJsonLoader.test.ts
  packages/migrate/resolve/resolve.ts
  packages/migrate/types/NodePath.ts
  packages/migrate/uglifyJsPlugin/uglifyJsPlugin.ts
  packages/utils/__tests__/is-local-path.test.ts
  packages/utils/__tests__/npm-exists.test.ts
  packages/utils/__tests__/npm-packages-exists.test.ts
  packages/utils/__tests__/package-manager.test.ts
  packages/utils/__tests__/recursive-parser.test.ts
  packages/utils/ast-utils.ts
  packages/utils/find-root.ts
  packages/utils/modify-config-helper.ts
  packages/utils/npm-packages-exists.ts
  packages/utils/package-manager.ts
  packages/utils/path-utils.ts
  packages/utils/prop-types.ts
  packages/utils/resolve-packages.ts
  packages/utils/run-prettier.ts
  packages/utils/scaffold.ts
  packages/utils/types/NodePath.ts
  packages/webpack-scaffold/__tests__/index.test.ts
  packages/webpack-scaffold/index.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: reviewed-changes-requested

#903 fix(cli): made --config-register resolve relative to root path
  bin/utils/convert-argv.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
