Repository webpack/webpack-cli, pull requests merged in 2019-11, with the labels that each got.

#1103 tests: configuration lookup
  lib/groups/config.js
  lib/utils/compiler.js
  packages/serve/package-lock.json
  test/config-lookup/dotfolder-array/.webpack/webpack.config.js
  test/config-lookup/dotfolder-array/a.js
  test/config-lookup/dotfolder-array/dotfolder-array.test.js
  test/config-lookup/dotfolder-single/.webpack/webpack.config.js
  test/config-lookup/dotfolder-single/dotfolder-single.test.js
  test/config-lookup/dotfolder-single/index_two.js
  test/config/empty/empty-config.test.js
Labels: PR: conflict, PR: reviewed-approved

#1105 chore: minor code refactoring
  lib/utils/commands.js
  lib/webpack-cli.js
Labels: PR: CI-ok, PR: reviewed-approved

#1100 tests(serve): add serve tests
  .gitignore
  packages/serve/package-lock.json
  packages/serve/package.json
  test/config/serve-basic/index.js
  test/config/serve-basic/node_modules/@webpack-cli/serve/index.js
  test/config/serve-basic/webpack.config.js
  test/serve/serve-basic.test.js
  test/utils/test-utils.js
Labels: PR: CI-ok, PR: reviewed-approved

#1115 chore(serve): use cli flags from dev server package
  lib/utils/dev-server-flags.js
  packages/serve/index.ts
Labels: PR: CI-not-ok, PR: reviewed-approved

#1119 chore: Remove redundant multiple property of OptionDefinition cli-flags.js
  lib/utils/cli-flags.js
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#1120 fix: Remove redundant await keyword
  lib/webpack-cli.js
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#1121 fix: Use ES6 object initializer shorthand
  lib/webpack-cli.js
Labels: PR: reviewed-approved, PR: small

#1123 fix: warnings on lint
  lib/bootstrap.js
  lib/commands/external.js
  lib/groups/advanced.js
  lib/groups/basic.js
  lib/groups/config.js
  lib/groups/help.js
  lib/groups/output.js
  lib/groups/stats.js
  lib/utils/compiler.js
  lib/utils/development-config.js
  lib/utils/group-helper.js
  lib/utils/process-log.js
  lib/utils/production-config.js
  lib/utils/zero-config.js
  lib/webpack-cli.js
  test/serve/serve-basic.test.js
Labels: PR: CI-not-ok, PR: reviewed-approved

#1124 fix: refactor redundant code
  lib/webpack-cli.js
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small
