Repository webpack/webpack-cli, pull requests merged in 2019-06, with the labels that each got.

#862 fix(cli): throws err when no args passed
  bin/cli.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#911 docs: fix link to webpack-scaffold
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#913 chore: refactor serve command action handler
  packages/serve/index.ts
Labels: PR: CI-ok, PR: reviewed-approved

#909 chore(utils): separated interfaces from the core module
  packages/utils/modify-config-helper.ts
  packages/utils/scaffold.ts
  packages/utils/types/Config.ts
Labels: PR: CI-ok, PR: review-outdated

#914 chore(migrate): fixes console error while running tests.
  packages/migrate/removeDeprecatedPlugins/removeDeprecatedPlugins.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#917 chore: fix azure
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: unreviewed

#921 feat(chore): Added type definitions for the data returned by envinfo
  packages/info/index.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#926 chore(lint): fix lint warnings
  packages/generators/init-generator.ts
  packages/generators/remove-generator.ts
  packages/migrate/commonsChunkPlugin/commonsChunkPlugin.ts
Labels: PR: CI-ok, PR: reviewed-approved

#920 chore(refactor): use all utils from the root file in generators
  package-lock.json
  packages/generators/__tests__/add-generator.test.ts
  packages/generators/add-generator.ts
  packages/generators/init-generator.ts
  packages/generators/utils/index.ts
Labels: PR: CI-ok, PR: reviewed-approved

#929 [infra]: format staged code on precommit
  package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#931 chore: refactored the add-generator
  packages/generators/add-generator.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#915 chore(utils): refactor ast utils and output message
  packages/utils/ast-utils.ts
  packages/utils/modify-config-helper.ts
Labels: PR: CI-ok, PR: reviewed-approved

#923 docs(contributing): updates the docs for the test
  .github/CONTRIBUTING.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#924 [utils]: refactor export types to index file
  packages/init/init.ts
  packages/utils/scaffold.ts
  packages/utils/types/Error.ts
  packages/utils/types/index.ts
Labels: PR: CI-ok, PR: reviewed-approved

#934 docs(contributing): combines separate sections for yarn and npm into one.
  .github/CONTRIBUTING.md
Labels: PR: CI-ok, PR: reviewed-approved

#797 fix(add): add handling of merge option
  packages/generators/add-generator.ts
  packages/generators/utils/add/index.ts
  packages/generators/utils/add/questions.ts
  packages/generators/utils/index.ts
  packages/serve/index.ts
  packages/utils/ast-utils.ts
  packages/utils/modify-config-helper.ts
  packages/utils/package-lock.json
  packages/utils/recursive-parser.ts
  packages/utils/scaffold.ts
  packages/utils/types/NodePath.ts
  packages/utils/types/index.ts
Labels: PR: CI-ok, PR: reviewed-approved, Up for Manual Verification

#935 fix: improve checking file permission
  bin/cli.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#942 feat: better defaults (0CJS) with config generation
  bin/utils/prompt-command.js
  packages/generators/init-generator.ts
  packages/generators/templates/package.json.js
  packages/generators/templates/template.html
  packages/generators/utils/webpackConfig.ts
  packages/utils/scaffold.ts
Labels: PR: unreviewed

#951 Fix: command mismatching, running always init command
  bin/utils/prompt-command.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#947 docs: added auto flag in docs for init command
  packages/init/README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#949 fix: module not found error
  bin/cli.js
Labels: PR: CI-ok, PR: review-outdated

#952 chore(docs): fixes 404 URLs and unformatted table
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#958 chore(packages): lock dependencies versions
  azure-pipelines-template.yml
  package-lock.json
  package.json
  packages/generate-loader/package-lock.json
  packages/generate-loader/package.json
  packages/generate-plugin/package-lock.json
  packages/generate-plugin/package.json
  packages/generators/package-lock.json
  packages/generators/package.json
  packages/info/package-lock.json
  packages/info/package.json
  packages/init/init.ts
  packages/init/package-lock.json
  packages/init/package.json
  packages/init/types/NodePath.ts
  packages/migrate/package-lock.json
  packages/migrate/package.json
  packages/serve/package-lock.json
  packages/serve/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
  packages/webpack-scaffold/package-lock.json
  packages/webpack-scaffold/package.json
  tsconfig.base.json
Labels: PR: CI-ok, PR: reviewed-approved

#959 fix: update deps
  package-lock.json
Labels: PR: CI-ok, PR: reviewed-approved

#948 chore: added await in order to resolve the pending promise
  packages/generators/init-generator.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#960 fix: change "usr strict" to "use strict"
  test/binCases/config-type/array/array.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#961 chore(ts): enables source map in the ts
  .gitignore
  tsconfig.base.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#968 fix(deps): move prettier from dependencies to devDependencies
  package-lock.json
  package.json
Labels: PR: reviewed-approved, PR: small

#969 chore(deps): update major versions
  package-lock.json
  package.json
  packages/generate-loader/package-lock.json
  packages/generate-loader/package.json
  packages/generate-plugin/package-lock.json
  packages/generate-plugin/package.json
  packages/generators/package-lock.json
  packages/generators/package.json
  packages/info/package-lock.json
  packages/info/package.json
  packages/init/package-lock.json
  packages/init/package.json
  packages/migrate/index.ts
  packages/migrate/package-lock.json
  packages/migrate/package.json
  packages/serve/package-lock.json
  packages/serve/package.json
  packages/utils/package-lock.json
  packages/utils/package.json
  packages/webpack-scaffold/package-lock.json
  packages/webpack-scaffold/package.json
Labels: PR: CI-ok, PR: reviewed-approved

#970 chore(scripts): clean postinstall
  bin/opencollective.js
  package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
