Repository webpack/webpack-cli, pull requests merged in 2019-08, with the labels that each got.

#1010 [NEXT]: fix missing package, fix bad function call
  lib/groups/config.js
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#1014 tests: add no-args help test
  package-lock.json
  package.json
  test/binCases/help/no-args/__snapshots__/help-no-args.test.js.snap
  test/binCases/help/no-args/help-no-args.test.js
Labels: PR: CI-ok, PR: review-outdated

#1018 [NEXT] BugFix: changed the path resolver call
  lib/groups/output.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1021 fix(serve): minor grammatical correction
  packages/serve/index.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1019 tests: help flag
  CODEOWNERS
  lib/bootstrap.js
  lib/groups/help.js
  lib/utils/compiler.js
  lib/webpack-cli.js
  test/binCases/help/empty/__snapshots__/command.test.js.snap
  test/binCases/help/empty/__snapshots__/dashed.test.js.snap
  test/binCases/help/empty/command.test.js
  test/binCases/help/empty/dashed.test.js
  test/binCases/help/mixed/__snapshots__/mixed.test.js.snap
  test/binCases/help/mixed/__snapshots__/precedence-command.test.js.snap
  test/binCases/help/mixed/__snapshots__/precedence-dashed.test.js.snap
  test/binCases/help/mixed/mixed.test.js
  test/binCases/help/mixed/precedence-command.test.js
  test/binCases/help/mixed/precedence-dashed.test.js
Labels: PR: CI-ok, PR: review-outdated

#1020 cli: replace cli-table with cli-table3
  lib/utils/compiler.js
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1022 chore(notifier): update notifier frequency
  cli.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1002 chore: refactor code to eliminate redundancy
  packages/utils/__tests__/package-manager.test.ts
  packages/utils/package-manager.ts
Labels: PR: CI-ok, PR: reviewed-approved

#977 fix(init): fixes config resolution on generating new configuration
  packages/utils/modify-config-helper.ts
Labels: PR: CI-ok, PR: reviewed-approved

#1025 fix(chore): remove extraneous ternary logic
  packages/generators/init-generator.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#955 docs(readme): adds deprecated warning and commands
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1027 feat(docs): Minor tweaks
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1026 tests: add tests for version, improve conventions
  .cz-config.js
  lib/bootstrap.js
  lib/groups/help.js
  lib/utils/compiler.js
  lib/webpack-cli.js
  packages/generate-loader/package-lock.json
  packages/generate-plugin/package-lock.json
  packages/generators/package-lock.json
  packages/init/package-lock.json
  packages/migrate/package-lock.json
  packages/serve/package-lock.json
  packages/utils/__tests__/package-manager.test.ts
  packages/utils/modify-config-helper.ts
  packages/utils/package-lock.json
  packages/utils/resolve-packages.ts
  packages/webpack-scaffold/package-lock.json
  test/binCases/help/empty/__snapshots__/command.test.js.snap
  test/binCases/help/empty/__snapshots__/dashed.test.js.snap
  test/binCases/help/empty/command.test.js
  test/binCases/help/empty/dashed.test.js
  test/binCases/help/mixed/__snapshots__/precedence-command.test.js.snap
  test/binCases/help/mixed/__snapshots__/precedence-dashed.test.js.snap
  test/binCases/help/mixed/mixed.test.js
  test/binCases/help/mixed/precedence-command.test.js
  test/binCases/help/mixed/precedence-dashed.test.js
  test/help/__snapshots__/help-single-arg.test.js.snap
  test/help/help-multi-args.test.js
  test/help/help-single-arg.test.js
  test/utils/exec-in-directory.js
  test/utils/test-utils.js
  test/utils/test-utils.test.js
  test/version/version-multi-args.test.js
  test/version/version-single-arg.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1036 chore: update version test
  test/version/version-multi-args.test.js
  test/version/version-single-arg.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1024 fix: resolve opts when no-config & fix vulns
  bin/utils/convert-argv.js
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#1041 fix(deps): add missing cz-customizable dep to allow committing
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#1039 chore(cli): fix var name to correct meaning
  lib/groups/help.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1042 chore(help): refactor help for more cleaner code
  lib/groups/help.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1043 feat(stats): refactor code
  lib/groups/stats.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1037 chore(bootstrap): refactor code
  lib/bootstrap.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: reviewed-changes-requested, PR: small

#1038 feat: use JS Webpack Plugin
  lib/utils/dev-config.js
  lib/utils/prod-config.js
  package-lock.json
  package.json
Labels: PR: reviewed-approved, PR: unreviewed

#1047 misc: fix infra & add failing test
  .eslintrc.js
  lib/utils/compiler.js
  packages/generators/.eslintrc
  packages/generators/init-generator.ts
  packages/generators/tsconfig.json
  packages/generators/utils/entry.ts
  packages/generators/utils/languageSupport.ts
  packages/generators/utils/plugins.ts
  packages/migrate/.eslintrc
  packages/migrate/index.ts
  packages/serve/index.ts
  packages/utils/.eslintrc
  packages/utils/__tests__/package-manager.test.ts
  packages/utils/copy-utils.ts
  packages/utils/modify-config-helper.ts
  packages/webpack-scaffold/index.ts
  test/entry/entry-single-arg.test.js
  test/utils/test-utils.js
  test/utils/test-utils.test.js
Labels: PR: unreviewed

#1048 chore: only output message on error
  packages/generators/addon-generator.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1052 Support `export default` from configuration files.
  lib/groups/config.js
Labels: PR: CI-ok, PR: reviewed-approved

#1049 chore: replace console logs with webpack log
  lib/groups/advanced.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1054 Update README.md
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1057 chore: minor tweak
  test/utils/exec-in-directory.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1056 chore: fix minor typo
  test/version/version-multi-args.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1059 chore(GroupHelper): minor tweak
  lib/utils/group-helper.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1061 chore(init): rephrase comment
  packages/init/index.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1058 chore: refactor
  lib/groups/config.js
  lib/utils/group-helper.js
  test/utils/test-utils.js
Labels: PR: CI-ok, PR: reviewed-approved

#1060 chore(compiler): refactor emoji rendering logic in compiler
  lib/utils/compiler.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: reviewed-changes-requested, PR: small

#1066 feat: refactor logic
  lib/utils/group-helper.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1063 tests: added tests for config
  test/config/.gitignore
  test/config/basic/a.js
  test/config/basic/basicConfig.test.js
  test/config/basic/webpack.config.js
  test/config/empty/emptyConfig.test.js
  test/config/empty/webpack.config.js
Labels: PR: CI-ok, PR: reviewed-approved

#1007 feat(info): new features
  packages/info/README.md
  packages/info/__tests__/index.test.ts
  packages/info/commands.ts
  packages/info/configParser.ts
  packages/info/index.ts
  packages/info/options.ts
  packages/info/package-lock.json
  packages/info/package.json
  packages/info/renderTable.ts
Labels: PR: CI-ok, PR: reviewed-approved

#1070 chore(cli): colorize commands to run and package to be installed
  lib/commands/external.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
