Repository webpack/webpack-cli, pull requests merged in 2019-03, with the labels that each got.

#765 tests(migration): including requested changes
  commitlint.config.js
  packages/migrate/bannerPlugin/__tests__/bannerPlugin.test.ts
  packages/migrate/commonsChunkPlugin/__tests__/commonsChunkPlugin.test.ts
  packages/migrate/extractTextPlugin/__tests__/extractTextPlugin.test.ts
  packages/migrate/index.ts
  packages/migrate/loaderOptionsPlugin/__tests__/loaderOptionsPlugin.test.ts
  packages/migrate/loaders/__tests__/loaders.test.ts
  packages/migrate/migrate.ts
  packages/migrate/moduleConcatenationPlugin/__tests__/moduleConcatenationPlugin.test.ts
  packages/migrate/namedModulesPlugin/__tests__/namedModulesPlugin.test.ts
  packages/migrate/noEmitOnErrorsPlugin/__tests__/noEmitOnErrorsPlugin.test.ts
  packages/migrate/outputPath/__tests__/outputPath.test.ts
  packages/migrate/removeDeprecatedPlugins/__tests__/removeDeprecatedPlugins.test.ts
  packages/migrate/removeJsonLoader/__tests__/removeJsonLoader.test.ts
  packages/migrate/resolve/__tests__/__snapshots__/resolve.test.ts.snap
  packages/migrate/resolve/__tests__/__testfixtures__/resolve.input.js
  packages/migrate/resolve/__tests__/resolve.test.ts
  packages/migrate/uglifyJsPlugin/__tests__/uglifyJsPlugin.test.ts
  packages/utils/__tests__/ast-utils.test.ts
Labels: PR: CI-ok, PR: reviewed-approved

#766 Bugfix/skip broken tests
  .travis.yml
  test/binCases/watch/info-verbosity-off/info-verbosity-off.test.js
  test/binCases/watch/info-verbosity-verbose/info-verbosity-verbose.test.js
  test/binCases/watch/multi-config-watch-opt/multi-config-watch-opt.test.js
  test/binCases/watch/multi-config/multi-config.test.js
  test/binCases/watch/single-config-watch-opt/single-config-watch-opt.test.js
  test/binCases/watch/single-config/single-config.test.js
Labels: PR: CI-not-ok, PR: reviewed-approved, PR: small

#779 docs(readme): add downloads badge
  README.md
Labels: PR: reviewed-approved, PR: reviewed-changes-requested, PR: small

#777 docs(contributing): commands to install jest globally
  .github/CONTRIBUTING.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#753 feat: use webpack.config as default name in dev scaffold
  packages/generators/init-generator.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#776 chore(deps): fix vulnerabilities
  package-lock.json
  package.json
  packages/info/package-lock.json
  packages/init/package-lock.json
  packages/migrate/package-lock.json
  packages/utils/package-lock.json
  packages/webpack-scaffold/package-lock.json
Labels: PR: CI-ok, PR: reviewed-approved

#763 fix(bin): use compiler.close API correctly for stats
  bin/cli.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#757 docs(contributing): adds prebuild instructions
  .github/CONTRIBUTING.md
Labels: Chill ❄️, PR: reviewed-approved

#768 docs(contributing): improve formatting
  .github/CONTRIBUTING.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#742 fix(init): fix init prompt installation
  bin/prompt-command.js
Labels: PR: CI-ok, PR: reviewed-approved

#786 docs: add lerna badge in README
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#773 docs(scaffolding): improved structure, formatting, typos
  SCAFFOLDING.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: reviewed-changes-requested

#792 Feature/replace uglify with terser
  packages/generators/init-generator.ts
  packages/generators/utils/plugins.ts
  packages/generators/utils/tooltip.ts
  packages/migrate/uglifyJsPlugin/__tests__/__snapshots__/uglifyJsPlugin.test.ts.snap
  packages/migrate/uglifyJsPlugin/uglifyJsPlugin.ts
Labels: PR: CI-ok, PR: reviewed-approved

#755 enh(Add open collective prompt)
  bin/cli.js
  bin/opencollective.js
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#794 enh(webpack-scaffold): improve prompt and doc
  INIT.md
  packages/generators/add-generator.ts
  packages/generators/init-generator.ts
  packages/generators/types/yeoman-generator.d.ts
  packages/generators/utils/entry.ts
  packages/webpack-scaffold/README.md
  packages/webpack-scaffold/__tests__/__snapshots__/index.test.ts.snap
  packages/webpack-scaffold/__tests__/index.test.ts
  packages/webpack-scaffold/index.ts
Labels: PR: CI-ok, PR: reviewed-approved

#796 fix(add): add handling for topScope
  packages/generators/add-generator.ts
  packages/utils/scaffold.ts
Labels: PR: CI-ok, PR: reviewed-approved

#781 misc(cli): refactor functions into utils and config dirs, merge yargs…
  bin/cli.js
  bin/config/config-yargs.js
  bin/config/optionsSchema.json
  bin/config/webpackConfigurationSchema.json
  bin/utils/convert-argv.js
  bin/utils/errorHelpers.js
  bin/utils/prepareOptions.js
  bin/utils/prompt-command.js
Labels: PR: CI-ok, PR: reviewed-approved

#791 chore(types): add type information
  packages/add/index.ts
  packages/generate-loader/index.ts
  packages/generate-plugin/index.ts
  packages/generators/add-generator.ts
  packages/generators/addon-generator.ts
  packages/generators/init-generator.ts
  packages/generators/remove-generator.ts
  packages/generators/utils/validate.ts
  packages/init/index.ts
  packages/init/init.ts
  packages/migrate/index.ts
  packages/remove/index.ts
  packages/serve/index.ts
  packages/update/index.ts
  packages/utils/ast-utils.ts
  packages/utils/copy-utils.ts
  packages/utils/defineTest.ts
  packages/utils/modify-config-helper.ts
  packages/utils/npm-exists.ts
  packages/utils/npm-packages-exists.ts
  packages/utils/package-manager.ts
  packages/utils/scaffold.ts
  packages/utils/validate-identifier.ts
  packages/webpack-scaffold/index.ts
Labels: PR: CI-ok, PR: review-outdated

#798 chore(cli): move constants to a separate file
  bin/cli.js
  bin/config/config-yargs.js
  bin/utils/constants.js
  bin/utils/errorHelpers.js
Labels: PR: CI-ok, PR: reviewed-approved

#801 fix(scaffold): config file is always generated at the project root
  packages/utils/find-root.ts
  packages/utils/package-lock.json
  packages/utils/package.json
  packages/utils/scaffold.ts
Labels: PR: CI-ok, PR: reviewed-approved

#809 chore(tests): updated test regex, some helper scripts
  .github/CONTRIBUTING.md
  package.json
  test/binCases/stats/single-config/single-config.test.js
  test/binCases/watch/info-verbosity-off/info-verbosity-off.test.js
  test/binCases/watch/info-verbosity-verbose/info-verbosity-verbose.test.js
  test/binCases/watch/multi-config-watch-opt/multi-config-watch-opt.test.js
  test/binCases/watch/multi-config/multi-config.test.js
  test/binCases/watch/single-config-watch-opt/single-config-watch-opt.test.js
  test/binCases/watch/single-config/single-config.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
