Repository webpack/webpack-cli, pull requests merged in 2020-02, with the labels that each got.

#1196 Better output
  .eslintrc.js
  bin/cli.js
  build/changelog-generator/index.js
  build/changelog-generator/templates/commit.hbs
  build/changelog-generator/templates/header.hbs
  build/changelog-generator/templates/template.hbs
  lib/bootstrap.js
  lib/commands/external.js
  lib/groups/advanced.js
  lib/groups/basic.js
  lib/groups/config.js
  lib/groups/help.js
  lib/groups/output.js
  lib/groups/stats.js
  lib/utils/Compiler.js
  lib/utils/CompilerOutput.js
  lib/utils/compiler.js
  lib/utils/development-config.js
  lib/utils/group-helper.js
  lib/utils/interactive.js
  lib/utils/parse-args.js
  lib/utils/process-log.js
  lib/utils/production-config.js
  lib/utils/zero-config.js
  lib/webpack-cli.js
  package.json
  packages/generators/package-lock.json
  smoketests/watch/watch.array.smoketest.js
  smoketests/watch/watch.single.smoketest.js
  test/config/type/function/webpack.config.js
  test/config/type/promise/webpack.config.js
  test/info/info-basic.test.js
  test/output/pretty/pretty.test.js
  test/output/pretty/src/index.js
  test/serve/serve-basic.test.js
  test/utils/test-utils.js
Labels: PR: CI-ok, PR: reviewed-approved

#1198 Always spawn a process for cli
  bin/cli.js
  lib/bootstrap.js
  packages/generators/__tests__/init-generator.test.ts
Labels: PR: CI-ok, PR: reviewed-approved

#1203 fix(init): fixed package template to include name param
  packages/generators/templates/package.json.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1187 docs: Updated information regarding migrate command and a typo fix
  .github/CONTRIBUTING.md
  packages/utils/npm-packages-exists.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1204 chore(cli): better group handling
  .prettierrc
  bin/cli.js
  lib/groups/AdvancedGroup.js
  lib/groups/BasicGroup.js
  lib/groups/ConfigGroup.js
  lib/groups/HelpGroup.js
  lib/groups/OutputGroup.js
  lib/groups/StatsGroup.js
  lib/groups/ZeroConfigGroup.js
  lib/utils/GroupHelper.js
  lib/utils/cli-flags.js
  lib/utils/development-config.js
  lib/utils/production-config.js
  lib/utils/zero-config.js
  lib/webpack-cli.js
  test/GroupHelper.test.js
  test/config-lookup/dotfolder-array/dotfolder-array.test.js
  test/config/basic/basic-config.test.js
  test/config/empty/empty-config.test.js
  test/config/type/array/array-config.test.js
  test/config/type/function/function-config.test.js
  test/config/type/promise/promise-config.test.js
  test/entry/defaults-empty/entry-single-arg.test.js
  test/node/node.test.js
  test/output/named-bundles/output-named-bundles.test.js
  test/utils/test-utils.js
Labels: PR: CI-ok, PR: reviewed-approved

#1205 Upgrade yeoman in generators/utils, slight generator error handling changes
  packages/generators/package-lock.json
  packages/generators/package.json
  packages/init/package-lock.json
  packages/utils/modify-config-helper.ts
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: PR: CI-ok, PR: reviewed-approved

#1207 chore: test cases for --max-old-space-size passed along with --node-args flag
  test/node/node.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1209 init generator: read name property from package.json
  packages/utils/.eslintrc
  packages/utils/modify-config-helper.ts
Labels: PR: CI-ok, PR: reviewed-approved

#1206 feat: adds standard output flag
  lib/groups/StatsGroup.js
  lib/utils/Compiler.js
  lib/utils/CompilerOutput.js
  lib/utils/cli-flags.js
  test/help/__snapshots__/help-single-arg.test.js.snap
  test/standard/src/index.js
  test/standard/standard.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1147 tests(info): add tests for info package arguments/flags
  test/info/info-help.test.js
  test/info/info-multi-args.test.js
  test/info/info-output.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1201 chore: it restores inquirer for prompting external commands
  lib/commands/external.js
  package-lock.json
  package.json
Labels: PR: CI-not-ok, PR: reviewed-approved

#1140 chore(lib): refactored lib utils and groups
  lib/groups/AdvancedGroup.js
  lib/groups/BasicGroup.js
  lib/utils/Compiler.js
  lib/utils/interactive.js
  lib/utils/zero-config.js
Labels: PR: CI-ok, PR: reviewed-approved

#1214 feat: test case for passing in unknown flags
  test/default/default.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1221 fix(cli): fix file resolution inside group helper
  lib/groups/ZeroConfigGroup.js
  lib/utils/development-config.js
  lib/utils/production-config.js
  lib/utils/zero-config.js
  lib/webpack-cli.js
  packages/generators/__tests__/add-generator.test.js
  test/ZeroConfigGroup.test.js
  test/env/prod/index.js
  test/env/prod/prod.test.js
  test/env/prod/webpack.config.js
  test/output/named-bundles/output-named-bundles.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1223 docs(cli): changed README to notify the beta version
  README.md
  lib/utils/cli-flags.js
  packages/init/README.md
  test/help/__snapshots__/help-single-arg.test.js.snap
  test/help/help-commands.test.js
  test/help/help-multi-args.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1224 chore(cli): updated changelog of v3
  CHANGELOG_v3.md
Labels: PR: CI-ok, PR: reviewed-approved

#1228 fix(init): fix the invalid package name
  INIT.md
  README.md
  lib/webpack-cli.js
  packages/README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1229 chore(generator): remove transpiled tests
  packages/generators/__tests__/add-generator.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1226 docs(templates): Branding guide violation fix
  packages/generators/templates/template.html
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1233 tests(generator): enable init generator test
  packages/generators/__tests__/init-generator.test.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1234 tests(loader-generator): add tests for loader generator
  package-lock.json
  package.json
  packages/generators/__tests__/loader-generator.test.ts
Labels: PR: CI-ok, PR: reviewed-approved

#1232 tests(sourcemap): fix flaky stats statement and patch versions
  package-lock.json
  test/source-map/object/source-map-object.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1235 tests(generator): add tests for plugin generator
  packages/generators/__tests__/add-generator.test.ts
  packages/generators/__tests__/plugin-generator.test.ts
Labels: PR: CI-ok, PR: reviewed-approved

#1237 chore: post refactor CLI
  .gitignore
  packages/cli/bin/cli.js
  packages/cli/package.json
  packages/webpack-cli/.eslintrc.js
  packages/webpack-cli/.gitignore
  packages/webpack-cli/README.md
  packages/webpack-cli/__tests__/GroupHelper.test.js
  packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
  packages/webpack-cli/__tests__/command/external.test.js
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/commands/external.js
  packages/webpack-cli/lib/groups/AdvancedGroup.js
  packages/webpack-cli/lib/groups/BasicGroup.js
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/groups/OutputGroup.js
  packages/webpack-cli/lib/groups/StatsGroup.js
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/CompilerOutput.js
  packages/webpack-cli/lib/utils/GroupHelper.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/commands.js
  packages/webpack-cli/lib/utils/core-flags.js
  packages/webpack-cli/lib/utils/development-config.js
  packages/webpack-cli/lib/utils/interactive.js
  packages/webpack-cli/lib/utils/logger.js
  packages/webpack-cli/lib/utils/parse-args.js
  packages/webpack-cli/lib/utils/process-log.js
  packages/webpack-cli/lib/utils/production-config.js
  packages/webpack-cli/lib/utils/zero-config.js
  packages/webpack-cli/lib/webpack-cli.js
  packages/webpack-cli/package.json
  test/info/info-help.test.js
  test/node/node.test.js
  test/utils/test-utils.js
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved

#1238 feat: add progress bar for progress flag
  packages/webpack-cli/lib/utils/Compiler.js
Labels: PR: CI-ok, PR: reviewed-approved

#1244 fix: correct supported arguments & commands link in README
  README.md
Labels: PR: CI-ok, PR: small, PR: unreviewed

#1252 chore: ignore package-lock.json and remove its references
  .github/CONTRIBUTING.md
  .gitignore
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1254 tests(output): add test case for defaults flag
  test/output/defaults/index.js
  test/output/defaults/output-defaults.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1253 feat(webpack-cli): added mode argument
  .babelrc
  .gitignore
  package.json
  packages/webpack-cli/README.md
  packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/help/__snapshots__/help-single-arg.test.js.snap
  test/mode/dev/dev.test.js
  test/mode/dev/src/index.js
  test/mode/prod/prod.test.js
  test/mode/prod/src/index.js
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved

#1256 chore: update Bug_report & Feature_request Templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: PR: CI-ok, PR: reviewed-approved

#1246 Fixing the typos and grammatical errors in Readme files
  SECURITY.md
  packages/webpack-scaffold/README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1250 Fix loader-generator and plugin-generator tests
  packages/generators/__tests__/loader-generator.test.ts
  packages/generators/__tests__/plugin-generator.test.ts
  packages/generators/src/addon-generator.ts
  packages/generators/src/loader-generator.ts
  packages/generators/src/plugin-generator.ts
  packages/generators/templates/addon-package.json.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1236 tests(generator): enhance init generator tests
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/package.json
Labels: PR: CI-ok, PR: reviewed-approved

#1257 chore: changelogs aligned
  CHANGELOG.md
  packages/webpack-cli/CHANGELOG.md
Labels: PR: unreviewed

#1259 chore(logger): fix npm files to publish
  packages/logger/package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1260 chore: added webpack 4 to the matrix and changed tests
  .github/workflows/nodejs.yml
  package.json
  test/config/empty/empty-config.test.js
  test/entry/defaults-empty/entry-single-arg.test.js
  test/json/json.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1255 feat: create a cli executer
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/runner.js
  packages/webpack-cli/lib/utils/cli-executer.js
Labels: PR: CI-ok, PR: reviewed-approved

#1262 docs: enhance CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: PR: CI-ok, PR: reviewed-approved

#1266 docs: fix links to angular commit guidelines
  .github/CONTRIBUTING.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1265 fix: yarn.lock diff on setup
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1267 fix: 🐛 add git-cz as a dev dependency
  package.json
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1272 chore: 🤖 remove stale entries from root package.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1273 docs: ✏️ fix init command in README
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1258 tests: fix folder structure, add more default tests
  test/defaults/a.js
  test/defaults/index.js
  test/defaults/output-defaults.test.js
  test/defaults/with-config-and-entry/default-with-config.test.js
  test/defaults/with-config-and-entry/index.js
  test/defaults/with-config-and-entry/webpack.config.js
  test/defaults/without-config-and-entry/default-without-config.test.js
  test/unknown/unknown.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1269 fix: handle promise rejection happening with cli-executor
  packages/webpack-cli/lib/utils/cli-executer.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
