Repository webpack/webpack-cli, pull requests merged in 2020-08, with the labels that each got.

#1715 feat: support multiple env params
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/config/type/function-with-env/a.js
  test/config/type/function-with-env/function-with-env.test.js
  test/config/type/function-with-env/webpack.config.js
Labels: PR: reviewed-approved

#1717 fix: generated plugin template
  packages/generate-plugin/templates/src/_index.js.tpl
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved, PR: small

#1718 tests: add tests for entry in config
  test/entry/config-entry/entry-with-index/entry-with-config.test.js
  test/entry/config-entry/entry-with-index/src/app.js
  test/entry/config-entry/entry-with-index/src/index.js
  test/entry/config-entry/entry-with-index/src/print.js
  test/entry/config-entry/entry-with-index/webpack.config.js
Labels: PR: reviewed-approved

#1723 fix: rename sourcemap flag to devtool
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/groups/BasicGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/devtool/array/index.js
  test/devtool/array/source-map-array.test.js
  test/devtool/array/webpack.config.js
  test/devtool/object/index.js
  test/devtool/object/source-map-object.test.js
  test/devtool/object/webpack.eval.config.js
  test/devtool/object/webpack.source.config.js
Labels: PR: reviewed-approved

#1721 fix: supply argv to config with functions
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/webpack-cli.js
  test/config/type/function-with-argv/a.js
  test/config/type/function-with-argv/function-with-argv.test.js
  test/config/type/function-with-argv/webpack.config.js
Labels: PR: review-outdated

#1720 fix: generated loader template
  packages/generate-loader/templates/src/_index.js.tpl
  packages/generators/__tests__/loader-generator.test.ts
  test/loader/loader.test.js
Labels: PR: reviewed-approved, PR: small

#1732 fix: conditionally install terser-webpack-plugin for webpack@next
  .github/workflows/nodejs.yml
  test/core-flags/optimization-flags.test.js
Labels: PR: reviewed-approved, PR: small

#1725 chore: rephrase test descriptions
  test/help/help-single-arg.test.js
  test/info/info-help.test.js
Labels: PR: reviewed-approved, PR: small, PR: unreviewed

#1727 feat: add support for .cjs config
  packages/webpack-cli/lib/groups/ConfigGroup.js
  test/config-format/commonjs/commonjs.test.js
  test/config-format/commonjs/main.js
  test/config-format/commonjs/webpack.config.cjs
  test/config-format/typescript/main.ts
  test/config-format/typescript/package.json
  test/config-format/typescript/typescript.test.js
  test/config-format/typescript/webpack.config.ts
Labels: PR: reviewed-approved

#1734 chore: revert adding terser plugin in webpack@next
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small

#1694 fix(serve): supplying help or version as an arg should throw
  packages/serve/src/index.ts
  test/help/help-commands.test.js
  test/serve/basic/serve-basic.test.js
Labels: PR: reviewed-approved

#1735 tests: remove --module-rules-options instances
  test/core-flags/module-flags.test.js
Labels: PR: reviewed-approved, PR: small

#1740 chore: use console for logging
  packages/serve/src/index.ts
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/utils/logger.js
  test/hot/hot-flag.test.js
  test/no-hot/no-hot.test.js
Labels: PR: reviewed-approved

#1742 chore(deps): update dependencies
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1737 fix(info): throw an error if help or version is passed as an arg
  packages/info/src/index.ts
  test/info/info-help.test.js
  test/info/info-unknown.test.js
Labels: PR: reviewed-approved, PR: small

#1745 docs(info): remove old flags
  packages/info/README.md
Labels: PR: reviewed-approved

#1744 chore: remove --mode flag validation
  packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  test/mode/mode-single-arg/mode-single-arg.test.js
  test/mode/mode-single-arg/src/index.js
  test/mode/mode-single-arg/src/main.js
Labels: PR: reviewed-approved

#1749 tests: add tests for coffeescript config
  test/config-format/coffee/coffee.test.js
  test/config-format/coffee/main.js
  test/config-format/coffee/package.json
  test/config-format/coffee/webpack.config.coffee
Labels: PR: reviewed-approved

#1741 perf: do not spawn new process for running webpack
  packages/webpack-cli/README.md
  packages/webpack-cli/__tests__/cli-executer.test.js
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/cli-executer.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/parse-node-args.js
  packages/webpack-cli/lib/webpack-cli.js
  test/node/node.test.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#1712 feat: serve integration
  packages/serve/package.json
  packages/serve/src/index.ts
  packages/serve/src/startDevServer.ts
  packages/webpack-cli/__tests__/serve/index.js
  packages/webpack-cli/__tests__/serve/serve.test.js
  packages/webpack-cli/__tests__/serve/webpack.config.js
  packages/webpack-cli/package.json
  test/serve/basic/serve-basic.test.js
  test/serve/with-custom-port/serve-custom-config.test.js
Labels: PR: reviewed-approved

#1754 chore: cliExecuter consumes runCLI
  packages/webpack-cli/__tests__/cli-executer.test.js
  packages/webpack-cli/lib/runner.js
  packages/webpack-cli/lib/utils/cli-executer.js
Labels: PR: reviewed-approved

#1755 fix: use appropriate exit codes
  README.md
  packages/package-utils/__tests__/packageUtils.test.ts
  packages/package-utils/src/packageUtils.ts
  packages/utils/src/modify-config-helper.ts
  packages/utils/src/npm-packages-exists.ts
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/utils/process-log.js
Labels: PR: reviewed-approved

#1753 feat: add --config-name flag
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/config-name/config-name.test.js
  test/config-name/src/first.js
  test/config-name/src/second.js
  test/config-name/src/third.js
  test/config-name/webpack.config.js
Labels: PR: reviewed-approved

#1736 tests: loader's tests for errors and warnings
  .gitignore
  packages/webpack-cli/lib/utils/Compiler.js
  test/loader/error-test/loader-error.test.js
  test/loader/error-test/package.json
  test/loader/error-test/src/index.ts
  test/loader/error-test/webpack.config.js
  test/loader/warning-test/loader-warning.test.js
  test/loader/warning-test/my-loader.js
  test/loader/warning-test/src/main.js
  test/loader/warning-test/webpack.config.js
Labels: PR: reviewed-approved

#1747 fix: allow unknown files to use default require as fallback
  packages/webpack-cli/lib/groups/ConfigGroup.js
Labels: PR: reviewed-approved

#1760 fix: throw err when supplied config is absent
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/GroupHelper.js
  packages/webpack-cli/lib/utils/errors/ConfigError.js
  packages/webpack-cli/lib/utils/errors/MergeError.js
  packages/webpack-cli/lib/utils/interactive.js
  packages/webpack-cli/lib/webpack-cli.js
  test/config/absent/a.js
  test/config/absent/config-absent.test.js
  test/config/absent/webpack.config-absent.js
Labels: PR: reviewed-approved

#1751 tests(info): --output flag handles invalid arg
  test/info/info-output.test.js
Labels: PR: reviewed-approved, PR: small

#1768 feat: add support for merging multiple configurations
  packages/webpack-cli/README.md
  packages/webpack-cli/__tests__/ConfigGroup/ConfigGroup.test.js
  packages/webpack-cli/__tests__/ConfigGroup/webpack.config.cjs
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/help/help-flags.test.js
  test/merge/config-absent/merge-config-absent.test.js
  test/merge/config/merge-config.test.js
Labels: PR: reviewed-approved

#1649 fix(serve): merge CLI and devServer options correctly
  packages/serve/__tests__/__snapshots__/parseArgs.test.ts.snap
  packages/serve/__tests__/__snapshots__/startDevServer.test.ts.snap
  packages/serve/__tests__/args-to-camel-case.test.ts
  packages/serve/__tests__/createConfig.test.ts
  packages/serve/__tests__/getDevServerOptions.test.ts
  packages/serve/__tests__/mergeOptions.test.ts
  packages/serve/__tests__/parseArgs.test.ts
  packages/serve/__tests__/startDevServer.test.ts
  packages/serve/src/args-to-camel-case.ts
  packages/serve/src/createConfig.ts
  packages/serve/src/getDevServerOptions.ts
  packages/serve/src/index.ts
  packages/serve/src/mergeOptions.ts
  packages/serve/src/parseArgs.ts
  packages/serve/src/startDevServer.ts
  packages/serve/src/types.ts
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/lib/utils/arg-parser.js
Labels: PR: reviewed-approved

#1770 tests: add config resolving tests for ConfigGroup
  packages/webpack-cli/__tests__/ConfigGroup/ConfigGroup.test.js
  packages/webpack-cli/__tests__/ConfigGroup/webpack.config1.cjs
  packages/webpack-cli/__tests__/ConfigGroup/webpack.config2.cjs
  packages/webpack-cli/__tests__/ConfigGroup/webpack.promise.config.cjs
Labels: PR: reviewed-approved

#1772 fix: use compiler.apply for Progress Plugin
  packages/webpack-cli/lib/utils/Compiler.js
  test/progress/progress-flag.test.js
Labels: PR: reviewed-approved

#1777 tests: ensure progress plugin is applied only once
  test/progress/index.js
  test/progress/progress-flag.test.js
  test/progress/src/index.js
  test/progress/webpack.progress.config.js
Labels: PR: reviewed-approved

#1775 feat: allow using cjs as default config
  packages/webpack-cli/lib/groups/ConfigGroup.js
  test/config/defaults/basic-config/default-js-config.test.js
  test/config/defaults/basic-config/index.js
  test/config/defaults/basic-config/webpack.config.js
  test/config/defaults/cjs-config/default-cjs-config.test.js
  test/config/defaults/cjs-config/index.js
  test/config/defaults/cjs-config/webpack.config.cjs
Labels: PR: reviewed-approved
