Repository webpack/webpack-cli, pull requests merged in 2020-09, with the labels that each got.

#1779 fix: compatibility with webpack@next
  packages/webpack-cli/README.md
  test/core-flags/cache-flags.test.js
  test/core-flags/output-flags.test.js
Labels: PR: reviewed-approved

#1766 chore: add commitlint github action
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small

#1748 refactor: use logger
  packages/generators/src/addon-generator.ts
  packages/generators/src/init-generator.ts
  packages/info/src/index.ts
  packages/migrate/package.json
  packages/migrate/src/index.ts
  packages/migrate/src/removeDeprecatedPlugins/removeDeprecatedPlugins.ts
  packages/utils/__tests__/run-prettier.test.ts
  packages/utils/package.json
  packages/utils/src/modify-config-helper.ts
  packages/utils/src/recursive-parser.ts
  packages/utils/src/resolve-packages.ts
  packages/utils/src/run-prettier.ts
  packages/utils/src/scaffold.ts
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/groups/BasicGroup.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/utils/cli-executer.js
  packages/webpack-cli/lib/utils/logger.js
  test/entry/flag-entry/entry-with-flag.test.js
  test/migrate/config/migrate-config.test.js
Labels: PR: reviewed-approved

#1787 tests(plugin & loader): refactor tests
  .eslintignore
  .gitignore
  jest.config.js
  lib/test/loader/error-test/src/index.d.ts
  package.json
  test/loader/loader.test.js
  test/migrate/config/migrate-config.test.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved

#1789 tests: for snapshot config related flags
  packages/webpack-cli/README.md
  test/core-flags/snapshot-flags.test.js
Labels: PR: reviewed-approved

#1790 refactor: remove duplicate invocation
  packages/webpack-cli/lib/groups/HelpGroup.js
Labels: PR: reviewed-approved, PR: small

#1793 chore: add network timeout in yarnrc
  .yarnrc
Labels: PR: reviewed-approved, PR: small

#1791 docs(init): minor typographical fix
  packages/init/README.md
Labels: PR: reviewed-approved, PR: small

#1801 fix: ci for webpack@beta.30
  packages/webpack-cli/__tests__/serve/serve.test.js
  packages/webpack-cli/__tests__/serve/webpack.config.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  test/config-name/config-name.test.js
  test/config/defaults/basic-config/default-js-config.test.js
  test/config/defaults/cjs-config/default-cjs-config.test.js
  test/config/multiple/multiple-config.test.js
  test/core-flags/output-flags.test.js
  test/core-flags/stats-flags.test.js
  test/serve/basic/serve-basic.test.js
  test/serve/basic/webpack.config.js
  test/serve/with-custom-port/serve-custom-config.test.js
  test/serve/with-custom-port/webpack.config.js
  test/stats/cli-flags/stats.test.js
  test/target/flag-test/target-flag.test.js
  test/utils/cli-plugin-test/plugin.test.js
  test/utils/test-utils.js
  test/utils/webpack-cli-test-plugin.js
  test/zero-config/entry-present/zero-config.test.js
Labels: PR: reviewed-approved, PR: small

#1800 misc(remove code): remove unused code
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/CompilerOutput.js
Labels: PR: reviewed-approved, PR: small

#1803 chore: remove temporaray files created during testing
  lib/test/loader/error-test/src/index.d.ts
Labels: PR: reviewed-approved, PR: small

#1799 feat: allow multiple targets
  packages/serve/__tests__/__snapshots__/parseArgs.test.ts.snap
  packages/serve/__tests__/parseArgs.test.ts
  packages/webpack-cli/lib/utils/cli-flags.js
  test/target/flag-test/target-flag.test.js
Labels: PR: reviewed-approved

#1806 tests: add test cases for resolve.fallback option
  test/core-flags/module-flags.test.js
  test/core-flags/resolve-flags.test.js
Labels: PR: reviewed-approved

#1808 tests: add case for stats summary preset for webpack 5
  test/stats/cli-flags/stats.test.js
Labels: PR: reviewed-approved, PR: small

#1805 feat: generate changelog and copy old CHANGEFILE
  CHANGELOG.md
  CHANGELOG_v3.md
  build/changelog-generator/index.js
  build/changelog-generator/templates/commit.hbs
  build/changelog-generator/templates/header.hbs
  build/changelog-generator/templates/template.hbs
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1812 chore: beta v9
  CHANGELOG.md
  package.json
  packages/webpack-cli/package.json
Labels: PR: unreviewed

#1816 fix: declare default commands as optional peer dependencies
  packages/package-utils/package.json
Labels: PR: reviewed-approved

#1813 refactor: migrate to async/await
  packages/migrate/src/index.ts
Labels: PR: reviewed-approved

#1804 fix: show warning if bail and watch are used together
  packages/webpack-cli/lib/groups/BasicGroup.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/warnings/bailAndWatchWarning.js
  test/bail/bail-and-watch-warning.test.js
  test/bail/multi-webpack.config.js
  test/bail/single-webpack.config.js
  test/bail/src/first.js
  test/bail/src/second.js
  test/bail/third-webpack.config.js
Labels: PR: reviewed-approved

#1811 refactor: config group to pure function and move away from group design
  packages/serve/__tests__/__snapshots__/parseArgs.test.ts.snap
  packages/webpack-cli/__tests__/ConfigGroup/ConfigGroup.test.js
  packages/webpack-cli/__tests__/GroupHelper.test.js
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/utils/GroupHelper.js
  packages/webpack-cli/lib/utils/arg-utils.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
  test/config/type/function-with-argv/function-with-argv.test.js
Labels: PR: reviewed-approved

#1819 feat(changelog): use lerna
  build/changelog-generator/index.js
  build/changelog-generator/templates/commit.hbs
  build/changelog-generator/templates/header.hbs
  build/changelog-generator/templates/template.hbs
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1821 refactor: remove redundant arg computation in config resolver
  packages/webpack-cli/__tests__/ConfigGroup/ConfigGroup.test.js
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#1823 chore: bump all versions
  packages/generate-loader/package.json
  packages/generate-plugin/package.json
  packages/generators/package.json
  packages/info/package.json
  packages/init/package.json
  packages/migrate/package.json
  packages/package-utils/package.json
  packages/serve/package.json
  packages/utils/package.json
  packages/webpack-cli/package.json
  packages/webpack-scaffold/package.json
Labels: PR: reviewed-approved

#1820 refactor: move zero-config from group design
  packages/serve/__tests__/__snapshots__/parseArgs.test.ts.snap
  packages/webpack-cli/__tests__/resolveMode.test.js
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  packages/webpack-cli/lib/groups/resolveMode.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
  test/mode/mode-single-arg/src/index.js
  test/mode/mode-with-config/mode-with-config.test.js
  test/mode/mode-with-config/webpack.config2.js
Labels: PR: reviewed-approved

#1826 docs: add resolve.fallback config related flags
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#1824 fix: mode behaviour
  packages/webpack-cli/__tests__/resolveMode.test.js
  packages/webpack-cli/lib/groups/resolveMode.js
  packages/webpack-cli/lib/webpack-cli.js
  test/mode/mode-single-arg/mode-single-arg.test.js
  test/mode/mode-with-config/mode-with-config.test.js
  test/mode/mode-with-config/webpack.config3.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#1829 chore: make prettier peer dependency meta
  packages/utils/package.json
  packages/utils/src/run-prettier.ts
  yarn.lock
Labels: PR: reviewed-approved

#1831 migrate stats group
  packages/webpack-cli/__tests__/StatsGroup.test.js
  packages/webpack-cli/__tests__/resolveStats.js
  packages/webpack-cli/lib/groups/StatsGroup.js
  packages/webpack-cli/lib/groups/resolveStats.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#1830 chore: remove group definitions of removed groups
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#1834 chore: remove lodash from direct dependencies
  packages/generators/package.json
  packages/generators/src/loader-generator.ts
  packages/generators/src/plugin-generator.ts
  packages/generators/src/utils/helpers.ts
  packages/migrate/__testfixtures__/failing.js
  packages/migrate/package.json
  packages/migrate/src/loaderOptionsPlugin/loaderOptionsPlugin.ts
  yarn.lock
Labels: PR: reviewed-approved

#1827 fix: check webpack installation before running cli
  packages/package-utils/package.json
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved

#1825 fix: add necessary peerDependencies
  packages/generators/package.json
  packages/init/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, PR: small

#1846 tests: optimization-flags test updates for webpack-rc.2
  test/core-flags/optimization-flags.test.js
Labels: PR: reviewed-approved

#1832 migrate output group
  packages/webpack-cli/__tests__/OutputGroup.test.js
  packages/webpack-cli/__tests__/resolveOutput.test.js
  packages/webpack-cli/lib/groups/OutputGroup.js
  packages/webpack-cli/lib/groups/resolveOutput.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/merge-strategies.js
  packages/webpack-cli/lib/webpack-cli.js
  test/output/named-bundles/output-named-bundles.test.js
Labels: PR: reviewed-approved

#1845 docs: update readme
  README.md
Labels: PR: reviewed-approved, PR: small
