Repository webpack/webpack-cli, pull requests merged in 2020-06, with the labels that each got.

#1587 fix(webpack-cli): remove invalid stats warning with json flag
  packages/webpack-cli/__tests__/StatsGroup.test.js
  packages/webpack-cli/lib/groups/StatsGroup.js
  test/json/json.test.js
Labels: PR: review-outdated

#1606 chore: remove plugin TODO
  packages/webpack-cli/lib/utils/GroupHelper.js
Labels: PR: reviewed-approved

#1590 feat(init): add features and refactor
  packages/init/src/index.ts
  packages/utils/src/modify-config-helper.ts
  packages/utils/src/scaffold.ts
  test/init/force/init-force.test.js
Labels: PR: reviewed-approved

#1604 tests: add test for progress flag
  packages/webpack-cli/lib/utils/Compiler.js
  test/progress/progress-flag.test.js
  test/progress/src/index.js
Labels: PR: reviewed-approved

#1614 chore: increase jest.setTimeout
  setupTest.js
Labels: PR: reviewed-approved, PR: small

#1610 feat(cli-executer): validate user input
  packages/webpack-cli/lib/utils/cli-executer.js
Labels: PR: review-outdated, PR: small

#1598 feat: 🎸 add support for env flag
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/config/type/function-with-env/a.js
  test/config/type/function-with-env/function-with-env.test.js
  test/config/type/function-with-env/webpack.config.js
Labels: PR: reviewed-approved

#1613 feat: allow only specified negated flags
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/lib/utils/arg-parser.js
Labels: PR: reviewed-approved

#1609 feat: add init to webpack-cli
  packages/webpack-cli/__tests__/init.test.js
  packages/webpack-cli/package.json
Labels: PR: review-outdated, PR: small

#1624 tests: create WebpackCLITest Plugin
  test/utils/cli-plugin-test/main.js
  test/utils/cli-plugin-test/plugin.test.js
  test/utils/cli-plugin-test/webpack.config.js
  test/utils/webpack-cli-test-plugin.js
Labels: PR: reviewed-approved

#1591 feat(webpack-cli): add --no-hot flag
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/utils/cli-flags.js
  test/no-hot/no-hot.test.js
  test/no-hot/src/index.js
  test/no-hot/webpack.config.js
  test/serve/basic/serve-basic.test.js
  test/serve/with-custom-port/serve-custom-config.test.js
Labels: PR: reviewed-approved

#1628 tests: add tests for --hot flag
  test/hot/hot-flag.test.js
  test/hot/index.js
  test/hot/webpack.config.js
Labels: PR: reviewed-approved

#1631 tests: add test for multiple config in dotfolder
  test/config/multiple/.webpack/webpack.config.dev.js
  test/config/multiple/.webpack/webpack.config.prod.js
  test/config/multiple/index.js
  test/config/multiple/multiple-config.test.js
Labels: PR: reviewed-approved

#1636 chore: upgrades typescript to the latest
  package.json
  packages/utils/src/modify-config-helper.ts
  yarn.lock
Labels: PR: reviewed-approved

#1548 tests: add tests for --target flag
  packages/webpack-cli/__tests__/AdvancedGroup.test.js
  test/target/flag-test/index.js
  test/target/flag-test/target-flag.test.js
  test/target/flag-test/webpack.config.js
Labels: PR: reviewed-approved

#1635 chore: remove redundant timeout definations
  packages/webpack-cli/__tests__/init.test.js
  test/init/language/css/init-language-css.test.js
  test/init/language/js/init-language-js.test.js
Labels: PR: reviewed-approved

#1644 feat: add aliases to all available commands
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#1641 tests: add tests for prefetch flag
  test/prefetch/prefetch.test.js
  test/prefetch/src/index.js
  test/prefetch/src/p.js
  test/prefetch/webpack.config.js
Labels: PR: review-outdated

#1647 feat: show up cli flag aliases with webpack help <arg>
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/help/help-commands.test.js
  test/help/help-flags.test.js
  test/help/help-multi-args.test.js
  test/info/info-help.test.js
Labels: PR: reviewed-approved, PR: small

#1627 feat(webpack-cli): allow multiple types for --stats
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/groups/StatsGroup.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/stats/stats.test.js
  test/stats/webpack.config.js
Labels: PR: reviewed-approved

#1652 feat: parse Number flags
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/lib/utils/arg-parser.js
Labels: PR: reviewed-approved

#1651 tests: add stats with config tests
  test/stats/cli-flags/.gitignore
  test/stats/cli-flags/index.js
  test/stats/cli-flags/package.json
  test/stats/cli-flags/stats.test.js
  test/stats/cli-flags/webpack.config.js
  test/stats/config/.gitignore
  test/stats/config/index.js
  test/stats/config/package.json
  test/stats/config/stats.test.js
  test/stats/config/webpack.config.js
Labels: PR: reviewed-approved

#1654 feat(webpack-cli): add --no-stats flag
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/groups/StatsGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/no-stats/with-config/a.js
  test/no-stats/with-config/no-stats-with-config.test.js
  test/no-stats/with-config/webpack.config.js
  test/no-stats/with-flags/main.js
  test/no-stats/with-flags/no-stats.test.js
  test/no-stats/with-flags/webpack.config.js
Labels: PR: reviewed-approved

#1656 tests: update stats test case assertion
  test/no-stats/with-config/main.js
  test/stats/cli-flags/stats.test.js
Labels: PR: reviewed-approved, PR: small

#1650 fix: prevent info from running unnecessarily
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/webpack-cli.js
  test/serve/basic/serve-basic.test.js
Labels: PR: reviewed-approved, PR: small, Semver: patch 🔧

#1379 docs: improving init and migrate
  INIT.md
  MIGRATE.md
Labels: PR: reviewed-approved

#1637 feat: add support for none config in dotfolder
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/webpack-cli.js
  test/config/multiple/all/.webpack/webpack.config.dev.js
  test/config/multiple/all/.webpack/webpack.config.none.js
  test/config/multiple/all/.webpack/webpack.config.prod.js
  test/config/multiple/all/index.js
  test/config/multiple/all/multiple-config.test.js
  test/config/multiple/multiple-location/.webpack/webpack.config.development.js
  test/config/multiple/multiple-location/index.js
  test/config/multiple/multiple-location/multiple-location-config.test.js
  test/config/multiple/multiple-location/webpack.config.development.js
  test/config/multiple/multiple-location/webpack.config.js
  test/config/multiple/none and dev/.webpack/webpack.config.dev.js
  test/config/multiple/none and dev/.webpack/webpack.config.none.js
  test/config/multiple/none and dev/dev-none-config.test.js
  test/config/multiple/none and dev/index.js
  test/config/multiple/with-mode/index.js
  test/config/multiple/with-mode/multiple-config.test.js
  test/config/multiple/with-mode/webpack.config.development.js
  test/config/multiple/with-mode/webpack.config.none.js
  test/config/multiple/with-mode/webpack.config.production.js
Labels: PR: reviewed-approved
