Repository webpack/webpack-cli, pull requests merged in 2020-01, with the labels that each got.

#1168 fix: various tests are now working
  lib/groups/advanced.js
  lib/groups/config.js
  lib/groups/output.js
  lib/utils/cli-flags.js
  lib/utils/group-helper.js
  lib/webpack-cli.js
  package.json
  test/config-lookup/dotfolder-single/dotfolder-single.test.js
  test/config/type/promise/promise-config.test.js
  test/config/type/promise/webpack.config.js
  test/entry/defaults-index/entry-multi-args.test.js
  test/env/object/object-env.test.js
  test/global/global.test.js
  test/json/json.test.js
  test/merge/defaults/merge-defaults.test.js
  test/output/defaults/output-defaults.test.js
Labels: PR: CI-ok, PR: unreviewed

#1148 chore: update dependences
  package.json
Labels: PR: CI-ok, PR: review-outdated, PR: small

#1150 chore(actions): add webpack version
  .github/workflows/nodejs.yml
Labels: PR: CI-ok, PR: review-outdated, PR: small

#1170 fix: update webpack installation
  .github/workflows/nodejs.yml
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1171 fix: remove for now the default value of the target
  lib/utils/cli-flags.js
  lib/utils/compiler.js
  package-lock.json
  package.json
  test/json/json.test.js
  test/target/node/main.js
  test/target/node/new.js
  test/target/node/node-test.test.js
  test/target/node/webpack.config.js
Labels: PR: CI-ok, PR: unreviewed

#1172 chore(deps): Updated terser-webpack-plugin
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#1174 fix(serve): handle serve args as an array
  lib/webpack-cli.js
  packages/serve/index.ts
  packages/serve/package-lock.json
  test/serve/serve-basic.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1122 chore: Minor code refactor adhering to ES6 semantics
  lib/commands/external.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1176 tests(serve): add tests for args to camel case util
  packages/serve/args-to-camel-case.ts
  test/serve/args-to-camel-case.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1175 info package fixes, slight refactor, and tests
  .gitignore
  packages/info/index.ts
  test/info/info-basic.test.js
  test/info/shim/node_modules/@webpack-cli/info/index.js
Labels: PR: CI-ok, PR: reviewed-approved

#1177 Add init-generator test for yeoman generator
  package-lock.json
  package.json
  packages/generators/__tests__/init-generator.test.js
  packages/generators/init-generator.ts
Labels: PR: CI-ok, PR: reviewed-approved

#1141 feat: help for core flags
  lib/groups/help.js
  lib/utils/cli-flags.js
  lib/utils/commands.js
  lib/utils/core-flags.js
  lib/webpack-cli.js
  packages/generate-loader/package-lock.json
  packages/generate-plugin/package-lock.json
  packages/init/package-lock.json
  packages/migrate/package-lock.json
  packages/serve/package-lock.json
  packages/webpack-scaffold/package-lock.json
  test/help/__snapshots__/help-single-arg.test.js.snap
  test/help/help-multi-args.test.js
  test/help/help-single-arg.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1155 docs(create): migrate init package docs
  .cz-config.js
  INIT.md
  README.md
  packages/README.md
  packages/init/README.md
  test/version/version-multi-args.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1179 chore: better logger
  cli.js
  lib/bootstrap.js
  lib/commands/external.js
  lib/groups/advanced.js
  lib/utils/compiler.js
  lib/utils/logger.js
  lib/utils/process-log.js
Labels: PR: CI-ok, PR: reviewed-approved

#1153 fix(create): add default sw in create template
  packages/generators/init-generator.ts
  packages/generators/templates/sw.js
Labels: PR: CI-ok, PR: reviewed-approved

#1178 chore: Updated CLI flags info with additional links
  lib/utils/cli-flags.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1184 test(help): add more tests to help
  test/help/help-commands.test.js
  test/help/help-flags.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1183 chore: Minor typographical fixes
  lib/utils/commands.js
  lib/utils/core-flags.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1159 fix(create): handle create package errors gracefully
  packages/init/index.ts
  packages/init/package-lock.json
  packages/utils/modify-config-helper.ts
Labels: PR: CI-ok, PR: reviewed-approved

#1194 Move jest to dev-deps
  packages/utils/package-lock.json
  packages/utils/package.json
Labels: PR: CI-ok, PR: reviewed-approved

#1195 Allow to pass flags to node.js
  .travis.yml
  azure-pipelines-template.yml
  lib/bootstrap.js
  lib/utils/cli-flags.js
  lib/utils/parse-args.js
  package-lock.json
  package.json
  test/help/__snapshots__/help-single-arg.test.js.snap
  test/node/a.js
  test/node/bootstrap.js
  test/node/bootstrap2.js
  test/node/node.test.js
  test/node/webpack.config.js
Labels: PR: CI-ok, PR: reviewed-approved

#1182 chore(ci): remove node 8 from the CI
  .eslintrc.js
  .github/workflows/nodejs.yml
  azure-pipelines-template.yml
  bin/cli.js
  lib/.eslintrc.js
  lib/bootstrap.js
  lib/commands/external.js
  lib/groups/advanced.js
  lib/groups/basic.js
  lib/utils/group-helper.js
  package-lock.json
  package.json
  packages/generators/__tests__/init-generator.test.js
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/package-lock.json
  packages/generators/package.json
  packages/serve/package-lock.json
  smoketests/watch/watch.array.smoketest.js
  smoketests/watch/watch.single.smoketest.js
  test/utils/test-utils.js
Labels: PR: CI-ok, PR: unreviewed

#1193 fix: ci
  azure-pipelines.yml
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved

#1197 chore: Added test case for providing unknown flags along with --node-args
  test/node/node.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
