Repository webpack/webpack-cli, pull requests merged in 2020-07, with the labels that each got.

#1655 feat[utils]: opt to use config schema from core
  package.json
  packages/utils/package.json
  packages/utils/src/isWebpack5.ts
  packages/utils/src/prop-types.ts
  yarn.lock
Labels: PR: reviewed-approved

#1661 fix: show version information for plugin and loader subcommands
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/commands.js
  test/version/version-external-packages.test.js
Labels: PR: review-outdated

#1664 feat: support command aliases with webpack-cli version
  packages/webpack-cli/lib/groups/HelpGroup.js
  test/version/version-external-packages.test.js
Labels: PR: reviewed-approved, PR: small

#1665 chore: increase jest timeout
  setupTest.js
Labels: PR: reviewed-approved, PR: small

#1667 feat: add scripts to cleanup stale test data
  .gitignore
  jest.config.js
  scripts/cleanupTest.js
  scripts/prepareSuite.js
  scripts/utils.js
Labels: PR: reviewed-approved

#1666 fix: promise support in config
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/webpack-cli.js
  test/config/type/promise/promise-config.test.js
Labels: PR: reviewed-approved

#1670 chore: remove stale helper methods
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#1669 chore: rm redundant test dir cleanup, rm test level gitignore and handle at root
  .gitignore
  test/config/multiple/all/multiple-config.test.js
  test/config/multiple/multiple-location/multiple-location-config.test.js
  test/config/multiple/none and dev/dev-none-config.test.js
  test/config/multiple/with-mode/multiple-config.test.js
  test/entry/scss/.gitignore
  test/mode/mode-with-config/.gitignore
  test/output/named-bundles/output-named-bundles.test.js
  test/stats/cli-flags/.gitignore
  test/stats/config/.gitignore
  test/typescript/.gitignore
Labels: PR: reviewed-approved

#1671 chore: remove redundant instructions
  scripts/cleanupTest.js
  test/init/auto/init-auto.test.js
  test/init/force/init-force.test.js
  test/init/generator/init-inquirer.test.js
  test/init/language/css/init-language-css.test.js
  test/init/language/js/init-language-js.test.js
  test/init/multipleEntries/init-multipleEntries.test.js
  test/loader/loader.test.js
  test/migrate/config/migrate-config.test.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved

#1668 feat(webpack-cli): allow negative property for cli-flags
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved

#1676 chore: handle unknown args and improve test suite for info
  packages/info/src/index.ts
  test/info/info-help.test.js
  test/info/info-output.test.js
  test/info/info-unknown.test.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved, PR: small

#1682 tests: add more cases in ZeroConfigGroup test
  packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
Labels: PR: reviewed-approved

#1687 docs: add --env type
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#1688 fix: set mode=production by default
  packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/defaults/output-defaults.test.js
  test/merge/config/merge-config.test.js
  test/merge/defaults/merge-defaults.test.js
  test/merge/defaults/some_entry.js
  test/merge/defaults/some_other_entry.js
  test/mode/mode-single-arg/mode-single-arg.test.js
  test/mode/mode-single-arg/webpack.config.js
Labels: PR: review-outdated

#1690 fix: use fileTypes from interpret
  packages/webpack-cli/lib/groups/ConfigGroup.js
Labels: PR: reviewed-approved, PR: small

#1692 docs: fix yarn installation guide
  .github/CONTRIBUTING.md
Labels: PR: reviewed-approved, PR: small

#1695 chore(deps): upgrade commander.js to v6
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/package.json
Labels: PR: reviewed-approved, PR: small

#1697 chore: update yarn.lock
  yarn.lock
Labels: PR: reviewed-approved, PR: small

#1693 refactor: remove --dev and --prod flags
  packages/webpack-cli/README.md
  packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/env/prod/index.js
  test/env/prod/prod.test.js
  test/env/prod/webpack.config.js
  test/mode/dev/dev.test.js
  test/mode/dev/src/index.js
  test/mode/prod/prod.test.js
  test/mode/prod/src/index.js
Labels: PR: review-outdated

#1674 fix: warn about merge config resolution cases
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/utils/GroupHelper.js
  packages/webpack-cli/lib/utils/errors/MergeError.js
  test/merge/config-absent/1.js
  test/merge/config-absent/merge-config-absent.test.js
  test/merge/config-absent/some_entry.js
  test/merge/config/1.js
  test/merge/config/2.js
  test/merge/config/merge-config.test.js
  test/merge/defaults/1.js
  test/merge/defaults/merge-defaults.test.js
  test/merge/defaults/some_entry.js
  test/merge/defaults/some_other_entry.js
  test/merge/defaults/webpack.base.js
Labels: PR: reviewed-approved

#1699 tests: improve webpackCLITestPlugin
  test/utils/cli-plugin-test/plugin.test.js
  test/utils/cli-plugin-test/webpack.config.js
  test/utils/webpack-cli-test-plugin.js
Labels: PR: reviewed-approved

#1698 chore: remove stale test cases
  test/env/array/array-env.test.js
  test/env/object/object-env.test.js
Labels: PR: reviewed-approved

#1702 fix: remove silent flag
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved

#1701 chore: remove unused config file
  .fitcommitjsrc.json
  .npmignore
Labels: PR: review-outdated

#1630 feat(webpack-cli): import flags from webpack core
  jest.config.js
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
  scripts/cleanupTest.js
  test/core-flags/amd-flag.test.js
  test/core-flags/bail-flag.test.js
  test/core-flags/cache-flags.test.js
  test/core-flags/context-flag.test.js
  test/core-flags/dependencies-flag.test.js
  test/core-flags/devtool-flag.test.js
  test/core-flags/experiments-flag.test.js
  test/core-flags/externals-flags.test.js
  test/core-flags/infrastructure-logging.test.js
  test/core-flags/main.js
  test/core-flags/module-flags.test.js
  test/core-flags/node-flags.test.js
  test/core-flags/optimization-flags.test.js
  test/core-flags/output-flags.test.js
  test/core-flags/parallelism-flag.test.js
  test/core-flags/performance-flags.test.js
  test/core-flags/profile-flag.test.js
  test/core-flags/records-flag.test.js
  test/core-flags/resolve-flags.test.js
  test/core-flags/stats-flags.test.js
  test/core-flags/watch-flags.test.js
  test/core-flags/webpack.config.js
  test/utils/test-utils.js
  test/version/version-multi-args.test.js
Labels: PR: reviewed-approved

#1705 docs: show download stats for serve
  packages/serve/README.md
Labels: PR: reviewed-approved, PR: small

#1707 docs(init): add info regarding force flag
  packages/init/README.md
Labels: PR: reviewed-approved, PR: small

#1691 chore: migrate to colorette
  package.json
  packages/generators/package.json
  packages/generators/src/init-generator.ts
  packages/info/package.json
  packages/info/src/index.ts
  packages/init/package.json
  packages/migrate/package.json
  packages/migrate/src/index.ts
  packages/migrate/src/removeDeprecatedPlugins/removeDeprecatedPlugins.ts
  packages/package-utils/package.json
  packages/package-utils/src/packageUtils.ts
  packages/utils/package.json
  packages/utils/src/modify-config-helper.ts
  packages/utils/src/npm-packages-exists.ts
  packages/utils/src/resolve-packages.ts
  packages/utils/src/run-prettier.ts
  packages/utils/src/scaffold.ts
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/commands/ExternalCommand.js
  packages/webpack-cli/lib/groups/BasicGroup.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/cli-executer.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/interactive.js
  packages/webpack-cli/lib/utils/unknown-args.js
  packages/webpack-cli/lib/webpack-cli.js
  packages/webpack-cli/package.json
  scripts/prepareSuite.js
  test/help/help-single-arg.test.js
  test/info/info-help.test.js
  test/info/info-unknown.test.js
  test/init/coreFlags/init-flags.test.js
  test/migrate/config/migrate-config.test.js
  test/progress/progress-flag.test.js
  test/version/version-multi-args.test.js
  yarn.lock
Labels: PR: reviewed-approved

#1710 chore: sync lock file
  yarn.lock
Labels: PR: reviewed-approved, PR: small

#1709 chore: cleanup verbose flag
  packages/webpack-cli/README.md
  packages/webpack-cli/__tests__/StatsGroup.test.js
  packages/webpack-cli/lib/groups/BasicGroup.js
  packages/webpack-cli/lib/groups/StatsGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/no-stats/with-flags/no-stats.test.js
  test/stats/cli-flags/stats.test.js
  test/verbose/index.js
  test/verbose/verbose-flag.test.js
Labels: PR: reviewed-approved

#1714 chore: enable workflow_dispatch event
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small
