Repository webpack/webpack-cli, pull requests merged in 2020-03, with the labels that each got.

#1276 feat(webpack-cli): add no-mode flag
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/help/__snapshots__/help-single-arg.test.js.snap
  test/json/json.test.js
  test/no-mode/no-mode.test.js
  test/no-mode/src/index.js
Labels: PR: CI-ok, PR: reviewed-approved

#1292 feat(README): Node CI badge added
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1293 tests(webpack-cli): remove intrusive snapshot
  test/help/__snapshots__/help-single-arg.test.js.snap
  test/help/help-single-arg.test.js
Labels: PR: CI-ok, PR: unreviewed

#1294 docs(readme): reflect branch next
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1290 feat(webpack-cli): add mode argument validation
  packages/webpack-cli/lib/utils/cli-flags.js
  test/mode/prod/prod.test.js
  test/mode/prod/src/index.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1304 chore(webpack-cli): remove stale imports from configGroup
  packages/webpack-cli/lib/groups/ConfigGroup.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1284 fix(webpack-cli): handle promise rejection with package installation
  packages/package-utils/__tests__/index.test.ts
  packages/webpack-cli/lib/commands/ExternalCommand.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1280 tests(cli): executer tests
  packages/webpack-cli/__tests__/cli-executer.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1303 fix: add configuration for mode option none
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  packages/webpack-cli/lib/utils/none-config.js
Labels: PR: CI-ok, PR: reviewed-approved

#1299 feat(webpack-cli): stats
  .travis.yml
  packages/webpack-cli/README.md
  packages/webpack-cli/__tests__/StatsGroup.test.js
  packages/webpack-cli/lib/groups/StatsGroup.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/CompilerOutput.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/.eslintrc
  test/config-lookup/dotfolder-array/dotfolder-array.test.js
  test/config-lookup/dotfolder-single/dotfolder-single.test.js
  test/config/basic/basic-config.test.js
  test/config/empty/empty-config.test.js
  test/config/type/array/array-config.test.js
  test/config/type/function/function-config.test.js
  test/defaults/output-defaults.test.js
  test/defaults/without-config-and-entry/default-without-config.test.js
  test/entry/defaults-empty/entry-single-arg.test.js
  test/entry/defaults-index/entry-multi-args.test.js
  test/global/global.test.js
  test/merge/config/merge-config.test.js
  test/merge/defaults/merge-defaults.test.js
  test/node/node.test.js
  test/output/named-bundles/output-named-bundles.test.js
  test/output/pretty/pretty.test.js
  test/standard/standard.test.js
  test/stats/.gitignore
  test/stats/index.js
  test/stats/package.json
  test/stats/stats.test.js
  test/stats/webpack.config.js
Labels: PR: CI-ok, PR: reviewed-approved

#1301 tests: add case for mode option none in ZeroGroupConfig
  packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1289 fix(webpack-cli): to void defaultEntry override the webpack config entry
  packages/webpack-cli/lib/groups/BasicGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
  test/entry/config-entry/1.js
  test/entry/config-entry/a.js
  test/entry/config-entry/entry-with-command/entry-with-command.test.js
  test/entry/config-entry/entry-with-command/index.js
  test/entry/config-entry/entry-with-config/entry-with-config.test.js
  test/entry/config-entry/entry-with-config/index.js
Labels: PR: CI-ok, PR: reviewed-approved

#1315 tests: fix tests
  test/defaults/with-config-and-entry/default-with-config.test.js
  test/entry/config-entry/entry-with-command/entry-with-command.test.js
  test/entry/config-entry/entry-with-config/entry-with-config.test.js
Labels: PR: CI-ok, PR: unreviewed

#1314 chore: reduce install size
  packages/webpack-cli/package.json
  yarn.lock
Labels: PR: CI-not-ok, PR: reviewed-approved

#1306 chore: fix typos across the project
  packages/serve/src/args-to-camel-case.ts
  packages/utils/src/ast-utils.ts
  packages/webpack-cli/lib/bootstrap.js
  test/env/array/array-env.test.js
  test/env/object/object-env.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1309 [bugfix] webpack-cli init loader's test regex
  packages/generators/src/utils/languageSupport.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1316 chore(webpack-cli): remove pretty output functionality
  packages/info/package.json
  packages/info/src/index.ts
  packages/info/src/renderTable.ts
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/groups/StatsGroup.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/CompilerOutput.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/package.json
  test/output/pretty/pretty.test.js
  test/output/pretty/src/index.js
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved

#1329 docs: add core-team link to CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1331 chore: update code of conduct and fix links
  CODE_OF_CONDUCT.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1332 docs(contributing): update table of contents
  .github/CONTRIBUTING.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1338 [Docs]: follow a consistent format
  CODE_OF_CONDUCT.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1341 docs(readme): update table of contents
  README.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1348 chore: fix eslint configuration
  packages/webpack-cli/.eslintrc.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1345 chore(webpack-cli): improve import-local
  packages/webpack-cli/bin/cli.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1319 tests(webpack-cli): correct descriptions for no-mode test cases
  test/no-mode/no-mode.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1354 docs: general corrections and improvements
  .github/CONTRIBUTING.md
  README.md
  packages/generate-plugin/templates/src/_index.js.tpl
  packages/generators/__tests__/plugin-generator.test.ts
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1351 chore: remove stale code and improve logic
  commitlint.config.js
  packages/info/src/configParser.ts
  packages/info/src/index.ts
  packages/package-utils/__tests__/index.test.ts
  packages/webpack-cli/lib/commands/ExternalCommand.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1317 fix: peer dependencies for `webpack serve`
  packages/serve/package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1339 chore: update dependencies
  package.json
  packages/generate-loader/package.json
  packages/generate-plugin/package.json
  packages/generators/package.json
  packages/info/package.json
  packages/init/package.json
  packages/logger/package.json
  packages/migrate/package.json
  packages/package-utils/package.json
  packages/utils/package.json
  packages/utils/src/npm-exists.ts
  packages/webpack-cli/package.json
  packages/webpack-scaffold/__tests__/__snapshots__/index.test.ts.snap
  packages/webpack-scaffold/package.json
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved

#1367 fix: yarn.lock conflicts on setup
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved

#1359 feat: add stats detailed option
  packages/webpack-cli/lib/groups/StatsGroup.js
  test/stats/stats.test.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1366 fix(packages): make packages have correct main paths to index
  packages/generate-plugin/package.json
  packages/info/package.json
  packages/init/package.json
  packages/migrate/package.json
  packages/serve/package.json
Labels: PR: CI-ok, PR: reviewed-approved

#1350 docs: improving contributing.md
  .github/CONTRIBUTING.md
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1375 tests(utils): add packageUtils tests
  packages/package-utils/__tests__/index.test.ts
  packages/package-utils/__tests__/packageUtils.test.ts
  packages/package-utils/__tests__/test-both/yarn.lock
  packages/package-utils/__tests__/test-yarn-lock/yarn.lock
  packages/package-utils/src/packageUtils.ts
  packages/webpack-cli/lib/commands/ExternalCommand.js
Labels: PR: CI-ok, PR: reviewed-approved

#1358 chore(logger): remove logger package, inline webpack logger
  packages/logger/.eslintrc
  packages/logger/.gitignore
  packages/logger/.npmignore
  packages/logger/CHANGELOG.md
  packages/logger/README.md
  packages/logger/package.json
  packages/logger/src/index.ts
  packages/logger/tsconfig.json
  packages/package-utils/package.json
  packages/package-utils/tsconfig.json
  packages/webpack-cli/lib/groups/StatsGroup.js
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/logger.js
  packages/webpack-cli/package.json
Labels: PR: CI-ok, PR: reviewed-approved

#1376 chore: rm unused packages
  .eslintrc.js
  package.json
  packages/generate-loader/package.json
  packages/generate-plugin/package.json
  packages/generators/package.json
  packages/info/package.json
  packages/init/package.json
  packages/migrate/package.json
  packages/package-utils/package.json
  packages/serve/package.json
  packages/utils/package.json
  packages/webpack-cli/package.json
  packages/webpack-scaffold/package.json
  yarn.lock
Labels: PR: CI-ok, PR: review-outdated

#1377 docs: Fix jsdoc comment for a test util function `run`
  test/utils/test-utils.js
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1364 docs: describe commit types
  .cz-config.js
  .github/CONTRIBUTING.md
Labels: PR: CI-ok, PR: reviewed-approved

#1378 chore: bump dependencies
  packages/generators/package.json
  packages/generators/src/addon-generator.ts
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved

#1381 chore: remove stub type definition
  packages/generators/package.json
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved, PR: small

#1387 chore(deps): upgrade jest
  package.json
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/__tests__/loader-generator.test.ts
  packages/generators/__tests__/plugin-generator.test.ts
  packages/utils/package.json
  yarn.lock
Labels: PR: CI-ok, PR: reviewed-approved

#1356 chore(workflows): add macOS, Windows, node v13 and linting
  .github/workflows/nodejs.yml
  README.md
  package.json
  packages/package-utils/__tests__/packageUtils.test.ts
  packages/webpack-cli/lib/groups/ConfigGroup.js
  test/node/node.test.js
  test/serve/serve-basic.test.js
  test/serve/webpack.config.js
  test/utils/test-utils.js
  yarn.lock
Labels: PR: CI-not-ok, PR: review-outdated, PR: small

#1355 chore: remove old, unused CI configuration files
  .travis.yml
  azure-pipelines-template.yml
  azure-pipelines.yml
Labels: PR: reviewed-approved

#1390 docs: improve badges
  README.md
Labels: PR: unreviewed
