Repository webpack/webpack-cli, pull requests merged in 2020-11, with the labels that each got.

#2007 docs: update generators links
  packages/generators/README.md
Labels: PR: reviewed-approved, PR: small

#2012 tests: add tests for env in configGroup
  packages/webpack-cli/__tests__/ConfigGroup/ConfigGroup.test.js
  packages/webpack-cli/__tests__/ConfigGroup/env.webpack.config.cjs
Labels: PR: reviewed-approved

#2008 fix(generators): correct optimization.splitChunks option in config
  packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/src/utils/webpackConfig.ts
Labels: PR: reviewed-approved

#2009 refactor: CLI creator class
  packages/serve/src/index.ts
  packages/webpack-cli/lib/utils/GroupHelper.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#2010 feat: suggest the closest match based on the Levenshtein distance algorithm
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/package.json
  test/unknown/unknown.test.js
Labels: PR: reviewed-approved

#2015 tests: update anayze-flag test
  test/analyze/analyze-flag.test.js
Labels: PR: reviewed-approved, PR: small

#2020 fix(info): throw error and exit for invalid --output value
  packages/info/src/index.ts
  test/info/info-output.test.js
Labels: PR: reviewed-approved, PR: small

#2014 chore: improve error message for invalid progress value
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/plugins/WebpackCLIPlugin.js
  test/progress/progress-flag.test.js
Labels: PR: reviewed-approved

#2017 chore: add more tmp test files to .prettierignore
  .prettierignore
Labels: PR: reviewed-approved, PR: small

#2011 feat: export utils from core for other packages
  packages/generate-loader/src/index.ts
  packages/generate-plugin/src/index.ts
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/src/addon-generator.ts
  packages/generators/src/init-generator.ts
  packages/info/src/index.ts
  packages/migrate/src/index.ts
  packages/migrate/src/removeDeprecatedPlugins/removeDeprecatedPlugins.ts
  packages/serve/src/parseArgs.ts
  packages/utils/__tests__/global-packages-path.test.ts
  packages/utils/src/global-packages-path.ts
  packages/utils/src/modify-config-helper.ts
  packages/utils/src/recursive-parser.ts
  packages/utils/src/resolve-packages.ts
  packages/utils/src/run-prettier.ts
  packages/utils/src/scaffold.ts
  packages/utils/src/spawn-child.ts
  packages/webpack-cli/lib/index.js
  packages/webpack-cli/lib/utils/__tests__/get-package-manager.test.js
  packages/webpack-cli/lib/utils/__tests__/prompt-installation.test.js
  packages/webpack-cli/lib/utils/get-package-manager.js
  packages/webpack-cli/lib/utils/prompt-installation.js
  packages/webpack-cli/package.json
Labels: PR: reviewed-approved

#2023 fix: handle core flags for webpack 4
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved, PR: small

#2016 chore(deps): remove unused ansi-escapes
  packages/webpack-cli/lib/utils/interactive.js
  packages/webpack-cli/package.json
Labels: PR: reviewed-approved, PR: small

#2026 chore: display running webpack version during tests
  .github/workflows/nodejs.yml
  jest.config.js
  scripts/globalSetup.js
  test/progress/progress-flag.test.js
Labels: PR: reviewed-approved, PR: small

#1899 feat: coverage
  .codecov.yml
  .github/workflows/nodejs.yml
  .nycrc
  jest.config.js
  package.json
  scripts/setupBuild.js
  test/config-format/typescript/tsconfig.json
  test/config-format/typescript/typescript.test.js
  tsconfig.json
  yarn.lock
Labels: PR: unreviewed

#2032 feat: configure codecov reporting
  .codecov.yml
  .nycrc
Labels: PR: reviewed-approved

#2030 tests: add a case for invalid context value
  test/core-flags/context-flag.test.js
Labels: PR: reviewed-approved

#2037 docs: update readme.md
  README.md
Labels: PR: reviewed-approved, PR: small

#2022 fix: resolve dev server hot options correctly
  packages/serve/__tests__/createConfig.test.ts
  packages/serve/src/createConfig.ts
  packages/serve/src/index.ts
  packages/serve/src/parseArgs.ts
  packages/serve/src/startDevServer.ts
  test/serve/basic/serve-basic.test.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#2027 feat: add WEBPACK_SERVE environment variable
  packages/serve/__tests__/__snapshots__/parseArgs.test.ts.snap
  packages/serve/src/parseArgs.ts
  test/serve/serve-variable/serve-basic.test.js
  test/serve/serve-variable/src/index.js
  test/serve/serve-variable/webpack.config.js
Labels: PR: reviewed-approved

#2013 fix: assign cache value for default configs
  packages/webpack-cli/lib/groups/resolveConfig.js
  packages/webpack-cli/lib/utils/flag-defaults.js
  packages/webpack-cli/lib/webpack-cli.js
  test/core-flags/cache-flags.test.js
Labels: PR: reviewed-approved

#2035 docs: cleanup readme
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#2044 docs: add configuration.externalsPrestes related flags
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved

#2043 refactor: remove redundant merge-strategies util
  packages/webpack-cli/lib/utils/merge-strategies.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved, PR: small

#2046 refactor: utils
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/groups/resolveAdvanced.js
  packages/webpack-cli/lib/groups/runVersion.js
  packages/webpack-cli/lib/plugins/WebpackCLIPlugin.js
  packages/webpack-cli/lib/utils/__tests__/package-exists.test.js
  packages/webpack-cli/lib/utils/__tests__/prompt-installation.test.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/commands.js
  packages/webpack-cli/lib/utils/core-flags.js
  packages/webpack-cli/lib/utils/package-exists.js
  packages/webpack-cli/lib/utils/prompt-installation.js
  packages/webpack-cli/lib/utils/resolve-command.js
  packages/webpack-cli/lib/utils/run-command.js
  packages/webpack-cli/lib/utils/to-kebab-case.js
  packages/webpack-cli/lib/utils/unknown-args.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#2047 chore: remove help group properties
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2040 feat: add pnpm support for package installation
  packages/webpack-cli/lib/utils/__tests__/get-package-manager.test.js
  packages/webpack-cli/lib/utils/__tests__/prompt-installation.test.js
  packages/webpack-cli/lib/utils/__tests__/test-all-lock/package-lock.json
  packages/webpack-cli/lib/utils/__tests__/test-all-lock/pnpm-lock.yaml
  packages/webpack-cli/lib/utils/__tests__/test-all-lock/yarn.lock
  packages/webpack-cli/lib/utils/__tests__/test-npm-and-pnpm/package-lock.json
  packages/webpack-cli/lib/utils/__tests__/test-npm-and-pnpm/pnpm-lock.yaml
  packages/webpack-cli/lib/utils/__tests__/test-pnpm-lock/pnpm-lock.yaml
  packages/webpack-cli/lib/utils/get-package-manager.js
  packages/webpack-cli/lib/utils/prompt-installation.js
Labels: PR: reviewed-approved, PR: reviewed-changes-requested

#2039 chore: add documentation links to cli-flags for help output
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2049 fix: merge resolvers
  packages/webpack-cli/__tests__/resolveAdvanced.test.js
  packages/webpack-cli/__tests__/resolveArgs.test.js
  packages/webpack-cli/__tests__/resolveMode.test.js
  packages/webpack-cli/__tests__/resolveOutput.test.js
  packages/webpack-cli/__tests__/resolveStats.js
  packages/webpack-cli/lib/groups/basicResolver.js
  packages/webpack-cli/lib/groups/resolveMode.js
  packages/webpack-cli/lib/groups/resolveOutput.js
  packages/webpack-cli/lib/groups/resolveStats.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/webpack-cli.js
  test/mode/mode-single-arg/mode-single-arg.test.js
Labels: PR: reviewed-approved

#2059 chore: add ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE.md
Labels: PR: reviewed-approved

#2053 fix: remove default value for devtool
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2057 docs: update stats option related flags
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved

#2058 fix: update --output-path link
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2069 chore: remove stale utils
  packages/webpack-cli/lib/utils/arg-utils.js
  packages/webpack-cli/lib/utils/to-kebab-case.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#2068 chore: rm redundant group resolvers
  packages/webpack-cli/lib/groups/resolveAdvanced.js
Labels: PR: reviewed-approved

#2078 docs: update INIT.md
  INIT.md
Labels: PR: reviewed-approved

#2080 docs: add code coverage badge
  README.md
Labels: PR: reviewed-approved, PR: small

#2067 fix: improve package-exists util
  packages/webpack-cli/lib/utils/package-exists.js
Labels: PR: reviewed-approved, PR: small

#2070 fix: catch dev server import during webpack serve
  packages/serve/src/startDevServer.ts
Labels: PR: reviewed-approved

#2050 feat(init): add --generation-path flag
  packages/generators/src/init-generator.ts
  packages/init/README.md
  packages/init/src/index.ts
  packages/utils/src/modify-config-helper.ts
  packages/utils/src/scaffold.ts
  test/init/generation-path/init-generation-path.test.js
Labels: PR: reviewed-approved

#2073 feat(generate-plugin): scaffold in a specified path
  packages/generate-plugin/README.md
  packages/generate-plugin/src/index.ts
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved

#2045 tests: add more cases for core-flags tests
  test/core-flags/entry-reset-flag.test.js
  test/core-flags/externals-flags.test.js
  test/core-flags/infrastructure-logging.test.js
  test/core-flags/parallelism-flag.test.js
  test/target/flag-test/target-flag.test.js
  test/target/flag-test/webpack.config.js
Labels: PR: reviewed-approved

#2071 fix: use content hash for css assets in init-generator
  packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
  packages/generators/src/init-generator.ts
Labels: PR: reviewed-approved, PR: small

#2064 docs: update --env & --target types
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#2083 tests(init): add test case for scaffolding in the current directory
  test/init/generation-path/init-generation-path.test.js
Labels: PR: reviewed-approved

#2079 chore(utils): remove duplicate log
  packages/utils/src/modify-config-helper.ts
  test/init/auto/init-auto.test.js
  test/init/force/init-force.test.js
  test/init/generator/init-inquirer.test.js
Labels: PR: reviewed-approved, PR: small

#2085 docs: add --generation-path for init
  INIT.md
Labels: PR: reviewed-approved, PR: small

#2084 feat(init): display available options as part of help information
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved

#2063 tests: enable tests for generators
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/__tests__/utils/languageSupport.test.ts
  packages/generators/__tests__/utils/styleSupport.test.ts
Labels: PR: reviewed-approved

#2072 feat(generate-loader): scaffold in a specified path
  packages/generate-loader/README.md
  packages/generate-loader/src/index.ts
  test/loader/loader.test.js
Labels: PR: reviewed-approved

#2086 chore: update usage info for subcommands
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2042 fix: allow to disable stats color via --no-color
  packages/serve/__tests__/__snapshots__/parseArgs.test.ts.snap
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
  test/colors/colors.test.js
  test/colors/multiple-configs.js
  test/colors/src/first.js
  test/colors/src/second.js
  test/config/type/function-with-argv/function-with-argv.test.js
  test/json/json.test.js
  test/unknown/unknown.test.js
Labels: PR: reviewed-approved

#2093 docs: update reference to subcommands
  README.md
Labels: PR: reviewed-approved, PR: small

#2088 docs: add configuration.ignoreWarnings related flags
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#2092 tests: fix flaky env tests
  test/env/array/array-env.test.js
  test/env/array/webpack.config.js
  test/env/object/object-env.test.js
Labels: PR: reviewed-approved

#2076 fix: use logger to throw error with proper exit code
  packages/webpack-cli/lib/utils/__tests__/resolve-command.test.js
  packages/webpack-cli/lib/utils/resolve-command.js
  packages/webpack-cli/lib/utils/run-command.js
Labels: PR: reviewed-approved, PR: small

#2060 refactor: get-package-manger logic for perf improvements
  packages/webpack-cli/lib/utils/__tests__/get-package-manager.test.js
  packages/webpack-cli/lib/utils/__tests__/test-npm-and-yarn/package-lock.json
  packages/webpack-cli/lib/utils/__tests__/test-npm-and-yarn/yarn.lock
  packages/webpack-cli/lib/utils/__tests__/test-yarn-and-pnpm/pnpm-lock.yaml
  packages/webpack-cli/lib/utils/__tests__/test-yarn-and-pnpm/yarn.lock
  packages/webpack-cli/lib/utils/get-package-manager.js
Labels: PR: reviewed-approved

#2074 fix: union webpack-scaffold and generators package
  .eslintignore
  .eslintrc.js
  README.md
  packages/README.md
  packages/generators/__tests__/utils/__snapshots__/scaffold-utils.test.ts.snap
  packages/generators/__tests__/utils/entry.test.ts
  packages/generators/__tests__/utils/scaffold-utils.test.ts
  packages/generators/package.json
  packages/generators/src/init-generator.ts
  packages/generators/src/utils/entry.ts
  packages/generators/src/utils/scaffold-utils.ts
  packages/generators/tsconfig.json
  packages/webpack-scaffold/CHANGELOG.md
  packages/webpack-scaffold/README.md
  packages/webpack-scaffold/__tests__/__snapshots__/index.test.ts.snap
  packages/webpack-scaffold/package.json
  packages/webpack-scaffold/src/index.ts
  packages/webpack-scaffold/tsconfig.json
  tsconfig.json
Labels: PR: reviewed-approved

#2096 chore: remove instances of old interactive
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/interactive.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#2094 chore: fix typo
  test/colors/colors.test.js
Labels: PR: reviewed-approved, PR: small

#2066 feat: expose config resolving as CLI instance
  packages/webpack-cli/__tests__/resolveConfig/resolveConfig.test.js
  packages/webpack-cli/lib/groups/resolveConfig.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#2097 chore(utils): remove cross-spawn
  packages/utils/__tests__/global-packages-path.test.ts
  packages/utils/package.json
  packages/utils/src/global-packages-path.ts
  yarn.lock
Labels: PR: reviewed-approved

#2048 Refactor code
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/groups/runHelp.js
  packages/webpack-cli/lib/groups/runVersion.js
  packages/webpack-cli/lib/utils/__tests__/package-exists.test.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/arg-utils.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/resolve-command.js
  packages/webpack-cli/lib/utils/to-kebab-case.js
  packages/webpack-cli/lib/utils/unknown-args.js
  packages/webpack-cli/lib/webpack-cli.js
  test/help/help-commands.test.js
  test/help/help-flags.test.js
  test/info/info-help.test.js
  test/utils/test-utils.js
  test/version/version-external-packages.test.js
  test/version/version-multi-args.test.js
Labels: PR: reviewed-approved

#2098 fix: respect `stats` from the config for webpack@4
  packages/webpack-cli/lib/webpack-cli.js
  test/stats/watch/multi-webpack.config.js
  test/stats/watch/src/index.js
  test/stats/watch/stats-and-watch.test.js
  test/stats/watch/webpack.config.js
Labels: PR: reviewed-approved

#2091 chore(ci): upgrade to using environment files
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small

#2105 tests: speedup
  test/config-lookup/dotfolder-array/.webpack/webpack.config.js
  test/config-name/function-config.js
  test/config-name/webpack.config.js
  test/config/function/multi-webpack.config.js
  test/config/multiple/webpack1.config.js
  test/config/multiple/webpack2.config.js
  test/config/type/array/webpack.config.js
  test/devtool/array/webpack.config.js
  test/devtool/object/webpack.eval.config.js
  test/devtool/object/webpack.source.config.js
  test/entry/scss/webpack.config.js
  test/target/flag-test/webpack.config.js
  test/target/node/webpack.config.js
  test/watch/watch-flag.test.js
Labels: PR: reviewed-approved

#2108 fix(init): add `files` field in tsconfig.json
  packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/templates/tsconfig.json.js
Labels: PR: reviewed-approved

#2109 chore: link to SO's guide for reproduction in bug template
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: PR: reviewed-approved, PR: small

#2126 fix(serve): do not default port in webpack-dev-server v4
  packages/serve/__tests__/createConfig.test.ts
  packages/serve/src/createConfig.ts
  packages/serve/src/startDevServer.ts
Labels: PR: reviewed-approved

#2133 feat(webpack-cli): add arg postprocessing
  packages/serve/__tests__/createConfig.test.ts
  packages/serve/src/createConfig.ts
  packages/serve/src/startDevServer.ts
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/lib/utils/arg-parser.js
Labels: PR: reviewed-approved

#2141 fix(serve): do not default host in webpack-dev-server v4
  packages/serve/src/startDevServer.ts
Labels: PR: reviewed-approved, PR: small

#2142 chore: replace compilation to complier
  packages/webpack-cli/lib/plugins/CLIPlugin.js
  test/stats/watch/stats-and-watch.test.js
  test/watch/watch-flag.test.js
Labels: PR: reviewed-approved

#2146 docs: update SECURITY.md
  SECURITY.md
Labels: PR: reviewed-approved, PR: small
