Repository webpack/webpack-cli, pull requests merged in 2020-05, with the labels that each got.

#1523 fix: ignore type inconsistency for now, fix build
  packages/migrate/package.json
  packages/migrate/src/index.ts
Labels: PR: review-outdated, PR: small

#1524 tests: add case to ensure entry and output resolve path same way
  test/entry/flag-entry/entry-with-flag.test.js
  test/output/named-bundles/output-named-bundles.test.js
Labels: PR: reviewed-approved

#1536 chore: allow commit type refactor
  .cz-config.js
  .github/CONTRIBUTING.md
  commitlint.config.js
Labels: PR: reviewed-approved

#1478 tests: add e2e tests for plugin
  test/init/auto/init-auto.test.js
  test/init/generator/init-inquirer.test.js
  test/loader/.gitignore
  test/loader/loader.test.js
  test/plugin/plugin.test.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#1543 refactor: 💡 remove defaults flag
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/zero-config.js
  packages/webpack-cli/lib/webpack-cli.js
  test/defaults/output-defaults.test.js
  test/defaults/with-config-and-entry/default-with-config.test.js
  test/defaults/with-config-and-entry/index.js
  test/defaults/with-config-and-entry/webpack.config.js
  test/defaults/without-config-and-entry/default-without-config.test.js
  test/output/named-bundles/output-named-bundles.test.js
Labels: PR: reviewed-approved

#1561 docs: remove --global instance
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#1546 tests: improve --node-args test cases
  test/node/node.test.js
Labels: PR: reviewed-approved, PR: small

#1550 chore: remove info-verbosity instances
  packages/webpack-cli/lib/utils/Compiler.js
Labels: PR: reviewed-approved

#1545 chore: 🤖 remove stale tests for standard flag and instances
  packages/webpack-cli/README.md
  test/loader/loader.test.js
  test/plugin/plugin.test.js
  test/standard/src/index.js
  test/standard/standard.test.js
  test/zero-config/with-config/zero-config-entry.test.js
Labels: PR: reviewed-approved

#1553 chore: remove stale issue_template.md
  .github/ISSUE_TEMPLATE.md
Labels: PR: review-outdated

#1549 fix(webpack-cli): verbose flag functionality
  packages/webpack-cli/lib/groups/StatsGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/stats/stats.test.js
  test/verbose/index.js
  test/verbose/verbose-flag.test.js
Labels: PR: reviewed-approved

#1547 chore: 🤖 improve cli-flags usage
  packages/webpack-cli/lib/utils/cli-flags.js
  test/help/help-flags.test.js
Labels: PR: reviewed-approved, PR: small

#1571 refactor: 💡 remove --plugin flag
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/groups/AdvancedGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved

#1565 fix: 🐛 do not apply own defaults while setting mode
  packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  packages/webpack-cli/lib/utils/development-config.js
  packages/webpack-cli/lib/utils/none-config.js
  packages/webpack-cli/lib/utils/production-config.js
  scripts/prepareSuite.js
  test/mode/mode-with-config/.gitignore
  test/mode/mode-with-config/index.js
  test/mode/mode-with-config/mode-with-config.test.js
  test/mode/mode-with-config/package.json
  test/mode/mode-with-config/webpack.config.js
Labels: PR: reviewed-approved

#1573 tests: add cases for json and verbose
  packages/webpack-cli/__tests__/StatsGroup.test.js
Labels: PR: review-outdated

#1574 chore: correct version flag group
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#1576 tests: check for the existence of webpack config file
  test/init/language/css/init-language-css.test.js
  test/init/language/js/init-language-js.test.js
Labels: PR: reviewed-approved, PR: reviewed-changes-requested, PR: small

#1575 chore[generators]: remove unused schema file
  packages/generators/src/utils/optionsSchema.json
Labels: PR: review-outdated

#1580 fix: typo in Compiler.js
  packages/webpack-cli/lib/utils/Compiler.js
Labels: PR: reviewed-approved, PR: small

#1579 tests: create unit test for OutputGroup
  packages/webpack-cli/__tests__/OutputGroup.test.js
Labels: PR: reviewed-approved

#1577 docs: correct stats type
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#1583 fix: prefetch flag implementation
  packages/webpack-cli/__tests__/AdvancedGroup.test.js
  packages/webpack-cli/lib/groups/AdvancedGroup.js
Labels: PR: reviewed-approved

#1595 chore: bump dependencies for v3
  package-lock.json
  package.json
Labels: PR: CI-ok, PR: reviewed-approved, PR: small
