Repository webpack/webpack-cli, pull requests merged in 2020-12, with the labels that each got.

#2153 docs: add --no-devtool & --no-watch
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#2150 chore: remove stale files from .eslintignore
  .eslintignore
Labels: PR: reviewed-approved

#2156 chore: remove unnecessary mocking of modules
  packages/utils/__tests__/global-packages-path.test.ts
  packages/webpack-cli/lib/utils/__tests__/get-package-manager.test.js
  packages/webpack-cli/lib/utils/__tests__/prompt-installation.test.js
Labels: PR: reviewed-approved

#2147 fix(serve): set client port when using default port
  packages/serve/__tests__/mergeOptions.test.ts
  packages/serve/__tests__/startDevServer.test.ts
  packages/serve/src/startDevServer.ts
  packages/serve/src/types.ts
Labels: PR: reviewed-approved

#2162 chore: remove stale type definition
  package.json
  yarn.lock
Labels: PR: reviewed-approved, PR: small

#2154 tests: correct merge-config-absent test
  test/merge/config-absent/merge-config-absent.test.js
  test/merge/config/merge-config.test.js
Labels: PR: reviewed-approved, PR: small

#2099 tests: use sync api for fs tests
  test/build-errors/errors.test.js
  test/build-warnings/warnings.test.js
  test/config-format/typescript/typescript.test.js
  test/config-lookup/dotfolder-array/dotfolder-array.test.js
  test/config-lookup/dotfolder-single/dotfolder-single.test.js
  test/config/defaults/dot-webpack-directory-webpackfile/multiple-location-config.test.js
  test/config/defaults/dot-webpack-directory/dev-none-config.test.js
  test/config/defaults/with-mode/multiple-config.test.js
  test/config/function/functional-config.test.js
  test/config/type/array-functions/array-functions.test.js
  test/config/type/array-promises/array-promises.test.js
  test/config/type/array/array.test.js
  test/config/type/function-array/function-array.test.js
  test/config/type/function-async/function-async.test.js
  test/config/type/function-promise/function-promise.test.js
  test/config/type/function/function.test.js
  test/config/type/promise-array/promise-array.test.js
  test/config/type/promise-function/promise-function.test.js
  test/config/type/promise/promise.test.js
  test/defaults/output-defaults.test.js
  test/devtool/object/source-map-object.test.js
  test/entry/config-entry/entry-with-command/entry-with-command.test.js
  test/entry/config-entry/entry-with-config/entry-with-config.test.js
  test/entry/defaults-index/entry-multi-args.test.js
  test/entry/flag-entry/entry-with-flag.test.js
  test/entry/multiple-entries/multi-entries.test.js
  test/json/json.test.js
  test/mode/mode-with-config/mode-with-config.test.js
  test/no-hot/no-hot.test.js
  test/node/node.test.js
  test/target/flag-test/target-flag.test.js
  test/target/node/node-test.test.js
Labels: PR: reviewed-approved

#2158 docs(webpack-cli): better description for negated flags
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#2160 chore: fix invalid-flag test description
  test/core-flags/invalid-flag.test.js
Labels: PR: reviewed-approved, PR: small

#2165 chore: fix args run method
  packages/webpack-cli/lib/bootstrap.js
Labels: PR: reviewed-approved, PR: small

#2167 chore: improve help output for --merge
  packages/webpack-cli/lib/utils/cli-flags.js
  test/help/help-flags.test.js
Labels: PR: reviewed-approved, PR: small

#2166 tests: cache
  test/cache/cache.test.js
  test/cache/multi.config.js
  test/cache/webpack.config.js
  test/core-flags/cache-flags.test.js
Labels: PR: reviewed-approved, PR: unreviewed

#2168 docs: remove old commands references
  README.md
Labels: PR: reviewed-approved, PR: small

#2174 fix: size of json stats
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: small, PR: unreviewed

#2169 tests: add more unit tests for info
  packages/info/__tests__/info.test.ts
  packages/info/src/index.ts
  packages/webpack-cli/__tests__/info.test.js
Labels: PR: unreviewed

#2176 docs: update output config related flags
  packages/webpack-cli/README.md
Labels: PR: unreviewed

#2179 tests: add test for array config err
  .eslintignore
  test/config/error-array/config-array-error.test.js
  test/config/error-array/src/index.js
  test/config/error-array/webpack.config.js
Labels: PR: reviewed-approved

#2183 chore: update webpack to 5.10.0
  package.json
  test/core-flags/output-flags.test.js
  yarn.lock
Labels: PR: reviewed-approved

#2177 tests: use sync fs for output check
  test/config/type/array-function-with-argv/function-with-argv.test.js
  test/config/type/array-function-with-env/array-function-with-env.test.js
  test/config/type/function-with-argv/function-with-argv.test.js
Labels: PR: reviewed-approved

#2186 tests: add tests for multitype flag
  packages/webpack-cli/__tests__/arg-parser.test.js
Labels: PR: reviewed-approved

#2188 fix: update description for --color flag
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2192 docs: add example commit messages
  .github/CONTRIBUTING.md
Labels: PR: reviewed-approved, PR: small

#2198 tests: respect cli args when config is an array
  test/config/type/array/array.test.js
  test/config/type/array/webpack.config.js
Labels: PR: reviewed-approved

#2190 Stringify stats using streaming approach
  packages/webpack-cli/lib/webpack-cli.js
  packages/webpack-cli/package.json
Labels: PR: reviewed-approved

#2180 chore: better description for built-in negated flags
  packages/webpack-cli/lib/groups/runHelp.js
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2195 fix: update usage of flags with multiple types
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2202 build: update lock file
  yarn.lock
Labels: PR: reviewed-approved, PR: small

#2193 tests: add tests for nested multitype flag
  packages/webpack-cli/__tests__/arg-parser.test.js
Labels: PR: reviewed-approved

#2172 feat: add mjs support
  .eslintignore
  .prettierignore
  packages/webpack-cli/lib/webpack-cli.js
  test/config-format/mjs/main.js
  test/config-format/mjs/mjs.test.js
  test/config-format/mjs/webpack.config.mjs
  test/config/defaults/mjs-config/default-mjs-config.test.js
  test/config/defaults/mjs-config/src/index.js
  test/config/defaults/mjs-config/webpack.config.mjs
  test/config/error-commonjs/config-error.test.js
  test/config/error-commonjs/src/index.js
  test/config/error-commonjs/syntax-error.js
  test/config/error-commonjs/webpack.config.js
  test/config/error-mjs/config-error.test.js
  test/config/error-mjs/src/index.js
  test/config/error-mjs/syntax-error.mjs
  test/config/error-mjs/webpack.config.mjs
Labels: PR: unreviewed

#2075 feat: union loader and plugin generators to single package
  packages/generate-loader/CHANGELOG.md
  packages/generate-loader/README.md
  packages/generate-loader/package.json
  packages/generate-loader/src/index.ts
  packages/generate-loader/tsconfig.json
  packages/generate-plugin/CHANGELOG.md
  packages/generate-plugin/README.md
  packages/generate-plugin/package.json
  packages/generate-plugin/src/index.ts
  packages/generate-plugin/tsconfig.json
  packages/generators/loader-template/examples/simple/src/index.js.tpl
  packages/generators/loader-template/examples/simple/src/lazy-module.js.tpl
  packages/generators/loader-template/examples/simple/src/static-esm-module.js.tpl
  packages/generators/loader-template/examples/simple/webpack.config.js.tpl
  packages/generators/loader-template/src/_index.js.tpl
  packages/generators/loader-template/src/cjs.js.tpl
  packages/generators/loader-template/test/fixtures/simple-file.js.tpl
  packages/generators/loader-template/test/functional.test.js.tpl
  packages/generators/loader-template/test/test-utils.js.tpl
  packages/generators/loader-template/test/unit.test.js.tpl
  packages/generators/package.json
  packages/generators/plugin-template/examples/simple/_webpack.config.js.tpl
  packages/generators/plugin-template/examples/simple/src/index.js.tpl
  packages/generators/plugin-template/examples/simple/src/lazy-module.js.tpl
  packages/generators/plugin-template/examples/simple/src/static-esm-module.js.tpl
  packages/generators/plugin-template/src/_index.js.tpl
  packages/generators/plugin-template/src/cjs.js.tpl
  packages/generators/plugin-template/test/fixtures/simple-file.js.tpl
  packages/generators/plugin-template/test/functional.test.js.tpl
  packages/generators/plugin-template/test/test-utils.js.tpl
  packages/generators/src/index.ts
  packages/generators/src/loader-generator.ts
  packages/generators/src/plugin-generator.ts
  packages/info/__tests__/info.test.ts
  packages/info/src/index.ts
  packages/init/src/index.ts
  packages/migrate/src/index.ts
  packages/serve/src/index.ts
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/resolve-command.js
  test/version/version-external-packages.test.js
  tsconfig.json
Labels: PR: reviewed-approved, PR: unreviewed

#2194 tests: add tests for cli plugin resolver
  packages/webpack-cli/__tests__/CLIPluginResolver.test.js
Labels: PR: reviewed-approved

#2178 tests: add more cases for stats tests
  packages/webpack-cli/__tests__/resolveArgs.test.js
  test/stats/config/stats.test.js
Labels: PR: reviewed-approved

#2204 chore: rephrase error message
  packages/webpack-cli/lib/webpack-cli.js
  test/config-name/config-name.test.js
Labels: PR: reviewed-approved, PR: small

#2208 fix: ci lint
  .eslintignore
Labels: PR: reviewed-approved, PR: small

#2205 fix: correct usage of cli-flags
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2203 feat: display monorepos in info output
  packages/info/src/index.ts
  test/info/info-output.test.js
Labels: PR: reviewed-approved, PR: small, PR: unreviewed

#2151 feat: allow basic & verbose help output
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/groups/runHelp.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/help/help-single-arg.test.js
Labels: PR: reviewed-approved

#2207 tests: add more cases for target
  test/target/flag-test/target-flag.test.js
Labels: PR: reviewed-approved

#2213 chore: update usage info for migrate command
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2215 fix: info package docs
  packages/info/README.md
Labels: PR: reviewed-approved

#2222 tests: rm redundant tests
  packages/webpack-cli/__tests__/info.test.js
  packages/webpack-cli/__tests__/init.test.js
Labels: PR: reviewed-approved

#2251 refactor: faster levenshtein
  packages/webpack-cli/lib/webpack-cli.js
  packages/webpack-cli/package.json
  yarn.lock
Labels: PR: reviewed-approved

#2252 Chore remove broken smoke tests
  .github/workflows/nodejs.yml
  package.json
  smoketests/smoketests.sh
  smoketests/watch.sh
  smoketests/watch/watch.array.smoketest.js
  smoketests/watch/watch.single.smoketest.js
  smoketests/watch/webpack.array.config.js
Labels: PR: reviewed-approved

#2254 Issue 2226
  packages/webpack-cli/bin/cli.js
Labels: PR: reviewed-approved, PR: small

#2260 fix: 🐛 Fixed articles error in the CONTRIBUTING.md file
  .github/CONTRIBUTING.md
Labels: PR: small, PR: unreviewed

#2261 Test core args
  test/serve/basic/serve-basic.test.js
  test/serve/basic/webpack.config.js
Labels: PR: unreviewed

#2259 Issue 2217
  package.json
  packages/serve/src/index.ts
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
  test/config/multiple/multiple-config.test.js
  test/core-flags/watch-flags.test.js
  test/error/error-in-plugin/error.test.js
  test/error/error-in-plugin/src/index.js
  test/error/error-in-plugin/webpack.config.js
  test/error/error.test.js
  test/error/invalid-schema/invalid-schema.test.js
  test/error/invalid-schema/webpack.config.mock.js
  test/invalid-schema/invalid-schema.test.js
  test/watch/simple/src/index.js
  test/watch/simple/watch.config.js
  test/watch/simple/watch.test.js
  test/watch/stdin/multi-serve.config.js
  test/watch/stdin/multi-watch.config.js
  test/watch/stdin/serve.config.js
  test/watch/stdin/src/index.js
  test/watch/stdin/src/second.js
  test/watch/stdin/stdin.test.js
  test/watch/stdin/watch.config.js
  yarn.lock
Labels: PR: unreviewed

#2265 fix: the `--progress` option with the `serve` command
  packages/serve/__tests__/mergeOptions.test.ts
  packages/serve/src/index.ts
  packages/serve/src/mergeOptions.ts
  packages/serve/src/startDevServer.ts
  test/serve/basic/serve-basic.test.js
Labels: PR: unreviewed

#2267 fix: the `--help` option is working without `webpack-dev-server`
  packages/generators/src/index.ts
  packages/info/src/index.ts
  packages/init/src/index.ts
  packages/migrate/src/index.ts
  packages/serve/src/index.ts
  packages/webpack-cli/lib/utils/prompt-installation.js
  packages/webpack-cli/lib/webpack-cli.js
  test/help/help.test.js
  test/optimization/optimization.test.js
  test/optimization/src/index.js
  test/optimization/webpack.config.js
  test/utils/test-utils.js
  test/version/version.test.js
Labels: PR: unreviewed

#2269 fix: do not apply HotModuleReplacement plugin twice
  packages/serve/src/index.ts
  test/serve/basic/serve-basic.test.js
  test/serve/basic/webpack.config.js
  test/utils/cli-plugin-test/plugin.test.js
  test/utils/webpack-cli-test-plugin.js
Labels: PR: unreviewed

#2275 tests: open and serve
  package.json
  packages/utils/package.json
  packages/webpack-cli/package.json
  test/serve/basic/serve-basic.test.js
  yarn.lock
Labels: PR: unreviewed

#2276 fix: the `--progress` option is working with `--json`
  packages/webpack-cli/lib/plugins/CLIPlugin.js
  packages/webpack-cli/lib/webpack-cli.js
  test/build-errors/errors.test.js
  test/build-warnings/warnings.test.js
  test/json/json.test.js
  test/json/logging.config.js
Labels: PR: small, PR: unreviewed

#2271 tests: publicPath
  packages/serve/__tests__/__snapshots__/startDevServer.test.ts.snap
  packages/serve/src/startDevServer.ts
  packages/serve/src/types.ts
  test/serve/basic/dev-server-output-public-path.config.js
  test/serve/basic/multi-dev-server-output-public-path.config.js
  test/serve/basic/multi-dev-server.config.js
  test/serve/basic/multi-output-public-path.config.js
  test/serve/basic/multi.config.js
  test/serve/basic/multiple-dev-server.config.js
  test/serve/basic/output-public-path.config.js
  test/serve/basic/serve-basic.test.js
  test/serve/basic/src/other.js
Labels: PR: review-outdated, PR: unreviewed

#2280 refactor: code
  packages/webpack-cli/__tests__/CLI.test.js
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
  test/config/type/function-with-env/function-with-env.test.js
Labels: PR: unreviewed

#2281 Issue 2277
  packages/webpack-cli/lib/webpack-cli.js
  test/unknown/unknown.test.js
Labels: PR: unreviewed

#2282 fix: error message on not installed module loaders for configuration
  packages/webpack-cli/lib/webpack-cli.js
  test/config-format/failure/failure.test.js
  test/config-format/failure/webpack.config.coffee
Labels: PR: unreviewed

#2284 fix: peer dependencies
  packages/webpack-cli/package.json
Labels: PR: small, PR: unreviewed
