Repository webpack/webpack-cli, pull requests merged in 2020-10, with the labels that each got.

#1849 docs: add --optimization-split-chunks-default-size-types flag
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#1848 tests: add test for --entry-reset flag
  test/core-flags/entry-reset-flag.test.js
  test/core-flags/src/entry.js
  test/core-flags/src/main.js
  test/core-flags/webpack.config.js
Labels: PR: reviewed-approved

#1837 migrate basic group
  packages/webpack-cli/lib/groups/BasicGroup.js
  packages/webpack-cli/lib/groups/basicResolver.js
  packages/webpack-cli/lib/utils/GroupHelper.js
  packages/webpack-cli/lib/webpack-cli.js
  test/entry/flag-entry/entry-with-flag.test.js
  test/entry/flag-entry/src/index.cjs
  test/zero-config/entry-absent/zero-config.test.js
Labels: PR: reviewed-approved

#1835 feat: allow users to store stats as json to a file
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/groups/resolveStats.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/cli-flags.js
  scripts/cleanupTest.js
  test/json/json.test.js
Labels: PR: reviewed-approved

#1857 chore: remove redundant copyFile test-util
  test/utils/test-utils.js
  test/utils/test-utils.test.js
Labels: PR: reviewed-approved

#1858 refactor: use base resolver to resolve config
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#1855 fix: only set output path on passing flag
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/__tests__/resolveOutput.test.js
  packages/webpack-cli/lib/groups/resolveOutput.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/config/basic/basic-config.test.js
  test/defaults/output-defaults.test.js
  test/devtool/array/source-map-array.test.js
  test/devtool/object/source-map-object.test.js
  test/entry/defaults-index/entry-multi-args.test.js
  test/node/node.test.js
  test/node/webpack.config.js
  test/output/named-bundles/output-named-bundles.test.js
  test/output/named-bundles/webpack.config.js
  test/output/named-bundles/webpack.single.config.js
  test/utils/test-utils.js
  test/utils/test-utils.test.js
Labels: PR: review-outdated

#1856 fix: defer setting default entry to core
  packages/webpack-cli/README.md
  packages/webpack-cli/__tests__/serve/src/index.js
  packages/webpack-cli/lib/webpack-cli.js
  test/config/defaults/basic-config/default-js-config.test.js
  test/config/defaults/basic-config/src/index.js
  test/config/defaults/cjs-config/default-cjs-config.test.js
  test/config/defaults/cjs-config/src/index.js
  test/defaults/src/index.js
  test/entry/defaults-index/src/index.js
  test/env/array/src/index.js
  test/env/object/src/index.js
  test/hot/src/index.js
  test/json/src/index.js
  test/mode/mode-with-config/src/index.js
  test/name/src/index.js
  test/optimization/src/index.js
  test/progress/src/index.js
  test/serve/basic/src/index.js
  test/serve/with-custom-port/src/index.js
  test/utils/src/index.js
  test/zero-config/entry-absent/zero-config.test.js
Labels: PR: reviewed-approved

#1840 chore: update dependencies
  package.json
  packages/generate-loader/package.json
  packages/generate-plugin/package.json
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/__tests__/utils/languageSupport.test.ts
  packages/generators/__tests__/utils/styleSupport.test.ts
  packages/generators/package.json
  packages/info/package.json
  packages/init/package.json
  packages/migrate/package.json
  packages/migrate/src/index.ts
  packages/package-utils/package.json
  packages/utils/package.json
  packages/webpack-scaffold/package.json
  yarn.lock
Labels: PR: review-outdated

#1863 refactor: migrate advanced group
  packages/webpack-cli/__tests__/AdvancedGroup.test.js
  packages/webpack-cli/__tests__/resolveAdvanced.test.js
  packages/webpack-cli/lib/groups/AdvancedGroup.js
  packages/webpack-cli/lib/groups/resolveAdvanced.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#1861 chore: remove stale entries from gitignore
  .gitignore
  scripts/cleanupTest.js
  test/loader/error-test/tsconfig.json
Labels: PR: reviewed-approved, PR: small

#1862 fix: cache issue
  packages/webpack-cli/lib/utils/Compiler.js
  scripts/cleanupTest.js
  test/cache/cache.test.js
  test/cache/src/main.js
  test/cache/webpack.config.js
  test/core-flags/cache-flags.test.js
Labels: PR: reviewed-approved

#1865 chore: cleanup version invocation, argParser
  packages/info/src/options.ts
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/groups/runVersion.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/arg-utils.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#1873 refactor(info): remove duplicate cli-flags definition
  packages/info/src/index.ts
  packages/info/src/options.ts
Labels: PR: reviewed-approved

#1872 fix: warning should not result in non-zero exit code
  README.md
  packages/webpack-cli/lib/utils/Compiler.js
  test/loader/warning-test/loader-warning.test.js
  test/loader/warning-test/webpack.config.js
Labels: PR: review-outdated

#1868 refactor: remove negative reset flags
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/utils/cli-flags.js
  test/core-flags/module-flags.test.js
  test/core-flags/output-flags.test.js
  test/core-flags/stats-flags.test.js
  test/core-flags/watch-flags.test.js
Labels: PR: reviewed-approved

#1853 feat: add --analyze flag
  package.json
  packages/webpack-cli/README.md
  packages/webpack-cli/__tests__/resolveAdvanced.test.js
  packages/webpack-cli/lib/groups/resolveAdvanced.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/package.json
  test/analyze/analyze-flag.test.js
  test/analyze/main.js
  test/analyze/webpack.config.js
  test/utils/test-utils.js
  yarn.lock
Labels: PR: reviewed-approved

#1864 chore: add peer deps
  packages/webpack-cli/package.json
Labels: PR: reviewed-approved, PR: small

#1874 fix: log error if --config-name is used without multiple configs
  packages/webpack-cli/lib/groups/ConfigGroup.js
  test/config-name/config-name.test.js
  test/config-name/single-config.js
Labels: PR: reviewed-approved

#1867 refactor: external command
  packages/package-utils/__tests__/index.test.ts
  packages/webpack-cli/lib/commands/ExternalCommand.js
  packages/webpack-cli/lib/commands/resolveCommand.js
  packages/webpack-cli/lib/utils/arg-parser.js
Labels: PR: reviewed-approved

#1875 refactor: migrate help group
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/groups/runHelp.js
  packages/webpack-cli/lib/groups/runVersion.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/unknown-args.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#1869 chore: handle promise rejection
  packages/webpack-cli/bin/cli.js
Labels: PR: reviewed-approved, PR: reviewed-changes-requested, PR: small

#1854 tests: add test for --watch flag
  test/watch/main.js
  test/watch/watch-flag.test.js
Labels: PR: reviewed-approved

#1880 chore: improvement for publish
  .gitignore
  package.json
Labels: PR: reviewed-approved, PR: small

#1879 docs: release guide
  .github/CONTRIBUTING.md
Labels: PR: reviewed-approved, PR: small

#1884 chore: cleanup
  lint-staged.config.js
  package.json
  yarn.lock
Labels: PR: unreviewed

#1887 docs: update table of contents in contributing.md
  .github/CONTRIBUTING.md
Labels: PR: reviewed-approved, PR: small

#1888 tests: rm duplicate code for hypenToUpperCase util
  packages/webpack-cli/lib/utils/arg-utils.js
  test/utils/test-utils.js
  test/utils/test-utils.test.js
Labels: PR: reviewed-approved

#1886 chore: use logger.success
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/groups/resolveAdvanced.js
  packages/webpack-cli/lib/utils/Compiler.js
Labels: PR: reviewed-approved, PR: small

#1883 feat: CI - cache lerna dependencies
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small

#1891 chore(deps): move devDependencies from packages to root
  package.json
  packages/package-utils/__tests__/index.test.ts
  packages/package-utils/package.json
  packages/serve/__tests__/startDevServer.test.ts
  packages/serve/package.json
  packages/serve/src/parseArgs.ts
  packages/serve/src/startDevServer.ts
  yarn.lock
Labels: PR: reviewed-approved

#1890 tests: improve watch tests and enable windows
  test/watch/main.js
  test/watch/src/index.js
  test/watch/watch-flag.test.js
Labels: PR: reviewed-approved

#1882 feat: bump CI Node to 14
  .github/workflows/nodejs.yml
  test/node/node.test.js
Labels: PR: reviewed-approved, PR: small

#1893 refactor: remove stale code
  packages/package-utils/__tests__/index.test.ts
  packages/webpack-cli/lib/commands/resolveCommand.js
  packages/webpack-cli/lib/utils/arg-parser.js
Labels: PR: reviewed-approved

#1894 tests: enable --analyze tests for windows
  test/analyze/analyze-flag.test.js
  test/analyze/main.js
  test/analyze/src/index.js
  test/analyze/webpack.config.js
Labels: PR: reviewed-approved

#1892 chore: use default timeout for every test
  test/config-format/typescript/typescript.test.js
  test/entry/scss/scss.test.js
  test/loader/loader.test.js
  test/migrate/config/migrate-config.test.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved, PR: small

#1896 chore: use the "files" field
  packages/generate-loader/.npmignore
  packages/generate-loader/package.json
  packages/generate-plugin/.npmignore
  packages/generate-plugin/package.json
  packages/generators/.npmignore
  packages/generators/package.json
  packages/info/.npmignore
  packages/info/package.json
  packages/init/.npmignore
  packages/init/package.json
  packages/migrate/.npmignore
  packages/migrate/package.json
  packages/package-utils/package.json
  packages/serve/.npmignore
  packages/serve/package.json
  packages/utils/.npmignore
  packages/utils/package.json
  packages/webpack-cli/.npmignore
  packages/webpack-cli/package.json
  packages/webpack-scaffold/.npmignore
  packages/webpack-scaffold/package.json
Labels: PR: reviewed-approved

#1822 fix: cleanup `package-utils` package
  .eslintignore
  .gitignore
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/package.json
  packages/generators/src/addon-generator.ts
  packages/generators/src/init-generator.ts
  packages/generators/tsconfig.json
  packages/package-utils/CHANGELOG.md
  packages/package-utils/README.md
  packages/package-utils/__tests__/index.test.ts
  packages/package-utils/__tests__/packageUtils.test.ts
  packages/package-utils/package.json
  packages/package-utils/src/index.ts
  packages/package-utils/src/packageUtils.ts
  packages/package-utils/tsconfig.json
  packages/utils/__tests__/global-packages-path.test.ts
  packages/utils/package.json
  packages/utils/src/global-packages-path.ts
  packages/utils/src/index.ts
  packages/utils/src/modify-config-helper.ts
  packages/utils/src/npm-packages-exists.ts
  packages/utils/src/resolve-packages.ts
  packages/utils/src/scaffold.ts
  packages/utils/src/spawn-child.ts
  packages/utils/tsconfig.json
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/commands/resolveCommand.js
  packages/webpack-cli/lib/groups/resolveAdvanced.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/__tests__/get-package-manager.test.js
  packages/webpack-cli/lib/utils/__tests__/package-exists.test.js
  packages/webpack-cli/lib/utils/__tests__/prompt-installation.test.js
  packages/webpack-cli/lib/utils/__tests__/test-both/package-lock.json
  packages/webpack-cli/lib/utils/__tests__/test-both/yarn.lock
  packages/webpack-cli/lib/utils/__tests__/test-npm-lock/package-lock.json
  packages/webpack-cli/lib/utils/__tests__/test-yarn-lock/yarn.lock
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/get-package-manager.js
  packages/webpack-cli/lib/utils/package-exists.js
  packages/webpack-cli/lib/utils/prompt-installation.js
  packages/webpack-cli/lib/utils/run-command.js
  packages/webpack-cli/package.json
  tsconfig.json
  yarn.lock
Labels: PR: reviewed-approved

#1905 auto apply labels for issue templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: PR: reviewed-approved, PR: small

#1903 fix: add compilation lifecycle in watch instance
  package.json
  packages/webpack-cli/lib/utils/Compiler.js
  test/watch/watch-flag.test.js
Labels: PR: reviewed-approved

#1898 fix: handle compiler errors
  packages/webpack-cli/lib/utils/Compiler.js
  test/core-flags/devtool-flag.test.js
  test/invalid-schema/invalid-schema.test.js
  test/invalid-schema/webpack.config.mock.js
  test/stats/cli-flags/stats.test.js
  test/target/flag-test/target-flag.test.js
Labels: PR: reviewed-approved

#1900 feat: assign config paths in build dependencies in cache config
  packages/webpack-cli/lib/utils/flag-defaults.js
  packages/webpack-cli/lib/webpack-cli.js
  test/cache/cache.test.js
  test/cache/webpack.config.js
  test/core-flags/cache-flags.test.js
  test/core-flags/src/index.js
  test/core-flags/webpack.cache.config.js
  test/core-flags/webpack.config.js
Labels: PR: reviewed-approved

#1904 fix: cli-executer supplies args further up
  packages/webpack-cli/__tests__/cli-executer.test.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/cli-executer.js
Labels: PR: reviewed-approved, Semver: patch 🔧

#1906 docs: remove reference to package-utils (deprecated)
  packages/README.md
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small

#1907 tests: windows
  packages/webpack-cli/lib/utils/Compiler.js
  test/invalid-schema/invalid-schema.test.js
  test/stats/cli-flags/stats.test.js
Labels: PR: unreviewed

#1909 chore: fix peerDependencies
  packages/generate-loader/package.json
  packages/generate-plugin/package.json
  packages/generators/package.json
Labels: PR: reviewed-approved

#1913 chore: update release script
  .eslintrc.js
  bin/utils/validate-options.js
  package.json
  packages/generators/__tests__/utils/entry.test.ts
  packages/generators/__tests__/utils/languageSupport.test.ts
  packages/generators/__tests__/utils/plugins.test.ts
  packages/generators/__tests__/utils/styleSupport.test.ts
  packages/generators/templates/addon-package.json.js
  packages/generators/templates/package.json.js
  packages/migrate/src/commonsChunkPlugin/commonsChunkPlugin.ts
  packages/utils/__tests__/defineTest.ts
  packages/utils/__tests__/global-packages-path.test.ts
  packages/utils/src/npm-packages-exists.ts
  packages/webpack-cli/__tests__/init.test.js
  packages/webpack-cli/__tests__/serve/webpack.config.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/prompt-installation.js
  packages/webpack-scaffold/src/index.ts
  smoketests/watch/watch.array.smoketest.js
  smoketests/watch/watch.single.smoketest.js
  test/binCases/errors/v5-schema-validation/options.js
  test/binCases/errors/v5-schema-validation/validation.test.js
  test/config-format/typescript/typescript.test.js
  test/config/multiple/multiple-config.test.js
  test/entry/scss/scss.test.js
  test/info/info-output.test.js
  test/init/auto/init-auto.test.js
  test/init/force/init-force.test.js
  test/init/generator/init-inquirer.test.js
  test/init/language/css/init-language-css.test.js
  test/init/language/js/init-language-js.test.js
  test/init/multipleEntries/init-multipleEntries.test.js
  test/loader/loader.test.js
  test/migrate/config/bad-webpack.config.js
  test/mode/mode-single-arg/webpack.config.js
  test/no-stats/with-config/no-stats-with-config.test.js
  test/no-stats/with-config/webpack.config.js
  test/no-stats/with-flags/no-stats.test.js
  test/no-stats/with-flags/webpack.config.js
  test/progress/progress-flag.test.js
  test/serve/basic/webpack.config.js
  test/serve/with-custom-port/webpack.config.js
  test/stats/cli-flags/stats.test.js
Labels: PR: reviewed-approved, PR: small

#1920 fix: avoid unnecessary stringify
  .github/workflows/nodejs.yml
  .gitignore
  packages/webpack-cli/lib/utils/Compiler.js
  test/build-errors/errors.test.js
  test/build-errors/src/index.js
  test/build-warnings/src/index.js
  test/build-warnings/warnings.test.js
  test/json/json.test.js
Labels: PR: reviewed-approved, PR: small, PR: unreviewed

#1927 tests: relative configs
  test/config-lookup/relative/a.js
  test/config-lookup/relative/basic-config.test.js
  test/config-lookup/relative/webpack.config.js
Labels: PR: reviewed-approved

#1926 fix: support any config name
  packages/webpack-cli/lib/groups/ConfigGroup.js
  test/config-lookup/custom-name/a.js
  test/config-lookup/custom-name/config.webpack.js
  test/config-lookup/custom-name/custom-name.test.js
Labels: PR: unreviewed

#1944 fix: colored output
  package.json
  packages/webpack-cli/lib/utils/Compiler.js
  test/build-errors/errors.test.js
  test/build-warnings/warnings.test.js
  test/cache/cache.test.js
  test/colors/colors-false.webpack.config.js
  test/colors/colors-true.webpack.config.js
  test/colors/colors.test.js
  test/colors/no-stats.webpack.config.js
  test/colors/src/index.js
  test/colors/stats-boolean.webpack.config.js
  test/colors/stats-string.webpack.config.js
  test/core-flags/cache-flags.test.js
  test/watch/watch-flag.test.js
  yarn.lock
Labels: PR: unreviewed

#1945 fix: remove unnecessary optional peer dependencies
  packages/utils/package.json
Labels: PR: reviewed-approved, PR: small

#1947 chore: reduce package size
  packages/info/package.json
  packages/utils/package.json
  packages/webpack-cli/package.json
  yarn.lock
Labels: PR: reviewed-approved

#1950 fix: move init command to separate package
  packages/webpack-cli/lib/utils/__tests__/package-exists.test.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/resolve-command.js
  packages/webpack-cli/package.json
Labels: PR: reviewed-approved

#1951 fix: run CLI after webpack installation
  packages/webpack-cli/bin/cli.js
Labels: PR: reviewed-approved

#1949 fix: output stacktrace on errors
  .github/workflows/nodejs.yml
  packages/generators/src/addon-generator.ts
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/utils/errors/ConfigError.js
  packages/webpack-cli/lib/utils/logger.js
  test/config/absent/config-absent.test.js
  test/error/error.test.js
  test/error/src/index.js
  test/error/webpack.config.js
  test/merge/config-absent/merge-config-absent.test.js
  test/merge/config/merge-config.test.js
Labels: PR: reviewed-approved, PR: unreviewed

#1939 feat: allow passing strings in env flag
  packages/webpack-cli/lib/groups/ConfigGroup.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/config/type/function-with-env/function-with-env.test.js
  test/config/type/function-with-env/webpack.env.config.js
  test/config/type/promise-function/promise-function.test.js
Labels: PR: unreviewed

#1958 refactor: code
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/Compiler.js
  packages/webpack-cli/lib/utils/interactive.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#1971 refactor: code
  packages/webpack-cli/__tests__/cli-executer.test.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/cli-executer.js
  packages/webpack-cli/lib/utils/process-log.js
  test/watch/watch-flag.test.js
Labels: PR: reviewed-approved

#1972 fix: help and version functionality
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/arg-parser.js
  test/help/help-commands.test.js
  test/help/help-flags.test.js
Labels: PR: reviewed-approved

#1979 tests: for exit-code in case of error in config
  .eslintignore
  .prettierignore
  test/config/error/config-error.test.js
  test/config/error/src/index.js
  test/config/error/syntax-error.js
  test/config/error/webpack.config.js
Labels: PR: reviewed-approved

#1977 refactor: pass a callback to webpack from webpack-cli
  packages/webpack-cli/lib/plugins/WebpackCLIPlugin.js
  packages/webpack-cli/lib/webpack-cli.js
  test/core-flags/cache-flags.test.js
  test/utils/cli-plugin-test/plugin.test.js
Labels: PR: reviewed-approved

#1994 chore(deps): update
  package.json
  packages/generators/__tests__/utils/entry.test.ts
  packages/generators/__tests__/utils/languageSupport.test.ts
  packages/generators/__tests__/utils/plugins.test.ts
  packages/generators/__tests__/utils/styleSupport.test.ts
  packages/utils/__tests__/global-packages-path.test.ts
  test/core-flags/module-flags.test.js
  test/core-flags/optimization-flags.test.js
  test/core-flags/output-flags.test.js
  yarn.lock
Labels: PR: reviewed-approved

#1999 chore(deps): update
  package.json
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/package.json
  packages/generators/src/addon-generator.ts
  packages/migrate/package.json
  packages/utils/package.json
  packages/webpack-cli/package.json
  packages/webpack-scaffold/package.json
  yarn.lock
Labels: PR: reviewed-approved, PR: unreviewed

#2000 feat: progress supports string argument
  packages/webpack-cli/lib/plugins/WebpackCLIPlugin.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/progress/progress-flag.test.js
Labels: PR: reviewed-approved
