Repository webpack/webpack-cli, pull requests merged in 2020-04, with the labels that each got.

#1392 fix(generators): fix and refactor entry util, add tests
  packages/generators/__tests__/utils/entry.test.ts
  packages/generators/src/init-generator.ts
  packages/generators/src/utils/entry.ts
Labels: PR: reviewed-approved

#1382 chore: refactor info package
  packages/info/__tests__/.eslintrc
  packages/info/__tests__/index.test.ts
  packages/info/package.json
  packages/info/src/commands.ts
  packages/info/src/index.ts
  packages/info/src/options.ts
  packages/webpack-cli/lib/utils/cli-flags.js
  test/info/info-help.test.js
  test/info/info-multi-args.test.js
  test/info/info-output.test.js
Labels: PR: CI-ok, PR: reviewed-approved

#1385 fix(generators): fix small issues with generators
  .gitignore
  package.json
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/src/addon-generator.ts
  packages/generators/src/init-generator.ts
  packages/generators/src/utils/languageSupport.ts
  yarn.lock
Labels: PR: CI-not-ok, PR: reviewed-approved

#1357 docs: improving packages Readme
  packages/README.md
Labels: PR: CI-ok, PR: review-outdated

#1399 chore: refactor typescript configuration
  .github/workflows/nodejs.yml
  package.json
  packages/generate-loader/package.json
  packages/generate-loader/tsconfig.json
  packages/generate-plugin/package.json
  packages/generate-plugin/tsconfig.json
  packages/generators/package.json
  packages/generators/tsconfig.json
  packages/info/package.json
  packages/info/tsconfig.json
  packages/init/package.json
  packages/init/tsconfig.json
  packages/migrate/package.json
  packages/migrate/tsconfig.json
  packages/package-utils/package.json
  packages/package-utils/tsconfig.json
  packages/serve/package.json
  packages/serve/tsconfig.json
  packages/utils/package.json
  packages/utils/tsconfig.json
  packages/webpack-scaffold/package.json
  packages/webpack-scaffold/tsconfig.json
  scripts/buildPackages.js
  tsconfig.base.json
  tsconfig.json
  tsconfig.packages.json
  yarn.lock
Labels: PR: unreviewed

#1411 fix(webpack-cli): add value none in mode usage
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#1410 docs: fix loading doc link in loader-generator
  packages/generate-loader/templates/src/_index.js.tpl
Labels: PR: reviewed-approved, PR: reviewed-changes-requested, PR: small

#1409 chore: rm unused dirs in packages
  packages/generate-loader/examples/simple/src/index.js.tpl
  packages/generate-loader/examples/simple/src/lazy-module.js.tpl
  packages/generate-loader/examples/simple/src/static-esm-module.js.tpl
  packages/generate-loader/examples/simple/webpack.config.js.tpl
  packages/generate-loader/lib/_index.js.tpl
  packages/generate-loader/lib/cjs.js.tpl
  packages/generate-loader/test/fixtures/simple-file.js.tpl
  packages/generate-loader/test/functional.test.js.tpl
  packages/generate-loader/test/test-utils.js.tpl
  packages/generate-loader/test/unit.test.js.tpl
  packages/generate-plugin/examples/simple/_webpack.config.js.tpl
  packages/generate-plugin/examples/simple/src/index.js.tpl
  packages/generate-plugin/examples/simple/src/lazy-module.js.tpl
  packages/generate-plugin/examples/simple/src/static-esm-module.js.tpl
  packages/generate-plugin/lib/_index.js.tpl
  packages/generate-plugin/lib/cjs.js.tpl
  packages/generate-plugin/test/fixtures/simple-file.js.tpl
  packages/generate-plugin/test/functional.test.js.tpl
  packages/generate-plugin/test/test-utils.js.tpl
Labels: PR: reviewed-approved

#1403 chore: add info package to webpack-cli
  packages/webpack-cli/__tests__/info.test.js
  packages/webpack-cli/package.json
Labels: PR: reviewed-approved, PR: small

#1405 feat(webpack-cli): add alias for version
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/version/version-multi-args.test.js
  test/version/version-single-arg.test.js
Labels: PR: reviewed-approved

#1418 tests: add test for zero config
  test/stats/stats.test.js
  test/zero-config/entry-absent/zero-config.test.js
  test/zero-config/entry-present/src/index.js
  test/zero-config/entry-present/zero-config.test.js
  test/zero-config/with-config/index.js
  test/zero-config/with-config/webpack.config.js
  test/zero-config/with-config/zero-config-entry.test.js
Labels: PR: reviewed-approved

#1441 fix(webpack-cli): correct cli-flags usage
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#1439 chore(generators): improve generator Typescript types
  packages/generators/src/init-generator.ts
  packages/generators/src/types/index.ts
  packages/generators/src/utils/entry.ts
  packages/generators/src/utils/languageSupport.ts
  packages/generators/src/utils/styleSupport.ts
  packages/webpack-scaffold/src/index.ts
Labels: PR: reviewed-approved

#1449 misc(generators): remove unused import and fix type
  packages/generators/src/init-generator.ts
Labels: PR: reviewed-approved, PR: small

#1448 tests(generators): plugins util tests
  packages/generators/__tests__/plugin-generator.test.ts
  packages/generators/__tests__/utils/plugins.test.ts
  packages/generators/src/utils/plugins.ts
Labels: PR: reviewed-approved

#1446 tests: add more tests cases for serve
  test/serve/basic/index.js
  test/serve/basic/serve-basic.test.js
  test/serve/basic/webpack.config.js
  test/serve/with-custom-port/index.js
  test/serve/with-custom-port/serve-custom-config.test.js
  test/serve/with-custom-port/webpack.config.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#1445 tests(webpack-cli): add test for entry flag
  test/entry/flag-entry/entry-with-flag.test.js
  test/entry/flag-entry/src/a.js
Labels: PR: reviewed-approved

#1450 chore(init): remove unused transform files
  packages/init/src/init.ts
  packages/init/src/types/NodePath.ts
  packages/init/src/types/Transform.ts
  packages/init/src/types/index.ts
Labels: PR: reviewed-approved

#1421 feat(webpack-cli): --version for external packages
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
  test/version/version-external-packages.test.js
  test/version/version-multi-args.test.js
Labels: PR: reviewed-approved

#1455 tests(webpack-cli): correct node-test
  test/target/node/node-test.test.js
Labels: PR: reviewed-approved, PR: small

#1451 tests: add tests for test utils
  test/utils/index.js
  test/utils/test-utils.test.js
Labels: PR: reviewed-approved

#1460 fix: json flag, enable tests
  packages/webpack-cli/lib/groups/StatsGroup.js
  test/json/json.test.js
Labels: PR: reviewed-approved

#1452 tests: increase coverage for webpack-scaffold
  packages/webpack-scaffold/__tests__/index.test.ts
Labels: PR: reviewed-approved

#1464 chore(webpack-scaffold): use default params
  packages/webpack-scaffold/src/index.ts
Labels: PR: reviewed-approved, PR: small

#1419 tests: add tests for init
  .gitignore
  package.json
  packages/webpack-cli/.gitignore
  packages/webpack-cli/__tests__/init/auto/init-auto.test.js
  packages/webpack-cli/__tests__/init/coreFlags/init-flags.test.js
  packages/webpack-cli/__tests__/init/generator/init-inquirer.test.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#1471 tests(generators): added style support tests
  packages/generators/__tests__/utils/styleSupport.test.ts
Labels: PR: reviewed-approved

#1447 languageSupport tests
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/__tests__/utils/languageSupport.test.ts
  packages/generators/src/utils/languageSupport.ts
Labels: PR: review-outdated

#1477 chore: remove yo-rc on clean command
  package.json
Labels: PR: reviewed-approved, PR: small

#1476 tests: add tests for loader command
  packages/webpack-cli/__tests__/init/generator/init-inquirer.test.js
  test/loader/.gitignore
  test/loader/loader.test.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#1480 fix: consistent webpack plugin name throughout
  packages/webpack-cli/lib/utils/Compiler.js
Labels: PR: reviewed-approved, PR: small

#1473 test(generators): Add test case for production CSS config
  packages/generators/__tests__/utils/styleSupport.test.ts
Labels: PR: unreviewed

#1482 tests: remove temp loader directory before and after test
  .gitignore
  packages/webpack-cli/.gitignore
  test/init/auto/init-auto.test.js
  test/init/coreFlags/init-flags.test.js
  test/init/generator/init-inquirer.test.js
  test/loader/loader.test.js
Labels: PR: reviewed-approved, PR: small

#1496 docs(info): update --output flag
  packages/info/README.md
Labels: PR: reviewed-approved, PR: small

#1481 migrate to commander
  packages/info/src/index.ts
  packages/info/src/options.ts
  packages/serve/src/index.ts
  packages/webpack-cli/__tests__/arg-parser.test.js
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/groups/AdvancedGroup.js
  packages/webpack-cli/lib/groups/OutputGroup.js
  packages/webpack-cli/lib/groups/StatsGroup.js
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  packages/webpack-cli/lib/utils/arg-parser.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/utils/helpers.js
  packages/webpack-cli/lib/utils/parse-node-args.js
  packages/webpack-cli/lib/webpack-cli.js
  packages/webpack-cli/package.json
  test/config/basic/basic-config.test.js
  test/defaults/output-defaults.test.js
  test/entry/defaults-index/entry-multi-args.test.js
  test/global/global.test.js
  test/global/global1.js
  test/global/global2.js
  test/global/index.js
  test/init/generator/init-inquirer.test.js
  test/loader/loader.test.js
  test/mode/prod/prod.test.js
  test/no-mode/no-mode.test.js
  test/node/node.test.js
  test/output/named-bundles/output-named-bundles.test.js
  test/serve/basic/serve-basic.test.js
  test/stats/stats.test.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#1495 Fix migrate command
  packages/migrate/src/index.ts
  packages/utils/__tests__/run-prettier.test.ts
  packages/utils/src/run-prettier.ts
  test/init/generator/init-inquirer.test.js
  test/loader/loader.test.js
  test/migrate/config/bad-webpack.config.js
  test/migrate/config/migrate-config.test.js
  test/migrate/config/webpack.config.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#1499 chore: minor grammar fix in Bug_report.md
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: PR: reviewed-approved, PR: small

#1501 tests: test case to ensure writing to stdin
  test/utils/test-utils.test.js
Labels: PR: reviewed-approved, PR: small

#1483 tests: add tests for project root finder util
  packages/utils/__tests__/find-project-root/package.json
  packages/utils/__tests__/find-project-root/project/find-project-root.test.ts
  packages/utils/src/path-utils.ts
Labels: PR: reviewed-approved

#1503 chore(webpack-cli): remove --no-mode flag
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/groups/ZeroConfigGroup.js
  packages/webpack-cli/lib/utils/cli-flags.js
  test/no-mode/no-mode.test.js
  test/no-mode/src/index.js
Labels: PR: reviewed-approved

#1462 fix(webpack-cli): throw error for invalid args with HelpGroup
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/groups/HelpGroup.js
  packages/webpack-cli/lib/utils/unknown-args.js
  packages/webpack-cli/lib/webpack-cli.js
  test/help/help-commands.test.js
  test/help/help-flags.test.js
  test/help/help-multi-args.test.js
  test/help/help-single-arg.test.js
  test/version/version-external-packages.test.js
  test/version/version-multi-args.test.js
  test/version/version-single-arg.test.js
Labels: PR: reviewed-approved
