Repository webpack/webpack-cli, pull requests merged in 2021-12, with the labels that each got.

#3042 chore: add Yarn cache to CI runs
  .github/workflows/nodejs.yml
Labels: PR: small, PR: reviewed-approved

#3048 chore: ignore eslint no-explicit-any warning
  packages/serve/src/types.ts
Labels: PR: small, PR: reviewed-approved

#3046 ci: do not install deps twice
  .github/workflows/nodejs.yml
Labels: PR: unreviewed, PR: small

#3053 chore: typo fixes with cSpell
  packages/generators/src/handlers/default.ts
  test/build/config/defaults/cjs-config/default-cjs-config.test.js
  test/build/config/defaults/mjs-config/default-mjs-config.test.js
  test/build/stats/config/stats.test.js
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
  test/help/help.test.js
  test/serve/basic/same-ports-dev-server.config.js
  test/serve/basic/serve-basic.test.js
  test/utils/test-utils.js
  test/utils/test-utils.test.js
Labels: PR: reviewed-approved

#3052 chore: expand lint-staged prettier glob
  lint-staged.config.js
Labels: PR: small, PR: reviewed-approved

#3056 ci: add Node 17
  .github/workflows/nodejs.yml
Labels: PR: unreviewed, PR: small

#3058 chore: add cSpell to check spelling issues
  .cspell.json
  lint-staged.config.js
  open-bot.yml
  package.json
  test/build/basic/basic.test.js
  test/build/cache/src/main.js
  test/build/colors/colors.test.js
  test/build/core-flags/core-flags.test.js
  test/build/unknown/unknown.test.js
  test/utils/test-utils.js
  yarn.lock
Labels: PR: reviewed-approved

#3061 chore: cleanup `.gitignore`, `.eslintignore`, and `.prettierignore`
  .cspell.json
  .eslintignore
  .gitignore
  .prettierignore
Labels: PR: reviewed-approved

#3065 docs: update webpack options
  OPTIONS.md
Labels: PR: small, PR: reviewed-approved

#3064 chore: update node image to 16
  .devcontainer/Dockerfile
Labels: PR: small, PR: reviewed-approved

#3068 ci: fix
  test/build/target/flag-test/index.js
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer4.webpack4
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer4.webpack5
  test/serve/basic/serve-basic.test.js
Labels: PR: small, PR: reviewed-approved

#3070 chore: update`cspell` configuration
  .cspell.json
Labels: PR: small, PR: reviewed-approved

#3067 docs: update server options
  SERVE-OPTIONS-v4.md
Labels: PR: reviewed-approved
