Repository webpack/webpack-cli, pull requests merged in 2021-05, with the labels that each got.

#2683 docs: add more information
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved

#2682 feat: upgrade to GitHub native dependabot
  .github/dependabot.yml
Labels: PR: reviewed-approved, PR: small

#2688 test: cleanup
  test/build/basic/basic.test.js
  test/build/build-variable/build-variable.test.js
  test/build/bundle-variable/bundle-variable.test.js
  test/build/config-format/commonjs-default/commonjs-default.test.js
  test/build/config-format/commonjs/commonjs.test.js
  test/build/config-lookup/dotfolder-array/dotfolder-array.test.js
  test/build/config-lookup/dotfolder-single/dotfolder-single.test.js
  test/build/config-lookup/relative/basic-config.test.js
  test/build/config-name/config-name.test.js
  test/build/config/absent/config-absent.test.js
  test/build/config/basic/basic-config.test.js
  test/build/config/defaults/basic-config/default-js-config.test.js
  test/build/config/defaults/cjs-config/default-cjs-config.test.js
  test/build/config/defaults/dot-webpack-directory-webpackfile/multiple-location-config.test.js
  test/build/config/defaults/dot-webpack-directory/dev-none-config.test.js
  test/build/config/defaults/with-mode/multiple-config.test.js
  test/build/config/invalid-path/invalid-path.test.js
  test/build/config/multiple-with-one-compilation/multiple-with-one-compilation.test.js
  test/build/config/multiple/multiple-config.test.js
  test/build/config/no-config-array/no-config-array.test.js
  test/build/config/no-config-object/no-config-object.test.js
  test/build/config/type/array-function-with-argv/function-with-argv.test.js
  test/build/config/type/array-function-with-env/array-function-with-env.test.js
  test/build/config/type/array-functions/array-functions.test.js
  test/build/config/type/array-promises/array-promises.test.js
  test/build/config/type/array/array.test.js
  test/build/config/type/function-array/function-array.test.js
  test/build/config/type/function-async/function-async.test.js
  test/build/config/type/function-promise/function-promise.test.js
  test/build/config/type/function-with-argv/function-with-argv.test.js
  test/build/config/type/function/function.test.js
  test/build/config/type/promise-array/promise-array.test.js
  test/build/config/type/promise-function/promise-function.test.js
  test/build/config/type/promise/promise.test.js
  test/build/defaults/output-defaults.test.js
  test/build/devtool/array/source-map-array.test.js
  test/build/devtool/object/source-map-object.test.js
  test/build/entry/config-entry/entry-with-config/entry-with-config.test.js
  test/build/entry/config-entry/entry-with-index/entry-with-config.test.js
  test/build/merge/config-absent/merge-config-absent.test.js
  test/build/merge/config/merge-config.test.js
  test/build/mode/mode-with-config/mode-with-config.test.js
  test/build/name/name.test.js
  test/build/output/output-named-bundles.test.js
  test/build/prefetch/prefetch.test.js
  test/build/zero-config/entry-absent/zero-config.test.js
  test/build/zero-config/entry-present/zero-config.test.js
  test/info/info-output.test.js
  test/info/info-unknown.test.js
  test/loader/loader.test.js
  test/plugin/plugin.test.js
  test/utils/test-utils.test.js
Labels: PR: reviewed-approved

#2687 chore(generators): send warning regarding invalid template to stderr
  packages/generators/src/init-generator.ts
  test/init/init.test.js
Labels: PR: reviewed-approved, PR: small

#2704 chore: upgrade webpack
  OPTIONS.md
  package.json
  test/build/core-flags/output-flags.test.js
  yarn.lock
Labels: PR: reviewed-approved

#2705 docs: update
  OPTIONS.md
  SERVE-OPTIONS.md
Labels: PR: reviewed-approved

#2707 test(init): update descriptions
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
  test/init/init.test.js
Labels: PR: reviewed-approved

#2700 feat(generators): add aliases for options
  INIT.md
  packages/generators/src/index.ts
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
  test/init/init.test.js
Labels: PR: reviewed-approved

#2709 feat(init): add alias for --output
  packages/info/README.md
  packages/info/src/index.ts
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
  test/info/info-output.test.js
Labels: PR: reviewed-approved

#2710 fix: husky config
  .husky/commit-msg
Labels: PR: reviewed-approved, PR: small

#2714 test: increase coverage
  test/loader/loader.test.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved

#2715 chore(deps): update
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2720 test: fix warning
  test/build/core-flags/experiments-flag.test.js
Labels: PR: reviewed-approved, PR: small

#2718 refactor: loading packages
  packages/serve/src/startDevServer.ts
  packages/webpack-cli/lib/webpack-cli.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved, PR: unreviewed

#2722 feat(init-generator): configure workbox-webpack-plugin as opted
  INIT.md
  packages/generators/init-template/default/template.html
  packages/generators/init-template/default/template.html.tpl
  packages/generators/init-template/default/webpack.configjs.tpl
  packages/generators/src/handlers/default.ts
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
  test/init/init.test.js
Labels: PR: reviewed-approved

#2729 chore: upgrade webpack
  package.json
  test/build/core-flags/module-flags.test.js
  yarn.lock
Labels: PR: reviewed-approved

#2730 refactor: ensure consistency
  .eslintrc.js
  packages/generators/src/handlers/default.ts
  packages/webpack-cli/lib/webpack-cli.js
  smoketests/helpers.js
  test/build/core-flags/snapshot-flags.test.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved

#2741 chore: update webpack
  OPTIONS.md
  package.json
  test/build/core-flags/module-flags.test.js
  yarn.lock
Labels: PR: reviewed-approved
