Repository webpack/webpack-cli, pull requests merged in 2021-04, with the labels that each got.

#2588 chore: remove version logging spam in each test
  scripts/snapshotResolver.js
Labels: PR: reviewed-approved, PR: small

#2571 feat: add support for mini-css-extract-plugin on demand
  packages/generators/init-template/default/webpack.configjs.tpl
  packages/generators/src/handlers/default.ts
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
  test/init/init.test.js
Labels: PR: reviewed-approved

#2590 chore: fix CI
  test/build/build-variable/build-variable.test.js
  test/init/init.test.js
Labels: PR: reviewed-approved, PR: small

#2591 test: resolve todos
  test/build/cache/cache.test.js
  test/build/config-format/mjs/mjs.test.js
  test/build/config-lookup/custom-name/custom-name.test.js
  test/build/config/defaults/mjs-config/default-mjs-config.test.js
  test/build/config/error-mjs/config-error.test.js
  test/build/core-flags/cache-flags.test.js
  test/build/node/node.test.js
Labels: PR: reviewed-approved

#2584 test: ts esnext
  test/build/config-format/typescript-esnext/main.ts
  test/build/config-format/typescript-esnext/package.json
  test/build/config-format/typescript-esnext/tsconfig.json
  test/build/config-format/typescript-esnext/typescript.test.js
  test/build/config-format/typescript-esnext/webpack.config.ts
Labels: PR: reviewed-approved

#2594 fix: update usage info
  OPTIONS.md
  packages/generators/src/index.ts
  packages/webpack-cli/README.md
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
  test/help/help.test.js
Labels: PR: reviewed-approved

#2593 test: add assertion for exit code
  test/serve/basic/serve-basic.test.js
Labels: PR: reviewed-approved, PR: small

#2567 test: enable skipped help tests
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
  test/help/help.test.js
Labels: PR: unreviewed

#2600 fix: broken URL in generated webpack.config.js
  packages/generators/init-template/default/webpack.configjs.tpl
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: unreviewed

#2604 test: coverage
  jest.config.js
  package.json
  smoketests/helpers.js
  smoketests/missing-packages/webpack-dev-server.test.js
Labels: PR: reviewed-approved

#2603 fix: `configs` property for `--devtool`
  packages/webpack-cli/lib/webpack-cli.js
  test/build/devtool/array/source-map-array.test.js
  test/build/devtool/array/webpack.config.js
  test/build/devtool/object/source-map-object.test.js
  test/build/devtool/object/webpack.eval.config.js
  test/build/devtool/object/webpack.source.config.js
  test/help/__snapshots__/help.test.js.snap.webpack4
Labels: PR: reviewed-approved

#2538 feat: use own inquirer implementation
  packages/webpack-cli/lib/utils/__tests__/get-package-manager.test.js
  packages/webpack-cli/lib/utils/__tests__/prompt-installation.test.js
  packages/webpack-cli/lib/utils/prompt-installation.js
  packages/webpack-cli/lib/utils/prompt.js
  packages/webpack-cli/package.json
  yarn.lock
Labels: PR: reviewed-approved

#2610 test: remove test folder from code coverage result
  jest.config.js
Labels: PR: reviewed-approved, PR: small

#2614 fix: add node env as prod in default template
  packages/generators/init-template/default/package.json.js
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2611 test: removed forceExit option from jest
  package.json
  test/utils/test-utils.js
  test/watch/analyze/analyze-flag.test.js
  test/watch/basic/basic.test.js
  test/watch/stdin/stdin.test.js
  test/watch/watch-variable/watch-variable.test.js
Labels: PR: reviewed-approved, PR: small

#2616 feat: add `create` and `new` alias for `init`
  OPTIONS.md
  package.json
  packages/generators/src/index.ts
  packages/webpack-cli/lib/webpack-cli.js
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
  test/help/help.test.js
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
  test/init/init.test.js
  yarn.lock
Labels: PR: unreviewed

#2621 refactor: remove `--no-force` option for `init`
  packages/generators/src/index.ts
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2622 test: add missing snapshot entry
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
  test/init/init.test.js
Labels: PR: reviewed-approved

#2625 fix: update devServerOptions type
  packages/serve/src/types.ts
Labels: PR: reviewed-approved

#2623 test: moves all tests to `test` folder, removes duplicates
  .gitignore
  jest.config.js
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/__tests__/loader-generator.test.ts
  packages/generators/__tests__/plugin-generator.test.ts
  test/api/__snapshots__/scaffold-utils.test.js.snap.webpack4
  test/api/__snapshots__/scaffold-utils.test.js.snap.webpack5
  test/api/get-package-manager.test.js
  test/api/prompt-installation.test.js
  test/api/scaffold-utils.test.js
  test/api/test-all-lock/package-lock.json
  test/api/test-all-lock/pnpm-lock.yaml
  test/api/test-all-lock/yarn.lock
  test/api/test-npm-and-pnpm/package-lock.json
  test/api/test-npm-and-pnpm/pnpm-lock.yaml
  test/api/test-npm-and-yarn/package-lock.json
  test/api/test-npm-and-yarn/yarn.lock
  test/api/test-npm-lock/package-lock.json
  test/api/test-pnpm-lock/pnpm-lock.yaml
  test/api/test-yarn-and-pnpm/pnpm-lock.yaml
  test/api/test-yarn-and-pnpm/yarn.lock
  test/api/test-yarn-lock/yarn.lock
Labels: PR: reviewed-approved

#2624 fix(serve): do not set port for modern client
  packages/serve/src/startDevServer.ts
Labels: PR: small, PR: unreviewed

#2627 docs: add init aliases
  README.md
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved

#2457 test: refactor test utils
  test/build/entry/scss/scss.test.js
  test/init/init.test.js
  test/loader/loader.test.js
  test/plugin/plugin.test.js
  test/utils/test-utils.js
  test/utils/test-utils.test.js
Labels: PR: reviewed-approved

#2585 feat: add support for mode specific config
  packages/generators/init-template/default/.babelrc
  packages/generators/init-template/default/webpack.configjs.tpl
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2633 chore: remove spammy console statements
  test/build/config/type/array-function-with-argv/webpack.config.js
  test/build/config/type/array-function-with-env/webpack.config.js
  test/build/core-flags/watch-flags.test.js
Labels: PR: reviewed-approved

#2635 chore: update husky to v6
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  husky.config.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2634 chore(deps): update
  .eslintrc.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2631 feat: add `server` alias for `serve` command
  OPTIONS.md
  README.md
  SERVE-OPTIONS.md
  packages/serve/src/index.ts
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/webpack-cli.js
  test/build/unknown/unknown.test.js
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
  test/help/help.test.js
Labels: PR: reviewed-approved, PR: unreviewed

#2636 docs: update INIT.md
  INIT.md
Labels: PR: reviewed-approved, PR: small

#2638 docs: update init generator questions
  INIT.md
Labels: PR: reviewed-approved, PR: small

#2637 refactor(generators): remove unnecessary helpers
  packages/generators/src/addon-generator.ts
  packages/generators/src/utils/copy-utils.ts
Labels: PR: reviewed-approved

#2639 fix : fix comment typo in webpack.config.js template file
  packages/generators/init-template/default/webpack.configjs.tpl
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2643 fix: improve parsing of `--env` flag
  packages/webpack-cli/lib/webpack-cli.js
  test/build/config/type/function-with-env/function-with-env.test.js
  test/build/config/type/function-with-env/webpack.config.js
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
  test/help/help.test.js
Labels: PR: reviewed-approved

#2645 chore: remove stale deps
  packages/generators/package.json
  yarn.lock
Labels: PR: reviewed-approved

#2632 Refactor test
  .github/workflows/nodejs.yml
  package.json
  packages/webpack-cli/lib/plugins/CLIPlugin.js
  packages/webpack-cli/lib/webpack-cli.js
  scripts/snapshotResolver.js
  test/build/mode/mode-with-config/index.js
  test/build/mode/mode-with-config/mode-with-config.test.js
  test/build/mode/mode-with-config/package.json
  test/build/mode/mode-with-config/src/index.js
  test/build/mode/mode-with-config/webpack.config.js
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
  test/help/help.test.js
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer3.webpack4
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer3.webpack5
  test/serve/basic/serve-basic.test.js
  test/serve/invalid-schema/__snapshots__/invalid-schema.test.js.snap.devServer3.webpack4
  test/serve/invalid-schema/__snapshots__/invalid-schema.test.js.snap.devServer3.webpack5
  test/serve/invalid-schema/invalid-schema.test.js
  test/serve/serve-variable/__snapshots__/serve-basic.test.js.snap.devServer3.webpack4
  test/serve/serve-variable/__snapshots__/serve-basic.test.js.snap.devServer3.webpack5
  test/serve/serve-variable/serve-basic.test.js
  test/serve/with-custom-port/__snapshots__/serve-custom-config.test.js.snap.devServer3.webpack4
  test/serve/with-custom-port/__snapshots__/serve-custom-config.test.js.snap.devServer3.webpack5
  test/serve/with-custom-port/serve-custom-config.test.js
  test/utils/test-utils.js
  test/version/__snapshots__/version.test.js.snap.webpack4
  test/version/__snapshots__/version.test.js.snap.webpack5
  test/version/version.test.js
  yarn.lock
Labels: PR: reviewed-approved, PR: unreviewed

#2649 docs: fix links on npm
  packages/configtest/package.json
  packages/generators/package.json
  packages/info/package.json
  packages/serve/README.md
  packages/serve/package.json
  packages/webpack-cli/README.md
  packages/webpack-cli/package.json
Labels: PR: reviewed-approved

#2648 fix: avoid unnecessary searching port
  packages/serve/src/startDevServer.ts
Labels: PR: reviewed-approved

#2647 Test refactor
  test/build/start-finish-force-log/start-finish-force-log.test.js
  test/init/init.test.js
  test/loader/loader.test.js
  test/plugin/plugin.test.js
  test/serve/basic/serve-basic.test.js
  test/utils/test-utils.js
  test/utils/test-utils.test.js
  test/watch/analyze/analyze-flag.test.js
  test/watch/basic/basic.test.js
  test/watch/stdin/stdin.test.js
  test/watch/watch-variable/watch-variable.test.js
Labels: PR: unreviewed

#2644 feat: allow extract plugin for production only
  packages/generators/init-template/default/webpack.configjs.tpl
  packages/generators/src/handlers/default.ts
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2646 test: refactor core-flags
  test/build/core-flags/experiments-flag.test.js
  test/build/core-flags/externals-flags.test.js
  test/build/core-flags/module-flags.test.js
  test/build/core-flags/optimization-flags.test.js
  test/build/core-flags/output-flags.test.js
  test/build/core-flags/performance-flags.test.js
  test/build/core-flags/resolve-flags.test.js
  test/build/core-flags/snapshot-flags.test.js
  test/build/core-flags/stats-flags.test.js
  test/build/core-flags/watch-flags.test.js
  test/utils/test-utils.js
Labels: PR: reviewed-approved

#2653 refactor: code
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#2650 fix: handle redundant timeouts in smoketest helpers
  smoketests/helpers.js
Labels: PR: reviewed-approved

#2659 feat: added support arguments description
  packages/generators/src/index.ts
  packages/webpack-cli/lib/webpack-cli.js
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
Labels: PR: reviewed-approved

#2652 refactor: backward compatible flags for dev server
  packages/serve/src/index.ts
Labels: PR: reviewed-approved, PR: unreviewed

#2658 test: snapshots more
  package.json
  test/configtest/with-config-path/__snapshots__/with-config-path.test.js.snap.webpack4
  test/configtest/with-config-path/__snapshots__/with-config-path.test.js.snap.webpack5
  test/configtest/with-config-path/syntax-error.config.js
  test/configtest/with-config-path/with-config-path.test.js
  test/configtest/without-config-path-custom-extension/__snapshots__/without-config-path.test.js.snap.webpack4
  test/configtest/without-config-path-custom-extension/__snapshots__/without-config-path.test.js.snap.webpack5
  test/configtest/without-config-path-custom-extension/without-config-path.test.js
  test/configtest/without-config-path-error/__snapshots__/without-config-path-error.test.js.snap.webpack4
  test/configtest/without-config-path-error/__snapshots__/without-config-path-error.test.js.snap.webpack5
  test/configtest/without-config-path-error/without-config-path-error.test.js
  test/configtest/without-config-path-multi-compiler-mode/__snapshots__/without-config-path-multi-compiler-mode.test.js.snap.webpack4
  test/configtest/without-config-path-multi-compiler-mode/__snapshots__/without-config-path-multi-compiler-mode.test.js.snap.webpack5
  test/configtest/without-config-path-multi-compiler-mode/without-config-path-multi-compiler-mode.test.js
  test/configtest/without-config-path-no-configuration/__snapshots__/without-config-path-no-configuration.test.js.snap.webpack4
  test/configtest/without-config-path-no-configuration/__snapshots__/without-config-path-no-configuration.test.js.snap.webpack5
  test/configtest/without-config-path-no-configuration/without-config-path-no-configuration.test.js
  test/configtest/without-config-path/__snapshots__/without-config-path.test.js.snap.webpack4
  test/configtest/without-config-path/__snapshots__/without-config-path.test.js.snap.webpack5
  test/configtest/without-config-path/without-config-path.test.js
  test/utils/test-utils.js
  test/watch/analyze/analyze-flag.test.js
  test/watch/watch-variable/watch-variable.test.js
  yarn.lock
Labels: PR: unreviewed

#2640 feat: prettify generated config
  packages/generators/package.json
  packages/generators/src/handlers/default.ts
  packages/generators/src/init-generator.ts
  packages/generators/src/types/index.ts
  smoketests/helpers.js
  smoketests/index.js
  smoketests/missing-packages/prettier.test.js
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2666 test: more snapshot testing
  test/build/hot/__snapshots__/hot-flag.test.js.snap.webpack4
  test/build/hot/__snapshots__/hot-flag.test.js.snap.webpack5
  test/build/hot/hot-flag.test.js
  test/build/output/__snapshots__/output-named-bundles.test.js.snap.webpack4
  test/build/output/__snapshots__/output-named-bundles.test.js.snap.webpack5
  test/build/output/output-named-bundles.test.js
  test/build/stats/flags/__snapshots__/stats.test.js.snap.webpack4
  test/build/stats/flags/__snapshots__/stats.test.js.snap.webpack5
  test/build/stats/flags/stats.test.js
  test/build/target/flag-test/__snapshots__/target-flag.test.js.snap.webpack4
  test/build/target/flag-test/__snapshots__/target-flag.test.js.snap.webpack5
  test/build/target/flag-test/target-flag.test.js
  test/build/target/node/__snapshots__/node-test.test.js.snap.webpack4
  test/build/target/node/__snapshots__/node-test.test.js.snap.webpack5
  test/build/target/node/node-test.test.js
  test/build/unknown/__snapshots__/unknown.test.js.snap.webpack4
  test/build/unknown/__snapshots__/unknown.test.js.snap.webpack5
  test/build/unknown/unknown.test.js
Labels: PR: reviewed-approved

#2662 chore: fix devServer types
  packages/serve/src/types.ts
Labels: PR: reviewed-approved, PR: small

#2669 chore: cleanup CI logs
  test/api/get-package-manager.test.js
  test/api/prompt-installation.test.js
  test/build/mode/mode-with-config/mode-with-config.test.js
  test/build/mode/mode-with-config/webpack.config2.js
  test/build/mode/mode-with-config/webpack.config3.js
Labels: PR: reviewed-approved

#2668 test: update
  test/api/capitalizeFirstLetter.test.js
  test/api/prompt.test.js
  test/build/config/type/function-with-env/function-with-env.test.js
Labels: PR: reviewed-approved

#2674 refactor(generators): remove extraneous args to addon-generator
  packages/generators/src/addon-generator.ts
  packages/generators/src/loader-generator.ts
  packages/generators/src/plugin-generator.ts
Labels: PR: reviewed-approved

#2677 docs: remove `webpack-scaffold`
  README.md
Labels: PR: reviewed-approved, PR: small

#2678 docs: remove scaffold guide
  README.md
Labels: PR: reviewed-approved, PR: small
