Repository webpack/webpack-cli, pull requests merged in 2021-03, with the labels that each got.

#2470 docs: fix a typo at contrbuting readme file
  .github/CONTRIBUTING.md
Labels: PR: reviewed-approved, PR: small

#2473 docs: update bootstrap command
  .github/CONTRIBUTING.md
Labels: PR: reviewed-approved, PR: small

#2488 chore: update webpack
  package.json
  test/core-flags/output-flags.test.js
  yarn.lock
Labels: PR: reviewed-approved, PR: small

#2482 fix: improve error message
  packages/webpack-cli/lib/webpack-cli.js
  smoketests/index.js
  smoketests/missing-command-help/generator.test.js
Labels: PR: reviewed-approved

#2495 feat: add support for multiple test cases
  smoketests/index.js
  smoketests/missing-command-packages/generator.test.js
  smoketests/missing-packages/webpack-dev-server.test.js
  smoketests/missing-packages/webpack.test.js
Labels: PR: reviewed-approved

#2497 chore: update webpack to v5.25.0
  package.json
  test/core-flags/module-flags.test.js
  test/core-flags/output-flags.test.js
  yarn.lock
Labels: PR: reviewed-approved

#2500 test: smoketest for init without generators
  smoketests/missing-command-packages/generator.test.js
Labels: PR: reviewed-approved

#2502 test: add serve smoketest
  smoketests/index.js
  smoketests/missing-command-packages/serve.test.js
Labels: PR: reviewed-approved

#2455 fix: assinging `type` for core flags
  .github/workflows/nodejs.yml
  OPTIONS.md
  packages/webpack-cli/lib/webpack-cli.js
  test/core-flags/experiments-flag.test.js
  test/core-flags/mock/mock.js
  test/core-flags/module-flags.test.js
  test/core-flags/optimization-flags.test.js
  test/core-flags/output-flags.test.js
  test/core-flags/performance-flags.test.js
  test/core-flags/resolve-flags.test.js
  test/core-flags/snapshot-flags.test.js
  test/core-flags/stats-flags.test.js
  test/core-flags/watch-flags.test.js
  test/help/help.test.js
Labels: PR: unreviewed

#2444 feat: allow string value for '--hot'
  OPTIONS.md
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/webpack-cli.js
  test/hot/hot-flag.test.js
Labels: PR: reviewed-approved

#2438 chore: improve updateDocs script for `serve`
  SERVE-OPTIONS.md
  packages/serve/README.md
  scripts/updateDocs.js
Labels: PR: reviewed-approved

#2510 test: add smoketest for missing info
  smoketests/index.js
  smoketests/missing-command-packages/info.test.js
Labels: PR: reviewed-approved

#2519 refactor: leverage helpers for smoketests
  smoketests/helpers.js
  smoketests/missing-command-packages/generator.test.js
  smoketests/missing-command-packages/info.test.js
  smoketests/missing-command-packages/serve.test.js
  smoketests/missing-packages/webpack-dev-server.test.js
  smoketests/missing-packages/webpack.test.js
Labels: PR: reviewed-approved

#2520 chore: remove stale type information
  packages/generators/src/types/index.ts
Labels: PR: reviewed-approved

#2521 chore: fix types package dep
  package.json
  yarn.lock
Labels: PR: reviewed-approved, PR: small

#2527 test: for missing `webpack-bundle-analyzer`
  smoketests/index.js
  smoketests/missing-packages/webpack-bundle-analyzer.test.js
Labels: PR: reviewed-approved

#2525 fix: comment on config resolution priority
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved, PR: small

#2530 test: fix help tests
  test/help/help.test.js
Labels: PR: reviewed-approved

#2508 fix: migrate package options to new format
  packages/generators/src/index.ts
  packages/info/src/index.ts
  packages/webpack-cli/lib/webpack-cli.js
  test/api/CLI.test.js
Labels: PR: reviewed-approved

#2539 test: add smoketest for configtest package
  smoketests/index.js
  smoketests/missing-command-packages/configtest.test.js
Labels: PR: reviewed-approved

#2534 Issue 2529
  .github/workflows/nodejs.yml
  OPTIONS.md
  SERVE-OPTIONS.md
  packages/generators/src/index.ts
  packages/webpack-cli/lib/webpack-cli.js
  test/help/help.test.js
Labels: PR: reviewed-approved

#2526 feat: add postcss support to default template
  packages/generators/init-template/default/postcss.config.js
  packages/generators/init-template/default/webpack.configjs.tpl
  packages/generators/src/handlers/default.ts
  test/init/init.test.js
Labels: PR: reviewed-approved

#2536 test: assert for config file content
  test/init/init.test.js
Labels: PR: reviewed-approved

#2542 test: refactor smoketests
  smoketests/helpers.js
  smoketests/index.js
  smoketests/missing-command-packages/configtest.test.js
  smoketests/missing-command-packages/generator.test.js
  smoketests/missing-command-packages/info.test.js
  smoketests/missing-command-packages/serve.test.js
  smoketests/missing-packages/webpack-bundle-analyzer.test.js
  smoketests/missing-packages/webpack-dev-server.test.js
  smoketests/missing-packages/webpack.test.js
Labels: PR: reviewed-approved

#2528 fix: description for `init` command
  OPTIONS.md
  README.md
  packages/generators/src/index.ts
  packages/webpack-cli/README.md
Labels: PR: review-outdated

#2546 feat: add env var to skip local import
  packages/webpack-cli/bin/cli.js
  test/build/import-local/import-local.test.js
  test/build/import-local/src/index.js
Labels: PR: reviewed-approved

#2547 test: use snapshot testing for the init test suite
  test/init/__snapshots__/init.test.js.snap
  test/init/init.test.js
Labels: PR: reviewed-approved

#2491 test: add snapshot tests for help
  jest.config.js
  packages/generators/__tests__/utils/__snapshots__/scaffold-utils.test.ts.snap.webpack4
  packages/generators/__tests__/utils/__snapshots__/scaffold-utils.test.ts.snap.webpack5
  scripts/snapshotResolver.js
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
  test/help/help.test.js
Labels: PR: reviewed-approved

#2549 fix: add version snapshots for init
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2545 test: configures html-webpack-plugin as opted with init
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
  test/init/init.test.js
Labels: PR: reviewed-approved

#2554 fix(info): grammar in description of `--output`
  packages/info/README.md
  packages/info/src/index.ts
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2550 feat: add additional scripts to init template
  packages/generators/init-template/default/package.json.js
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2553 build: add bootstrap step in workflow
  .github/workflows/nodejs.yml
Labels: PR: small, PR: unreviewed

#2557 test: update snapshots
  .github/workflows/nodejs.yml
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2556 feat: add `WEBPACK_PACKAGE` env var to use custom `webpack` package
  packages/webpack-cli/lib/webpack-cli.js
  test/build/custom-webpack/custom-webpack.js
  test/build/custom-webpack/custom-webpack.test.js
  test/build/custom-webpack/src/index.js
  test/build/custom-webpack/webpack.config.js
Labels: PR: reviewed-approved

#2555 fix: generation of `negative` flags
  packages/webpack-cli/lib/webpack-cli.js
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2563 chore: ignore tests from npm
  .npmignore
  packages/webpack-cli/package.json
  smoketests/index.js
  test/build/analyze/analyze.config.js
  test/build/cache/cache.test.js
  test/build/core-flags/cache-flags.test.js
  test/build/entry/scss/webpack.config.js
  test/build/env/array/array-env.test.js
  test/build/env/object/object-env.test.js
  test/build/prefetch/prefetch.test.js
  test/help/help.test.js
  test/init/init.test.js
  test/loader/loader.test.js
  test/plugin/plugin.test.js
  test/serve/basic/multi-dev-server.config.js
  test/serve/basic/serve-basic.test.js
  test/serve/serve-variable/serve-basic.test.js
  test/serve/with-custom-port/serve-custom-config.test.js
  test/utils/test-utils.js
  test/utils/test-utils.test.js
  test/version/version.test.js
  test/watch/analyze/analyze.config.js
Labels: PR: reviewed-approved, PR: small

#2569 fix(generators): use correct exit code
  packages/generators/src/init-generator.ts
Labels: PR: reviewed-approved, PR: small

#2566 feat: add flag to force start finish log
  packages/webpack-cli/lib/plugins/CLIPlugin.js
  test/build/start-finish-force-log/src/index.js
  test/build/start-finish-force-log/start-finish-force-log.test.js
  test/build/start-finish-force-log/webpack.config.array.js
  test/build/start-finish-force-log/webpack.config.js
Labels: PR: reviewed-approved, PR: small

#2568 chore: upgrade lerna to v4
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2562 test: migrate version tests
  test/version/__snapshots__/version.test.js.snap.webpack4
  test/version/__snapshots__/version.test.js.snap.webpack5
  test/version/version.test.js
Labels: PR: reviewed-approved

#2570 fix: imports in generator
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/__tests__/loader-generator.test.ts
  packages/generators/__tests__/plugin-generator.test.ts
  packages/generators/src/addon-generator.ts
  packages/generators/src/index.ts
  packages/generators/src/init-generator.ts
Labels: PR: reviewed-approved

#2574 test: init generator throws if the path is not writable
  test/init/init.test.js
Labels: PR: reviewed-approved

#2572 feat: make extention case insensitive
  packages/generators/init-template/default/webpack.configjs.tpl
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2577 fix: webpack config for `babel-loader` and `ts-loader`
  packages/generators/init-template/default/webpack.configjs.tpl
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#2576 feat: add --template flag for addon generator
  README.md
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/__tests__/loader-generator.test.ts
  packages/generators/__tests__/plugin-generator.test.ts
  packages/generators/loader-template/default/examples/simple/src/index.js.tpl
  packages/generators/loader-template/default/examples/simple/src/lazy-module.js.tpl
  packages/generators/loader-template/default/examples/simple/src/static-esm-module.js.tpl
  packages/generators/loader-template/default/examples/simple/webpack.config.js.tpl
  packages/generators/loader-template/default/src/_index.js.tpl
  packages/generators/loader-template/default/src/cjs.js.tpl
  packages/generators/loader-template/default/test/fixtures/simple-file.js.tpl
  packages/generators/loader-template/default/test/functional.test.js.tpl
  packages/generators/loader-template/default/test/test-utils.js.tpl
  packages/generators/loader-template/default/test/unit.test.js.tpl
  packages/generators/plugin-template/default/examples/simple/_webpack.config.js.tpl
  packages/generators/plugin-template/default/examples/simple/src/index.js.tpl
  packages/generators/plugin-template/default/examples/simple/src/lazy-module.js.tpl
  packages/generators/plugin-template/default/examples/simple/src/static-esm-module.js.tpl
  packages/generators/plugin-template/default/src/_index.js.tpl
  packages/generators/plugin-template/default/src/cjs.js.tpl
  packages/generators/plugin-template/default/test/fixtures/simple-file.js.tpl
  packages/generators/plugin-template/default/test/functional.test.js.tpl
  packages/generators/plugin-template/default/test/test-utils.js.tpl
  packages/generators/src/addon-generator.ts
  packages/generators/src/index.ts
  test/help/__snapshots__/help.test.js.snap.webpack4
  test/help/__snapshots__/help.test.js.snap.webpack5
  test/loader/loader.test.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved
