Repository webpack/webpack-cli, pull requests merged in 2021-01, with the labels that each got.

#2283 chore: fix ci coverage
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small

#2295 docs: fix typo
  .github/ISSUE_TEMPLATE.md
Labels: PR: reviewed-approved, PR: reviewed-changes-requested, PR: small

#2288 fix: better description for --no-watch-options-stdin
  packages/webpack-cli/lib/utils/cli-flags.js
Labels: PR: reviewed-approved, PR: small

#2286 chore: create script to update docs
  OPTIONS.md
  package.json
  packages/webpack-cli/README.md
  scripts/updateDocs.js
Labels: PR: reviewed-approved

#2285 docs: usage and internal commands
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved

#2294 tests: add test cases for --ignore-warnings
  test/core-flags/ignore-warnings/ignore-warnings-flag.test.js
  test/core-flags/ignore-warnings/my-warning-loader.js
  test/core-flags/ignore-warnings/src/main.js
  test/core-flags/ignore-warnings/webpack.config.js
Labels: PR: reviewed-approved

#2287 feat: add support for dev containers
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/CONTRIBUTING.md
Labels: PR: reviewed-approved

#2297 chore: prevent unnecessary writes to stdin
  test/init/force/init-force.test.js
  test/init/generator/init-inquirer.test.js
  test/init/multipleEntries/init-multipleEntries.test.js
Labels: PR: reviewed-approved

#2298 fix: double commands output in help
  packages/webpack-cli/__tests__/CLI.test.js
  packages/webpack-cli/lib/webpack-cli.js
  test/help/help.test.js
Labels: PR: unreviewed

#2299 feat: allow to pass parseOption to CLI class
  packages/webpack-cli/lib/index.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: unreviewed

#2301 docs: remove redundant command entries
  OPTIONS.md
Labels: PR: reviewed-approved, PR: small

#2304 chore: ignore build files from lint
  .eslintignore
  .prettierignore
Labels: PR: reviewed-approved, PR: small

#2300 tests(init): assert for webpack config file content
  packages/generators/__tests__/utils/styleSupport.test.ts
  packages/generators/src/utils/styleSupport.ts
  test/init/auto/init-auto.test.js
  test/init/force/init-force.test.js
  test/init/generation-path/init-generation-path.test.js
  test/init/generator/init-inquirer.test.js
  test/init/language/css/init-language-css.test.js
  test/init/language/js/init-language-js.test.js
  test/init/multipleEntries/init-multipleEntries.test.js
Labels: PR: reviewed-approved

#2309 fix(init): remove style-loader from the loader chain
  packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/src/init-generator.ts
  test/init/language/css/init-language-css.test.js
Labels: PR: reviewed-approved

#2310 fix: remove splitchunks
  packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
  packages/generators/src/init-generator.ts
Labels: PR: reviewed-approved

#2315 docs: fix broken references
  README.md
  packages/README.md
Labels: PR: reviewed-approved

#2316 fix: webpack installation prompt message
  packages/webpack-cli/bin/cli.js
Labels: PR: reviewed-approved, PR: small

#2318 chore: remove duplicate build script
  .github/workflows/nodejs.yml
  package.json
Labels: PR: small, PR: unreviewed

#2312 fix: respect `--stats`, `--color` and `--no-color` option for serve c…
  package.json
  packages/serve/__tests__/__snapshots__/startDevServer.test.ts.snap
  packages/serve/__tests__/startDevServer.test.ts
  packages/serve/src/index.ts
  packages/serve/src/startDevServer.ts
  packages/serve/src/types.ts
  packages/webpack-cli/__tests__/resolveArgs.test.js
  packages/webpack-cli/lib/webpack-cli.js
  test/core-flags/stats-flags.test.js
  test/serve/basic/serve-basic.test.js
  test/stats/config-no/no-stats-with-config.test.js
  test/stats/config/index.js
  test/stats/config/package.json
  test/stats/config/stats.test.js
  test/stats/config/webpack.config.js
  test/stats/flags/index.js
  test/stats/flags/package.json
  test/stats/flags/stats.test.js
  yarn.lock
Labels: PR: unreviewed

#2303 feat: implement new configtest command
  .eslintignore
  .prettierignore
  OPTIONS.md
  packages/configtest/package.json
  packages/configtest/src/index.ts
  packages/configtest/tsconfig.json
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/webpack-cli.js
  packages/webpack-cli/package.json
  test/configtest/configtest.test.js
  test/configtest/error.config.js
  test/configtest/src/index.js
  test/configtest/syntax-error.config.js
  test/configtest/webpack.config.js
  test/help/help.test.js
  tsconfig.json
Labels: PR: review-outdated

#2311 feat: flexible init scaffolding
  INIT.md
  packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
  packages/generators/src/init-generator.ts
  test/init/force/init-force.test.js
  test/init/generator/init-inquirer.test.js
  test/init/language/css/init-language-css.test.js
  test/init/language/js/init-language-js.test.js
  test/init/multipleEntries/init-multipleEntries.test.js
Labels: PR: reviewed-approved

#2319 fix(init): regression with webpack config
  packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
  packages/generators/src/init-generator.ts
Labels: PR: reviewed-approved

#2329 tests: multi compiler CLI plugin test
  packages/webpack-cli/__tests__/applyCLIPlugin.test.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved

#2327 chore: remove stale helpers
  packages/generators/src/utils/tooltip.ts
Labels: PR: reviewed-approved

#2330 fix(serve): ts types and warnings
  packages/serve/src/startDevServer.ts
  packages/serve/src/types.ts
Labels: PR: reviewed-approved, PR: small

#2321 fix: create sourcemaps on ci
  .github/workflows/nodejs.yml
  package.json
Labels: PR: reviewed-approved, PR: small

#2326 fix: remove legacy tooling
  .babelrc
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2324 fix: improve init generator
  packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/src/init-generator.ts
  test/init/auto/init-auto.test.js
  test/init/force/init-force.test.js
  test/init/generation-path/init-generation-path.test.js
  test/init/generator/init-inquirer.test.js
Labels: PR: reviewed-approved

#2209 tests: refactor
  test/cache/cache.test.js
  test/config-format/coffee/coffee.test.js
  test/config-format/mjs/mjs.test.js
  test/config/defaults/mjs-config/default-mjs-config.test.js
  test/config/error-mjs/config-error.test.js
  test/config/function/functional-config.test.js
  test/config/type/function-with-env/function-with-env.test.js
  test/core-flags/webpack.test.config.js
  test/devtool/object/source-map-object.test.js
  test/entry/flag-entry/entry-with-flag.test.js
  test/entry/multiple-entries/multi-entries.test.js
  test/env/array/array-env.test.js
  test/env/object/object-env.test.js
  test/hot/hot-flag.test.js
  test/loader/error-test/loader-error.test.js
  test/mode/mode-single-arg/mode-single-arg.test.js
  test/mode/mode-with-config/mode-with-config.test.js
  test/node/node.test.js
  test/serve/basic/serve-basic.test.js
  test/serve/serve-variable/serve-basic.test.js
  test/serve/with-custom-port/serve-custom-config.test.js
  test/utils/test-utils.js
  test/utils/test-utils.test.js
Labels: PR: reviewed-approved

#2334 chore: update webpack to 5.12.2
  OPTIONS.md
  package.json
  test/core-flags/module-flags.test.js
  test/entry/flag-entry/entry-with-flag.test.js
  test/serve/basic/serve-basic.test.js
  yarn.lock
Labels: PR: reviewed-approved

#2335 tests(init): increase coverage
  packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/src/init-generator.ts
Labels: PR: reviewed-approved

#2317 tests: serve help
  test/entry/flag-entry/entry-with-flag.test.js
  test/serve/help/serve-help.test.js
Labels: PR: reviewed-approved

#2328 refactor: generators
  packages/configtest/src/index.ts
  packages/generators/addon-template/package.json.js
  packages/generators/init-template/.babelrc
  packages/generators/init-template/README.md
  packages/generators/init-template/index.js
  packages/generators/init-template/package.json.js
  packages/generators/init-template/sw.js
  packages/generators/init-template/template.html
  packages/generators/init-template/tsconfig.json.js
  packages/generators/package.json
  packages/generators/src/addon-generator.ts
  packages/generators/src/init-generator.ts
  packages/generators/src/types/index.ts
Labels: PR: review-outdated

#2336 refactor: `configtest` is the part of webpack-cli
  packages/webpack-cli/package.json
Labels: PR: reviewed-approved, PR: small

#2296 tests: add test for missing packages
  .github/workflows/nodejs.yml
  package.json
  smoketests/index.js
  smoketests/missing-packages/webpack-dev-server.test.js
  smoketests/missing-packages/webpack.test.js
Labels: PR: unreviewed

#2337 chore: remove stale code
  packages/generators/src/utils/index.ts
  packages/generators/src/utils/webpackConfig.ts
Labels: PR: reviewed-approved

#2338 fix: show exact package name while prompting for installation
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved, PR: small

#2339 chore: remove redundant action
  packages/init/src/index.ts
  packages/utils/src/modify-config-helper.ts
  packages/utils/src/resolve-packages.ts
Labels: PR: reviewed-approved

#2340 fix: use worker from plugin and remove default
  packages/generators/init-template/sw.js
  packages/generators/src/init-generator.ts
Labels: PR: reviewed-approved, PR: small

#2343 fix: union utils
  .eslintrc.js
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/__tests__/utils/languageSupport.test.ts
  packages/generators/__tests__/utils/plugins.test.ts
  packages/generators/__tests__/utils/styleSupport.test.ts
  packages/generators/package.json
  packages/generators/src/addon-generator.ts
  packages/generators/src/index.ts
  packages/generators/src/loader-generator.ts
  packages/generators/src/utils/__tests__/__snapshots__/ast-utils.test.ts.snap
  packages/generators/src/utils/__tests__/ast-utils.test.ts
  packages/generators/src/utils/__tests__/find-project-root/package.json
  packages/generators/src/utils/__tests__/find-project-root/project/find-project-root.test.ts
  packages/generators/src/utils/__tests__/global-packages-path.test.ts
  packages/generators/src/utils/__tests__/is-local-path.test.ts
  packages/generators/src/utils/__tests__/npm-exists.test.ts
  packages/generators/src/utils/__tests__/npm-packages-exists.test.ts
  packages/generators/src/utils/__tests__/recursive-parser/__snapshots__/recursive-parser.test.ts.snap
  packages/generators/src/utils/__tests__/recursive-parser/__testfixtures__/fixture-0.input.js
  packages/generators/src/utils/__tests__/recursive-parser/__testfixtures__/fixture-1.input.js
  packages/generators/src/utils/__tests__/recursive-parser/__testfixtures__/fixture-2.input.js
  packages/generators/src/utils/__tests__/recursive-parser/__testfixtures__/fixture-3.input.js
  packages/generators/src/utils/__tests__/recursive-parser/recursive-parser.test.ts
  packages/generators/src/utils/__tests__/resolve-packages.test.ts
  packages/generators/src/utils/__tests__/run-prettier.test.ts
  packages/generators/src/utils/__tests__/validate-identifier.test.ts
  packages/generators/src/utils/ast-utils.ts
  packages/generators/src/utils/copy-utils.ts
  packages/generators/src/utils/defineTest.ts
  packages/generators/src/utils/global-packages-path.ts
  packages/generators/src/utils/isWebpack5.ts
  packages/generators/src/utils/modify-config-helper.ts
  packages/generators/src/utils/npm-exists.ts
  packages/generators/src/utils/npm-packages-exists.ts
  packages/generators/src/utils/path-utils.ts
  packages/generators/src/utils/prop-types.ts
  packages/generators/src/utils/recursive-parser.ts
  packages/generators/src/utils/resolve-packages.ts
  packages/generators/src/utils/run-prettier.ts
  packages/generators/src/utils/scaffold.ts
  packages/generators/src/utils/spawn-child.ts
  packages/generators/src/utils/types/Config.ts
  packages/generators/src/utils/types/Error.ts
  packages/generators/src/utils/types/NodePath.ts
  packages/generators/src/utils/types/index.ts
  packages/generators/src/utils/validate-identifier.ts
  packages/generators/tsconfig.json
  packages/init/package.json
  packages/init/src/index.ts
  packages/init/tsconfig.json
  packages/utils/CHANGELOG.md
  packages/utils/README.md
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/tsconfig.json
  scripts/utils.js
  tsconfig.json
Labels: PR: unreviewed

#2345 fix: pass all `argv` to configurations when `serve` command used
  .github/workflows/nodejs.yml
  packages/serve/src/index.ts
  packages/webpack-cli/__tests__/resolveConfig/resolveConfig.test.js
  packages/webpack-cli/lib/webpack-cli.js
  test/config/type/function-with-argv/function-with-argv.test.js
  test/serve/basic/function-with-argv.config.js
  test/serve/basic/function-with-env.config.js
  test/serve/basic/serve-basic.test.js
  yarn.lock
Labels: PR: unreviewed

#2346 chore: update deps
  .github/workflows/nodejs.yml
  .prettierignore
  OPTIONS.md
  package.json
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/__tests__/loader-generator.test.ts
  packages/generators/__tests__/plugin-generator.test.ts
  packages/generators/__tests__/utils/scaffold-utils.test.ts
  packages/generators/package.json
  packages/serve/src/index.ts
  smoketests/missing-packages/webpack-dev-server.test.js
  smoketests/missing-packages/webpack.test.js
  yarn.lock
Labels: PR: unreviewed

#2348 chore: update `webpack-merge`
  packages/webpack-cli/lib/webpack-cli.js
  packages/webpack-cli/package.json
  yarn.lock
Labels: PR: unreviewed

#2349 feat: show multiple suggestions on unknown options
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
  test/unknown/unknown.test.js
Labels: PR: unreviewed

#2350 refactor: generators
  packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
  packages/generators/__tests__/init-generator.test.ts
  packages/generators/__tests__/utils/plugins.test.ts
  packages/generators/src/index.ts
  packages/generators/src/init-generator.ts
  packages/generators/src/utils/__tests__/npm-exists.test.ts
  packages/generators/src/utils/__tests__/npm-packages-exists.test.ts
  packages/generators/src/utils/__tests__/run-prettier.test.ts
  packages/generators/src/utils/copy-utils.ts
  packages/generators/src/utils/entry.ts
  packages/generators/src/utils/global-packages-path.ts
  packages/generators/src/utils/index.ts
  packages/generators/src/utils/isWebpack5.ts
  packages/generators/src/utils/languageSupport.ts
  packages/generators/src/utils/modify-config-helper.ts
  packages/generators/src/utils/npm-exists.ts
  packages/generators/src/utils/npm-packages-exists.ts
  packages/generators/src/utils/path-utils.ts
  packages/generators/src/utils/plugins.ts
  packages/generators/src/utils/prop-types.ts
  packages/generators/src/utils/run-prettier.ts
  packages/generators/src/utils/scaffold-utils.ts
  packages/generators/src/utils/scaffold.ts
  packages/generators/src/utils/styleSupport.ts
  packages/generators/src/utils/types/Error.ts
  packages/generators/src/utils/types/index.ts
Labels: PR: unreviewed

#2351 Refactor core command
  OPTIONS.md
  packages/webpack-cli/lib/webpack-cli.js
  test/build/basic/basic.test.js
  test/build/basic/src/index.js
  test/build/build-variable/build-variable.test.js
  test/build/build-variable/src/index.js
  test/build/build-variable/webpack.config.js
  test/build/bundle-variable/bundle-variable.test.js
  test/build/bundle-variable/src/index.js
  test/build/bundle-variable/webpack.config.js
  test/config/type/function-with-argv/function-with-argv.test.js
  test/help/help.test.js
  test/version/version.test.js
Labels: PR: unreviewed

#2353 feat: allow to use `help` command to show option information
  OPTIONS.md
  packages/webpack-cli/lib/webpack-cli.js
  test/build/basic/basic.test.js
  test/help/help.test.js
Labels: PR: unreviewed

#2354 feat: `configtest` validate default configuration
  .eslintignore
  .prettierignore
  packages/configtest/src/index.ts
  packages/webpack-cli/lib/webpack-cli.js
  test/configtest/with-config-path/basic.config.js
  test/configtest/with-config-path/error.config.js
  test/configtest/with-config-path/src/index.js
  test/configtest/with-config-path/syntax-error.config.js
  test/configtest/with-config-path/with-config-path.test.js
  test/configtest/without-config-path-custom-extension/webpack.config.json
  test/configtest/without-config-path-custom-extension/without-config-path.test.js
  test/configtest/without-config-path-error/webpack.config.js
  test/configtest/without-config-path-error/without-config-path-error.test.js
  test/configtest/without-config-path-multi-compiler-mode/webpack.config.js
  test/configtest/without-config-path-multi-compiler-mode/without-config-path-multi-compiler-mode.test.js
  test/configtest/without-config-path-no-configuration/without-config-path-no-configuration.test.js
  test/configtest/without-config-path/webpack.config.js
  test/configtest/without-config-path/without-config-path.test.js
Labels: PR: reviewed-approved, PR: unreviewed

#2357 feat: added the `watch` command
  OPTIONS.md
  packages/configtest/src/index.ts
  packages/webpack-cli/lib/webpack-cli.js
  test/help/help.test.js
  test/version/version.test.js
  test/watch/basic/basic.test.js
  test/watch/basic/src/index.js
  test/watch/basic/watch.config.js
  test/watch/simple/watch.test.js
  test/watch/stdin/stdin.test.js
Labels: PR: unreviewed

#2365 chore: update `commander`
  packages/info/src/index.ts
  packages/init/src/index.ts
  packages/serve/src/index.ts
  packages/webpack-cli/__tests__/CLI.test.js
  packages/webpack-cli/lib/utils/capitalize-first-letter.js
  packages/webpack-cli/lib/webpack-cli.js
  packages/webpack-cli/package.json
  test/config/type/function-with-env/function-with-env.test.js
  test/defaults/output-defaults.test.js
  test/info/info-unknown.test.js
  test/output/output-named-bundles.test.js
  test/prefetch/prefetch.test.js
  test/serve/basic/serve-basic.test.js
  test/target/flag-test/target-flag.test.js
  test/unknown/unknown.test.js
  yarn.lock
Labels: PR: reviewed-approved

#2366 refactor: code
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: unreviewed

#2372 Mention `-p` in the changelog
  CHANGELOG.md
Labels: PR: reviewed-approved, PR: small

#2376 chore: update webpack to 5.17.0
  OPTIONS.md
  package.json
  packages/webpack-cli/README.md
  test/core-flags/experiments-flag.test.js
  yarn.lock
Labels: PR: reviewed-approved

#2369 [WIP] Fix entries syntax
  OPTIONS.md
  packages/serve/src/index.ts
  packages/webpack-cli/__tests__/resolveArgs.test.js
  packages/webpack-cli/lib/utils/cli-flags.js
  packages/webpack-cli/lib/webpack-cli.js
  test/build/basic/basic.test.js
  test/build/basic/entry.config.js
  test/build/basic/src/again.js
  test/build/basic/src/entry.js
  test/build/basic/src/other.js
  test/config/absent/config-absent.test.js
  test/config/invalid-path/invalid-path.test.js
  test/configtest/with-config-path/with-config-path.test.js
  test/core-flags/experiments-flag.test.js
  test/core-flags/externals-flags.test.js
  test/core-flags/module-flags.test.js
  test/core-flags/optimization-flags.test.js
  test/core-flags/output-flags.test.js
  test/core-flags/performance-flags.test.js
  test/core-flags/resolve-flags.test.js
  test/core-flags/snapshot-flags.test.js
  test/core-flags/stats-flags.test.js
  test/core-flags/watch-flags.test.js
  test/core-flags/webpack.test.config.js
  test/help/help.test.js
  test/merge/config-absent/merge-config-absent.test.js
  test/serve/basic/serve-basic.test.js
  test/serve/basic/serve.config.js
  test/serve/basic/src/entry.js
  test/serve/help/serve-help.test.js
  test/unknown/unknown.test.js
  test/watch/basic/basic.test.js
  test/watch/basic/src/entry.js
Labels: PR: reviewed-approved, PR: unreviewed

#2379 fix: improve description for `configtest` command
  OPTIONS.md
  packages/configtest/package.json
  packages/configtest/src/index.ts
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved

#2380 fix: fix error message on invalid plugin options
  package.json
  packages/serve/src/index.ts
  packages/webpack-cli/lib/webpack-cli.js
  test/error/invalid-schema/invalid-schema.test.js
  test/error/invalid-schema/webpack.mock.config.js
  test/error/invalid-schema/webpack.plugin-mock.config.js
  yarn.lock
Labels: PR: reviewed-approved

#2382 Refactor code
  .eslintignore
  .eslintrc.js
  .prettierignore
  packages/webpack-cli/__tests__/resolveConfig/resolveConfig.test.js
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/index.js
  packages/webpack-cli/lib/plugins/CLIPlugin.js
  packages/webpack-cli/lib/utils/get-package-manager.js
  packages/webpack-cli/lib/utils/index.js
  packages/webpack-cli/lib/utils/logger.js
  packages/webpack-cli/lib/utils/package-exists.js
  packages/webpack-cli/lib/utils/prompt-installation.js
  packages/webpack-cli/lib/utils/run-command.js
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: unreviewed

#2375 fix: show a warning if serve and `--watch` are used together
  packages/serve/src/index.ts
  packages/webpack-cli/lib/webpack-cli.js
  test/serve/basic/serve-basic.test.js
  test/serve/basic/watch.config.js
  test/watch/basic/basic.test.js
  test/watch/watch-variable/src/index.js
  test/watch/watch-variable/watch-variable.test.js
  test/watch/watch-variable/webpack.config.js
Labels: PR: unreviewed
