Repository webpack/webpack-cli, pull requests merged in 2021-02, with the labels that each got.

#2389 chore: remove git-cz
  .github/CONTRIBUTING.md
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2391 chore(init): remove --force flag
  INIT.md
  packages/generators/src/utils/modify-config-helper.ts
  packages/generators/src/utils/scaffold.ts
  packages/init/README.md
  packages/init/src/index.ts
  test/init/force/init-force.test.js
Labels: PR: reviewed-approved

#2395 docs: remove references to non-existent packages
  README.md
  packages/README.md
Labels: PR: reviewed-approved, PR: small

#2381 fix: support esm format for configurations
  package.json
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/bootstrap.js
  packages/webpack-cli/lib/utils/dynamic-import-loader.js
  packages/webpack-cli/lib/utils/index.js
  packages/webpack-cli/lib/webpack-cli.js
  test/config-format/coffee/coffee.test.js
  test/config-format/coffee/package.json
  test/config-format/commonjs-default/commonjs-default.test.js
  test/config-format/commonjs-default/main.js
  test/config-format/commonjs-default/webpack.config.cjs
  test/config-format/failure/failure.test.js
  test/config-format/failure/webpack.config.iced
  test/config-format/mjs/mjs.test.js
  test/config-format/typescript/package.json
  test/config-format/typescript/typescript.test.js
  test/config-format/typescript/webpack.config.ts
  test/config-lookup/custom-name/config.webpack.mjs
  test/config-lookup/custom-name/custom-name.test.js
  test/config/defaults/mjs-config/default-mjs-config.test.js
  test/config/error-mjs/config-error.test.js
  test/entry/scss/package.json
  test/watch/basic/basic.test.js
  test/watch/basic/src/index.js
  yarn.lock
Labels: PR: unreviewed

#2394 chore: use conventional commitlint
  .cz-config.js
  commitlint.config.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2398 docs: update
  .github/CONTRIBUTING.md
Labels: PR: reviewed-approved, PR: small

#2399 test: improve tests for --merge
  test/merge/config/1.js
  test/merge/config/2.js
  test/merge/config/3.js
  test/merge/config/first-entry.js
  test/merge/config/merge-config.test.js
  test/merge/config/second-entry.js
  test/merge/config/some_entry.js
  test/merge/config/third-entry.js
Labels: PR: reviewed-approved

#2392 test: default loader name and plugin name
  test/loader/loader.test.js
  test/plugin/plugin.test.js
Labels: PR: unreviewed

#2388 feat: add --node-env flag
  packages/webpack-cli/lib/webpack-cli.js
  test/node-env/auto-mode.config.js
  test/node-env/node-env.test.js
  test/node-env/src/index.js
  test/node-env/webpack.config.js
Labels: PR: reviewed-approved, PR: unreviewed

#2416 chore: update webpack
  OPTIONS.md
  package.json
  test/build-errors/errors.test.js
  test/build-warnings/warnings.test.js
  test/colors/colors.test.js
  test/core-flags/context-flag.test.js
  test/core-flags/output-flags.test.js
  test/core-flags/stats-flags.test.js
  test/defaults/output-defaults.test.js
  test/entry/defaults-empty/entry-single-arg.test.js
  test/entry/flag-entry/entry-with-flag.test.js
  test/mode/mode-single-arg/mode-single-arg.test.js
  test/prefetch/prefetch.test.js
  test/zero-config/entry-absent/zero-config.test.js
  yarn.lock
Labels: PR: reviewed-approved, PR: unreviewed

#2417 build: do not install webpack 5 again
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small

#2393 chore: move init to generators
  .eslintignore
  .prettierignore
  packages/generators/src/index.ts
  packages/init/CHANGELOG.md
  packages/init/README.md
  packages/init/package.json
  packages/init/src/index.ts
  packages/init/tsconfig.json
  packages/webpack-cli/lib/webpack-cli.js
  packages/webpack-cli/package.json
  test/version/version.test.js
  tsconfig.json
Labels: PR: reviewed-approved

#2424 fix: add serve script if opted for WDS with init
  packages/generators/init-template/package.json.js
  packages/generators/src/init-generator.ts
  test/init/auto/init-auto.test.js
  test/init/generation-path/init-generation-path.test.js
  test/init/generator/init-inquirer.test.js
  test/init/language/css/init-language-css.test.js
  test/init/language/js/init-language-js.test.js
  test/init/multipleEntries/init-multipleEntries.test.js
Labels: PR: reviewed-approved

#2411 feat: show '--node-env' in minimum help output
  OPTIONS.md
  packages/webpack-cli/README.md
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: reviewed-approved, PR: unreviewed

#2425 chore(generators): update types
  packages/generators/src/types/index.ts
  packages/generators/src/utils/modify-config-helper.ts
Labels: PR: reviewed-approved, PR: small

#2402 docs: update commands
  README.md
  packages/configtest/README.md
  packages/info/README.md
Labels: PR: reviewed-approved, PR: unreviewed

#2423 refactor: use error validation from cli
  packages/configtest/src/index.ts
Labels: PR: reviewed-approved

#2419 fix: improve prettier message
  packages/generators/src/utils/__tests__/run-prettier.test.ts
  packages/generators/src/utils/run-prettier.ts
  packages/generators/src/utils/scaffold.ts
Labels: PR: reviewed-approved, PR: small

#2431 feat: display used config path when logging level=log
  .github/workflows/nodejs.yml
  package.json
  packages/webpack-cli/__tests__/applyCLIPlugin.test.js
  packages/webpack-cli/lib/plugins/CLIPlugin.js
  packages/webpack-cli/lib/webpack-cli.js
  test/build/basic/basic.test.js
  test/build/basic/log.config.js
  test/core-flags/infrastructure-logging.test.js
  test/json/json.test.js
  test/serve/basic/log.config.js
  test/serve/basic/serve-basic.test.js
  test/watch/basic/basic.test.js
  test/watch/basic/log.config.js
Labels: PR: reviewed-approved, PR: unreviewed

#2432 docs: remove references to init package
  README.md
  packages/README.md
Labels: PR: reviewed-approved, PR: small

#2404 chore: disable colors on CI by default
  setupTest.js
  smoketests/missing-packages/webpack-dev-server.test.js
  smoketests/missing-packages/webpack.test.js
  test/analyze/analyze-flag.test.js
  test/build-errors/errors.test.js
  test/build-warnings/warnings.test.js
  test/build/basic/basic.test.js
  test/colors/colors.test.js
  test/config/multiple/multiple-config.test.js
  test/core-flags/context-flag.test.js
  test/defaults/output-defaults.test.js
  test/entry/defaults-empty/entry-single-arg.test.js
  test/entry/flag-entry/entry-with-flag.test.js
  test/help/help.test.js
  test/init/auto/init-auto.test.js
  test/init/generator/init-inquirer.test.js
  test/json/json.test.js
  test/loader/loader.test.js
  test/mode/mode-single-arg/mode-single-arg.test.js
  test/plugin/plugin.test.js
  test/prefetch/prefetch.test.js
  test/serve/basic/serve-basic.test.js
  test/serve/help/serve-help.test.js
  test/stats/watch/stats-and-watch.test.js
  test/unknown/unknown.test.js
  test/utils/test-utils.js
  test/version/version.test.js
  test/watch/basic/basic.test.js
  test/watch/watch-variable/watch-variable.test.js
  test/zero-config/entry-absent/zero-config.test.js
Labels: PR: small, PR: unreviewed

#2442 Test refactor
  test/bail/bail.test.js
  test/serve/basic/serve-basic.test.js
  test/serve/serve-variable/serve-basic.test.js
  test/serve/with-custom-port/serve-custom-config.test.js
  test/stats/watch/stats-and-watch.test.js
  test/utils/test-utils.js
Labels: PR: unreviewed

#2443 chore: upgrade eslint plugins
  package.json
  packages/configtest/src/index.ts
  packages/generators/__tests__/addon-generator.test.ts
  packages/generators/__tests__/utils/scaffold-utils.test.ts
  packages/generators/src/addon-generator.ts
  packages/generators/src/index.ts
  packages/generators/src/init-generator.ts
  packages/generators/src/loader-generator.ts
  packages/generators/src/plugin-generator.ts
  packages/generators/src/types/index.ts
  packages/generators/src/utils/__tests__/npm-packages-exists.test.ts
  packages/generators/src/utils/__tests__/recursive-parser/__snapshots__/recursive-parser.test.ts.snap
  packages/generators/src/utils/__tests__/recursive-parser/recursive-parser.test.ts
  packages/generators/src/utils/__tests__/resolve-packages.test.ts
  packages/generators/src/utils/ast-utils.ts
  packages/generators/src/utils/copy-utils.ts
  packages/generators/src/utils/defineTest.ts
  packages/generators/src/utils/entry.ts
  packages/generators/src/utils/modify-config-helper.ts
  packages/generators/src/utils/npm-packages-exists.ts
  packages/generators/src/utils/resolve-packages.ts
  packages/generators/src/utils/scaffold-utils.ts
  packages/generators/src/utils/types/Config.ts
  packages/generators/src/utils/types/NodePath.ts
  packages/info/src/index.ts
  packages/serve/src/index.ts
  packages/serve/src/startDevServer.ts
  packages/serve/src/types.ts
  test/entry/scss/webpack.config.js
  test/stats/flags/webpack.config.js
  test/utils/test-utils.js
  yarn.lock
Labels: PR: unreviewed

#2445 chore: skip flaky tests for windows
  test/config-format/mjs/mjs.test.js
  test/config-lookup/custom-name/custom-name.test.js
  test/config/defaults/mjs-config/default-mjs-config.test.js
  test/config/error-mjs/config-error.test.js
Labels: PR: reviewed-approved

#2450 docs: remove migrate references
  .github/CONTRIBUTING.md
Labels: PR: reviewed-approved

#2454 test: refactor
  packages/webpack-cli/__tests__/applyCLIPlugin.test.js
  packages/webpack-cli/__tests__/resolveArgs.test.js
  test/api/CLI.test.js
  test/api/resolveConfig/env.webpack.config.cjs
  test/api/resolveConfig/resolveConfig.test.js
  test/api/resolveConfig/webpack.config.cjs
  test/api/resolveConfig/webpack.config1.cjs
  test/api/resolveConfig/webpack.config2.cjs
  test/api/resolveConfig/webpack.promise.config.cjs
Labels: PR: reviewed-approved

#2469 docs: Grammatical error in webpack-cli commands and arguments usage
  packages/webpack-cli/README.md
Labels: PR: reviewed-approved, PR: small
