Repository webpack/webpack-cli, pull requests merged in 2021-06, with the labels that each got.

#2743 chore: update jest to v27
  jest.config.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2747 chore: migrate to `jest-circus`
  jest.config.js
  setupTest.js
  test/api/CLI.test.js
Labels: PR: reviewed-approved

#2753 refactor: use appropriate name for test file
  test/serve/serve-variable/__snapshots__/serve-variable.test.js.snap.devServer3.webpack4
  test/serve/serve-variable/__snapshots__/serve-variable.test.js.snap.devServer3.webpack5
  test/serve/serve-variable/__snapshots__/serve-variable.test.js.snap.devServer4.webpack4
  test/serve/serve-variable/__snapshots__/serve-variable.test.js.snap.devServer4.webpack5
  test/serve/serve-variable/serve-variable.test.js
Labels: PR: reviewed-approved

#2746 test: refactor core-flags tests
  test/api/CLI.test.js
  test/build/core-flags/amd-flag.test.js
  test/build/core-flags/bail-flag.test.js
  test/build/core-flags/cache-flags.test.js
  test/build/core-flags/context-flag.test.js
  test/build/core-flags/core-flags.test.js
  test/build/core-flags/dependencies-flag.test.js
  test/build/core-flags/devtool-flag.test.js
  test/build/core-flags/entry-reset-flag.test.js
  test/build/core-flags/experiments-flag.test.js
  test/build/core-flags/externals-flags.test.js
  test/build/core-flags/ignore-warnings/ignore-warnings-flag.test.js
  test/build/core-flags/ignore-warnings/src/main.js
  test/build/core-flags/infrastructure-logging.test.js
  test/build/core-flags/invalid-flag.test.js
  test/build/core-flags/module-flags.test.js
  test/build/core-flags/my-warning-loader.js
  test/build/core-flags/node-flags.test.js
  test/build/core-flags/optimization-flags.test.js
  test/build/core-flags/output-flags.test.js
  test/build/core-flags/parallelism-flag.test.js
  test/build/core-flags/performance-flags.test.js
  test/build/core-flags/profile-flag.test.js
  test/build/core-flags/records-flag.test.js
  test/build/core-flags/resolve-flags.test.js
  test/build/core-flags/snapshot-flags.test.js
  test/build/core-flags/stats-flags.test.js
  test/build/core-flags/warning.config.js
  test/build/core-flags/watch-flags.test.js
Labels: PR: unreviewed

#2758 chore: add node 16 on CI
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small

#2759 Revert "chore: add node 16 on CI"
  .github/workflows/nodejs.yml
Labels: PR: small, PR: unreviewed

#2760 fix: add node 16 to CI
  .github/workflows/nodejs.yml
  test/build/entry/scss/package.json
Labels: PR: reviewed-approved, PR: small

#2761 fix: not found module after ask installation
  packages/webpack-cli/lib/utils/package-exists.js
  packages/webpack-cli/lib/utils/prompt-installation.js
Labels: PR: unreviewed

#2754 feat: new CLI options API for serve
  packages/serve/src/index.ts
  test/serve/serve-variable/webpack.config.js
Labels: PR: reviewed-approved

#2770 fix: broken serve with new CLI API
  packages/serve/src/index.ts
Labels: PR: reviewed-approved, PR: small

#2769 feat(init-generator): add ability to specify a package manager of choice
  packages/generators/src/init-generator.ts
  packages/webpack-cli/lib/utils/get-available-installers.js
  packages/webpack-cli/lib/utils/index.js
  test/init/init.test.js
Labels: PR: reviewed-approved

#2779 feat(addon-generator): add prompt to select a package manager of choice
  packages/generators/src/addon-generator.ts
  test/loader/loader.test.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved

#2777 chore: revise documentation
  README.md
  SECURITY.md
  packages/generators/INIT.md
Labels: PR: reviewed-approved

#2796 test: enable skipped test assertions
  test/loader/loader.test.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved

#2798 test: increase coverage
  test/init/__snapshots__/init.test.js.snap.webpack4
  test/init/__snapshots__/init.test.js.snap.webpack5
  test/init/init.test.js
  test/loader/loader.test.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved

#2799 refactor: leverage helpers
  test/init/init.test.js
  test/loader/loader.test.js
  test/plugin/plugin.test.js
Labels: PR: reviewed-approved

#2808 chore: upgrade webpack
  package.json
  test/build/target/flag-test/__snapshots__/target-flag.test.js.snap.webpack5
  yarn.lock
Labels: PR: reviewed-approved

#2809 chore(generators): do not prompt if multiple installers are not available
  packages/generators/src/addon-generator.ts
  packages/generators/src/init-generator.ts
Labels: PR: reviewed-approved

#2811 docs: update options
  OPTIONS.md
Labels: PR: reviewed-approved
