Repository webpack/webpack-cli, pull requests merged in 2021-07, with the labels that each got.

#2819 feat: show possible values for option in help output
  packages/webpack-cli/lib/webpack-cli.js
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
  test/help/help.test.js
Labels: PR: reviewed-approved

#2825 test: remove duplicate testcase
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
  test/help/help.test.js
Labels: PR: reviewed-approved

#2828 docs: update options
  OPTIONS.md
Labels: PR: reviewed-approved, PR: small

#2829 ci: use `actions/setup-node@v2`
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small

#2814 fix: show default value in help output if available
  packages/webpack-cli/lib/webpack-cli.js
  test/api/CLI.test.js
  test/api/__snapshots__/CLI.test.js.snap.webpack4
  test/api/__snapshots__/CLI.test.js.snap.webpack5
Labels: PR: reviewed-approved, PR: small

#2838 chore: upgrade webpack
  package.json
  test/build/target/flag-test/__snapshots__/target-flag.test.js.snap.webpack5
  yarn.lock
Labels: PR: reviewed-approved

#2841 fix: ci for dev server next
  packages/serve/src/index.ts
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
  test/help/help.test.js
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer3.webpack4
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer3.webpack5
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer4.webpack4
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer4.webpack5
  test/serve/basic/serve-basic.test.js
  test/serve/invalid-schema/__snapshots__/invalid-schema.test.js.snap.devServer4.webpack4
  test/serve/invalid-schema/__snapshots__/invalid-schema.test.js.snap.devServer4.webpack5
  test/utils/test-utils.js
Labels: PR: reviewed-approved, PR: unreviewed

#2844 Fix dev server with multi compiler mode
  packages/serve/src/index.ts
  packages/serve/src/startDevServer.ts
  test/serve/basic/multi-dev-server-output-public-path.config.js
  test/serve/basic/serve-basic.test.js
Labels: PR: unreviewed

#2842 refactor(generators): leverage helpers
  packages/generators/src/addon-generator.ts
  packages/generators/src/init-generator.ts
  packages/generators/src/utils/helpers.ts
  test/api/generators/__snapshots__/scaffold-utils.test.js.snap.webpack4
  test/api/generators/__snapshots__/scaffold-utils.test.js.snap.webpack5
  test/api/generators/helpers.test.js
  test/api/generators/scaffold-utils.test.js
Labels: PR: unreviewed

#2848 test: add more cases for colors test
  test/build/colors/colors.test.js
  test/build/colors/multi-stats-colors.webpack.config.js
  test/build/colors/stats-colors.webpack.config.js
Labels: PR: reviewed-approved, PR: unreviewed

#2849 fix: update dev server types to v4 compatible
  packages/serve/src/types.ts
Labels: PR: reviewed-approved

#2847 docs: update serve options to v4
  SERVE-OPTIONS-v3.md
  SERVE-OPTIONS-v4.md
  scripts/updateDocs.js
Labels: PR: reviewed-approved

#2853 fix: update `webpack-dev-server` usage
  packages/serve/src/index.ts
Labels: PR: reviewed-approved, PR: small

#2852 chore: use default node cache
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved

#2855 ci: migrate to `actions/setup-node@v2`
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small
