Repository webpack/webpack-cli, pull requests merged in 2021-08, with the labels that each got.

#2865 docs: update options
  OPTIONS.md
Labels: PR: small, PR: unreviewed

#2876 chore: update commitlint action in CI
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved, PR: small

#2874 fix: support top multi compiler options
  packages/webpack-cli/lib/webpack-cli.js
  test/build/config/top-multi-compilers-options/index.js
  test/build/config/top-multi-compilers-options/top-multi-compilers-options.test.js
  test/build/config/top-multi-compilers-options/webpack.config.js
Labels: PR: reviewed-approved

#2878 test: more
  test/build/core-flags/core-flags.test.js
Labels: PR: reviewed-approved

#2880 ci: update `codecov-action`
  .github/workflows/nodejs.yml
Labels: PR: small, PR: reviewed-approved

#2882 docs: update serve options link
  packages/serve/README.md
Labels: PR: small, PR: reviewed-approved

#2892 docs: update cli options
  OPTIONS.md
Labels: PR: reviewed-approved

#2886 fix: using new dev server API for v4
  packages/serve/src/index.ts
Labels: PR: unreviewed

#2893 docs: update `SERVE-OPTIONS-v4`
  OPTIONS.md
  SERVE-OPTIONS-v4.md
Labels: PR: reviewed-approved

#2898 fix: update `postCreateCommand` script for dev containers
  .devcontainer/devcontainer.json
Labels: PR: small, PR: reviewed-approved

#2905 docs: update server v4 options
  SERVE-OPTIONS-v4.md
Labels: PR: reviewed-approved

#2903 test: update snapshot for `webpack-dev-server@4.0.0`
  .github/workflows/nodejs.yml
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer4.webpack4
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer4.webpack5
  test/serve/basic/serve-basic.test.js
  yarn.lock
Labels: PR: unreviewed, PR: small, PR: reviewed-approved

#2901 docs: update bug report template
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: PR: small, PR: reviewed-approved

#2907 feat: allow to run commands not requiring webpack without webpack installation
  packages/configtest/src/index.ts
  packages/generators/src/index.ts
  packages/info/src/index.ts
  packages/serve/src/index.ts
  packages/webpack-cli/bin/cli.js
  packages/webpack-cli/lib/webpack-cli.js
  smoketests/helpers.js
  smoketests/index.js
  smoketests/missing-packages/webpack-dev-server.test.js
  smoketests/missing-packages/webpack.test.js
  test/build/custom-webpack/custom-webpack.test.js
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
  test/version/__snapshots__/version.test.js.snap.webpack4
  test/version/__snapshots__/version.test.js.snap.webpack5
  yarn.lock
Labels: PR: unreviewed
