Repository webpack/webpack-cli, pull requests merged in 2022-06, with the labels that each got.

#3285 docs: update options
  OPTIONS.md
  SERVE-OPTIONS-v4.md
Labels: PR: small, PR: reviewed-approved, update docs

#3288 feat: add summary to smoketests
  .cspell.json
  smoketests/index.js
Labels: PR: reviewed-approved

#3287 chore: disable length related `commitlint` rules
  commitlint.config.js
Labels: PR: small, PR: reviewed-approved

#3286 fix: improve parsing of `--env` flag
  packages/webpack-cli/src/webpack-cli.ts
  test/build/config/type/function-with-env/function-with-env.test.js
  test/build/config/type/function-with-env/webpack.config.js
  test/build/config/type/function-with-env/webpack.env.config.js
Labels: PR: reviewed-approved

#3289 chore: update package.json
  package.json
  packages/webpack-cli/package.json
Labels: PR: small, PR: reviewed-approved

#3291 refactor!: remove `migrate` command
  OPTIONS.md
  README.md
  packages/webpack-cli/README.md
  packages/webpack-cli/package.json
  packages/webpack-cli/src/webpack-cli.ts
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
  test/help/help.test.js
  test/version/__snapshots__/version.test.js.snap.webpack4
  test/version/__snapshots__/version.test.js.snap.webpack5
  test/version/version.test.js
Labels: PR: reviewed-approved

#3292 docs: remove redundant link
  README.md
Labels: PR: small, PR: reviewed-approved

#3290 refactor!: remove `--hot` in favor of directly using the HMR plugin
  packages/serve/src/index.ts
  packages/webpack-cli/src/plugins/CLIPlugin.ts
  packages/webpack-cli/src/webpack-cli.ts
  test/build/hot/__snapshots__/hot-flag.test.js.snap.webpack4
  test/build/hot/__snapshots__/hot-flag.test.js.snap.webpack5
  test/build/hot/hot-flag.test.js
  test/build/hot/src/index.js
  test/build/hot/webpack.config.js
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer3.webpack4
  test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer3.webpack5
  test/serve/basic/serve-basic.test.js
  test/serve/with-custom-port/__snapshots__/serve-custom-config.test.js.snap.devServer3.webpack4
  test/serve/with-custom-port/__snapshots__/serve-custom-config.test.js.snap.devServer3.webpack5
  test/serve/with-custom-port/serve-custom-config.test.js
Labels: PR: reviewed-approved

#3295 refactor!: remove the `--prefetch` option
  OPTIONS.md
  packages/webpack-cli/README.md
  packages/webpack-cli/src/plugins/CLIPlugin.ts
  packages/webpack-cli/src/webpack-cli.ts
  test/build/prefetch/prefetch.test.js
  test/build/prefetch/src/index.js
  test/build/prefetch/src/p.js
  test/build/prefetch/webpack.config.js
Labels: PR: reviewed-approved

#3309 chore: remove spam label
  open-bot.yml
Labels: PR: reviewed-approved

#3308 docs: update to use note syntax
  packages/configtest/README.md
  packages/info/README.md
  packages/serve/README.md
Labels: PR: reviewed-approved

#3310 chore: remove unnecessary step
  .cspell.json
  .devcontainer/devcontainer.json
Labels: PR: reviewed-approved

#3311 chore: use node:lts image
  .devcontainer/Dockerfile
Labels: PR: reviewed-approved

#3312 refactor: move all scripts to same folder
  jest.config.js
  scripts/setupTest.js
Labels: PR: reviewed-approved

#3317 feat: failOnWarnings option
  OPTIONS.md
  packages/webpack-cli/src/types.ts
  packages/webpack-cli/src/webpack-cli.ts
  test/build/build-warnings/warnings.test.js
Labels: PR: reviewed-approved
