Repository webpack/webpack-cli, pull requests merged in 2022-09, with the labels that each got.

#3399 chore(deps): update lock file
  yarn.lock
Labels: PR: unreviewed

#3403 chore: update eslint to v8.23.0
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#3402 ci: upgrade jest and enable --shard option
  .github/workflows/nodejs.yml
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#3408 ci: add separate job for smoketests
  .github/workflows/nodejs.yml
  smoketests/missing-packages/prettier.test.js
Labels: PR: reviewed-approved

#3410 chore: ignore log files for cspell
  .cspell.json
Labels: PR: reviewed-approved

#3409 refactor: remove prepareSuite script
  .github/workflows/nodejs.yml
  package.json
  scripts/prepareSuite.js
  test/build/entry/scss/package.json
  test/build/entry/scss/scss.test.js
  test/build/entry/scss/webpack.config.js
  test/loader/error-test/loader-error.test.js
  test/loader/error-test/package.json
  yarn.lock
Labels: PR: reviewed-approved

#3415 ci: update commitlint action
  .github/workflows/nodejs.yml
Labels: PR: reviewed-approved

#3413 chore: update jest to v29
  package.json
  test/api/__snapshots__/CLI.test.js.snap.webpack5
  test/configtest/with-config-path/__snapshots__/with-config-path.test.js.snap.webpack5
  test/configtest/without-config-path-error/__snapshots__/without-config-path-error.test.js.snap.webpack5
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
  test/init/__snapshots__/init.test.js.snap.webpack5
  test/serve/invalid-schema/__snapshots__/invalid-schema.test.js.snap.devServer4.webpack5
  yarn.lock
Labels: PR: reviewed-approved

#3419 chore: update link for cli flags generated by core
  packages/webpack-cli/src/webpack-cli.ts
Labels: PR: reviewed-approved

#3420 chore: remove cz-customizable dependency
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#3422 ci: run cancel workflow on pull requests
  .github/workflows/cancel.yml
Labels: PR: reviewed-approved

#3423 docs: update options for next
  OPTIONS.md
  SERVE-OPTIONS-v3.md
  SERVE-OPTIONS-v4.md
Labels: PR: reviewed-approved, update docs
