Repository webpack/webpack-cli, pull requests merged in 2022-01, with the labels that each got.

#3077 chore: regenerate lock file
  .cspell.json
  .github/workflows/nodejs.yml
  package.json
  packages/generators/package.json
  yarn.lock
Labels: PR: unreviewed

#3079 ci: update workflow jobs
  .github/workflows/nodejs.yml
Labels: PR: unreviewed

#3081 chore: remove bluebird from installed deps in generators
  packages/generators/loader-template/default/test/test-utils.js.tpl
  packages/generators/loader-template/default/test/unit.test.js.tpl
  packages/generators/plugin-template/default/test/test-utils.js.tpl
  packages/generators/src/addon-generator.ts
Labels: PR: reviewed-approved

#3080 chore: udpate dev dependencies
  .github/workflows/nodejs.yml
  .husky/.gitignore
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#3078 Feat strict types
  packages/configtest/src/index.ts
  packages/generators/src/addon-generator.ts
  packages/generators/src/handlers/default.ts
  packages/generators/src/index.ts
  packages/generators/src/init-generator.ts
  packages/generators/src/loader-generator.ts
  packages/generators/src/plugin-generator.ts
  packages/generators/src/types/index.ts
  packages/generators/src/utils/helpers.ts
  packages/generators/src/utils/scaffold-utils.ts
  packages/info/package.json
  packages/info/src/index.ts
  packages/serve/src/index.ts
  test/api/generators/__snapshots__/scaffold-utils.test.js.snap.webpack4
  test/api/generators/__snapshots__/scaffold-utils.test.js.snap.webpack5
  test/api/generators/scaffold-utils.test.js
  tsconfig.json
  yarn.lock
Labels: PR: reviewed-approved

#3101 docs: update webpack options
  OPTIONS.md
  package.json
  yarn.lock
Labels: PR: unreviewed

#3102 fix: respect `negatedDescription` for flags from schema
  packages/webpack-cli/lib/webpack-cli.js
Labels: PR: small, PR: reviewed-approved

#3108 chore: update deps and regenerate lock file
  package.json
  yarn.lock
Labels: PR: reviewed-approved
