Repository webpack/webpack-cli, pull requests merged in 2023-06, with the labels that each got.

#3739 ci: add Node.js v20
  .github/workflows/nodejs.yml
  package.json
  test/build/config-format/typescript-esnext/package.json
  test/build/config-format/typescript-esnext/typescript.test.js
  yarn.lock
Labels: PR: reviewed-approved

#3772 fix: improve check for custom webpack-dev-server package existance
  packages/webpack-cli/src/webpack-cli.ts
Labels: PR: unreviewed

#3832 refactor: use `type` for types
  packages/configtest/src/index.ts
  packages/generators/src/addon-generator.ts
  packages/generators/src/custom-generator.ts
  packages/generators/src/handlers/default.ts
  packages/generators/src/handlers/react.ts
  packages/generators/src/index.ts
  packages/generators/src/init-generator.ts
  packages/generators/src/loader-generator.ts
  packages/generators/src/plugin-generator.ts
  packages/generators/src/types/index.ts
  packages/generators/src/utils/helpers.ts
  packages/generators/src/utils/scaffold-utils.ts
  packages/info/src/index.ts
  packages/serve/src/index.ts
  packages/webpack-cli/src/bootstrap.ts
  packages/webpack-cli/src/index.ts
  packages/webpack-cli/src/plugins/cli-plugin.ts
  packages/webpack-cli/src/types.ts
  packages/webpack-cli/src/utils/dynamic-import-loader.ts
  packages/webpack-cli/src/webpack-cli.ts
Labels: PR: unreviewed

#3834 fix: regression for custom configurations
  package.json
  packages/webpack-cli/src/webpack-cli.ts
  test/build/config-format/babel-commonjs/babel-esm.test.js
  test/build/config-format/babel-commonjs/main.js
  test/build/config-format/babel-commonjs/package.json
  test/build/config-format/babel-commonjs/webpack.config.babel.js
  test/build/config-format/babel-esm/babel-esm.test.js
  test/build/config-format/babel-esm/main.js
  test/build/config-format/babel-esm/package.json
  test/build/config-format/babel-esm/webpack.config.babel.js
  yarn.lock
Labels: PR: unreviewed

#3845 chore: fix eslint warnings
  packages/webpack-cli/src/plugins/cli-plugin.ts
  packages/webpack-cli/src/types.ts
Labels: PR: unreviewed

#3846 .gitattributes updated to ignore `png.tpl` files
  .gitattributes
Labels: PR: review-outdated
