Repository webpack/webpack-cli, pull requests merged in 2024-08, with the labels that each got.

#4245 ci: fix
  .eslintrc.js
  .github/CONTRIBUTING.md
  .github/workflows/dependency-review.yml
  .github/workflows/nodejs.yml
  .github/workflows/update-docs.yml
  .husky/commit-msg
  .husky/pre-commit
  package.json
  packages/generators/src/addon-generator.ts
  packages/generators/src/custom-generator.ts
  packages/generators/src/handlers/default.ts
  packages/generators/src/index.ts
  packages/generators/src/init-generator.ts
  packages/generators/src/loader-generator.ts
  packages/generators/src/plugin-generator.ts
  packages/serve/src/index.ts
  packages/webpack-cli/package.json
  packages/webpack-cli/src/bootstrap.ts
  packages/webpack-cli/src/index.ts
  packages/webpack-cli/src/plugins/cli-plugin.ts
  packages/webpack-cli/src/types.ts
  packages/webpack-cli/src/utils/dynamic-import-loader.ts
  packages/webpack-cli/src/webpack-cli.ts
  scripts/cleanup-test.js
  scripts/snapshot-resolver.js
  scripts/update-docs.js
  smoketests/helpers.js
  smoketests/missing-packages/prettier.test.js
  test/.eslintrc
  test/api/CLI.test.js
  test/api/capitalizeFirstLetter.test.js
  test/api/do-install.test.js
  test/api/generators/helpers.test.js
  test/api/generators/scaffold-utils.test.js
  test/api/get-default-package-manager.test.js
  test/api/resolve-config/resolve-config.test.js
  test/build/analyze/analyze.config.js
  test/build/cache/cache.test.js
  test/build/config-format/babel-commonjs/babel-esm.test.js
  test/build/config-format/babel-esm/babel-esm.test.js
  test/build/config-format/babel-esm/webpack.config.babel.js
  test/build/config-format/disable-interpret/disable-interpret.test.js
  test/build/config-format/disable-interpret/webpack.config.ts
  test/build/config-format/typescript-esnext-mjs/typescript.test.js
  test/build/config-format/typescript-esnext/typescript.test.js
  test/build/config-format/typescript-esnext/webpack.config.ts
  test/build/config-format/typescript/webpack.config.ts
  test/build/entry/scss/webpack.config.js
  test/build/env/array/array-env.test.js
  test/build/env/object/object-env.test.js
  test/info/additional-package.test.js
  test/serve/basic/multi-dev-server.config.js
  test/serve/basic/serve-basic.test.js
  test/serve/serve-variable/serve-variable.test.js
  test/serve/with-custom-port/serve-custom-config.test.js
  test/utils/test-utils.js
  test/version/additional-package.test.js
  test/watch/analyze/analyze.config.js
  yarn.lock
Labels: PR: unreviewed, PR: reviewed-approved

#4211 Feat: modular and scalable refactor, --template flag and react template support
  packages/create-webpack-app/src/generators/default.ts
  packages/create-webpack-app/src/generators/react.ts
  test/create-webpack-app/__snapshots__/create-webpack-app.test.js.snap.webpack5
  test/create-webpack-app/init/init.test.js
Labels: PR: reviewed-approved

#4255 chore: update webpack
  OPTIONS.md
  package.json
  packages/webpack-cli/src/types.ts
  packages/webpack-cli/src/webpack-cli.ts
  yarn.lock
Labels: PR: reviewed-approved, update docs
