Repository webpack/webpack-cli, pull requests merged in 2024-01, with the labels that each got.

#4008 feat: use html-loader to default template
  packages/generators/init-template/default/webpack.configjs.tpl
  packages/generators/src/handlers/default.ts
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: unreviewed, PR: review-outdated

#4057 fix: correct the minimum help output
  OPTIONS.md
  SERVE-OPTIONS-v4.md
  packages/webpack-cli/src/webpack-cli.ts
  test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
Labels: PR: reviewed-approved

#4059 chore: update cspell to v8
  .gitignore
  lint-staged.config.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#4017 fix: dont override set pkg.json props
  packages/generators/src/handlers/default.ts
  test/utils/test-utils.test.js
Labels: PR: reviewed-approved

#4061 chore(deps): bump
  lint-staged.config.js
  package.json
  packages/generators/package.json
  packages/generators/src/handlers/default.ts
  test/utils/test-utils.test.js
  yarn.lock
Labels: PR: unreviewed

#4060 ci: update github actions
  .github/workflows/dependency-review.yml
  .github/workflows/nodejs.yml
  .github/workflows/update-docs.yml
Labels: PR: review-outdated

#4063 fix(init): use strict checks intemplate configs
  packages/generators/init-template/default/webpack.configjs.tpl
  packages/generators/init-template/react/webpack.config.js.tpl
  test/init/__snapshots__/init.test.js.snap.webpack5
Labels: PR: reviewed-approved

#4062 build!: the minimum required Node.js version is `18.12.0`
  .github/workflows/nodejs.yml
  package.json
  packages/configtest/package.json
  packages/generators/package.json
  packages/info/package.json
  packages/serve/package.json
  packages/webpack-cli/package.json
  test/build/config-format/babel-commonjs/package.json
  test/build/config-format/babel-esm/package.json
  test/build/config-format/typescript-esnext-mjs/package.json
  test/build/config-format/typescript-esnext/package.json
  test/build/config-format/typescript-esnext/typescript.test.js
Labels: PR: reviewed-approved

#4067 chore: remove webpack@4 check from `jest.config.js`
  jest.config.js
Labels: PR: reviewed-approved

#4072 chore: update webpack & options
  OPTIONS.md
  package.json
  yarn.lock
Labels: PR: reviewed-approved, update docs
